(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring coin silver knightsword rope ash hairtonic humanskull - item
		 storage basement bar docks townarch townsquare valley fort shop bank forge mansion cliff junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit bankexit forgeexit mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna peter matthias jordan - character
	)
	(:init
		(at barexit bar)
		(at mel basement)
		(at karina townarch)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at knightshield shop)
		(at fortentrance valley)
		(at mansionentrance cliff)
		(at jordan mansion)
		(at arthur fort)
		(at fortexit fort)
		(at forgeentrance townarch)
		(at ian fort)
		(at camille fort)
		(at bankexit bank)
		(at mel bar)
		(at bucket fort)
		(at phillip fort)
		(at giovanna shop)
		(at shopexit shop)
		(at matthias forge)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected storage basement)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected townarch docks)
		(connected townsquare townarch)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway storage basement)
		(has arthur loveletter)
		(has arthur mushroom)
		(has ian knightsword)
		(has james coin)
		(has arthur rubyring)
		(has ian knightshield)
		(has arthur silver)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto basemententrance basement)
		(leadsto fortexit valley)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item giovanna hairtonic)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) 
			)

		)
	)

)
