(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring coin silver knightsword rope humanskull bouquet hairtonic ash - item
		 storage basement bar docks townarch townsquare valley fort shop bank forge cliff mansion junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit bankexit forgeexit mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna peter matthias jordan - character
	)
	(:init
		(at matthias forge)
		(at ian fort)
		(at arthur cliff)
		(at knightshield shop)
		(at forgeentrance townarch)
		(at bouquet cliff)
		(at humanskull cliff)
		(at bankentrance townsquare)
		(at shopexit shop)
		(at shopentrance townsquare)
		(at fortexit fort)
		(at dave townsquare)
		(at bucket fort)
		(at fortentrance valley)
		(at jordan mansion)
		(at barexit bar)
		(at bankexit bank)
		(at mel bar)
		(at mansionentrance cliff)
		(at camille fort)
		(at phillip fort)
		(at james valley)
		(at giovanna shop)
		(at karina townarch)
		(at frank townsquare)
		(at mel basement)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected townarch docks)
		(connected storage basement)
		(connected townsquare valley)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townarch townsquare)
		(has arthur silver)
		(has ian knightsword)
		(has arthur loveletter)
		(has ian knightshield)
		(has james coin)
		(has arthur rubyring)
		(has arthur mushroom)
		(leadsto fortexit valley)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(wants-item james humanskull)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item giovanna hairtonic)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) 
			)

		)
	)

)
