(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit shopentrance bankentrance bankexit fortentrance fortexit mansionentrance mansionexit hutexit - entrance
		 storage basement bar docks junkyard townarch forge townsquare bank valley fort cliff mansion hut shop - location
		 arthur mel oscar alli dorian karina peter matthias frank dave james ian camille phillip jordan avery roger michael - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope coin silver bucket humanskull bouquet candle tastycupcake hairtonic book rubyring knightshield - item
	)
	(:init
		(at avery mansion)
		(at hutentrance townarch)
		(at james valley)
		(at michael hut)
		(at frank townsquare)
		(at book hut)
		(at mansionexit mansion)
		(at shopentrance townsquare)
		(at matthias forge)
		(at fortexit fort)
		(at bankexit bank)
		(at phillip fort)
		(at tastycupcake hut)
		(at barexit bar)
		(at jordan mansion)
		(at candle mansion)
		(at barentrance docks)
		(at knightshield shop)
		(at bankentrance townsquare)
		(at oscar bar)
		(at dorian townarch)
		(at rope forge)
		(at hairtonic hut)
		(at rubyring shop)
		(at roger mansion)
		(at alli junkyard)
		(at mel storage)
		(at dave townsquare)
		(at knightsword forge)
		(at mel bar)
		(at forgeexit forge)
		(at hutexit hut)
		(at fortentrance valley)
		(at peter forge)
		(at karina townarch)
		(at mansionentrance cliff)
		(at forgeentrance townarch)
		(at camille fort)
		(at basementexit basement)
		(at ian fort)
		(at basemententrance bar)
		(at arthur hut)
		(at mel basement)
		(closed basemententrance)
		(closed shopentrance)
		(connected townsquare cliff)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected basement storage)
		(connected townarch docks)
		(connected valley townsquare)
		(connected storage basement)
		(connected docks junkyard)
		(connected townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway basement storage)
		(has jordan loveletter)
		(has mel basementbucket)
		(has arthur silver)
		(has arthur mushroom)
		(has dorian lovecontract)
		(has arthur humanskull)
		(has arthur bouquet)
		(has james coin)
		(has arthur mirror)
		(has arthur bucket)
		(has alli ash)
		(leadsto fortentrance fort)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto bankexit townsquare)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto mansionexit cliff)
		(leadsto fortexit valley)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item alli tastycupcake)
		(wants-item james humanskull)
		(wants-item arthur ash)
		(wants-item ian knightshield)
		(wants-item dorian rubyring)
		(wants-item jordan lovecontract)
		(wants-item dorian bouquet)
		(wants-item ian knightsword)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur humanskull)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur bucket)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) 
			)

		)
	)

)
