(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit bankexit shopexit - entrance
		 storage basement bar docks townarch junkyard hut forge townsquare valley cliff mansion bank shop fort - location
		 arthur mel oscar dorian karina alli michael peter matthias frank dave james jordan avery roger giovanna - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter mirror ash tastycupcake hairtonic book knightsword rope humanskull bouquet candle coin silver knightshield rubyring - item
	)
	(:init
		(at shopexit shop)
		(at dave townsquare)
		(at book hut)
		(at michael hut)
		(at knightsword forge)
		(at bankexit bank)
		(at shopentrance townsquare)
		(at silver bank)
		(at mushroom townarch)
		(at jordan mansion)
		(at barexit bar)
		(at tastycupcake hut)
		(at matthias forge)
		(at knightshield shop)
		(at candle mansion)
		(at barentrance docks)
		(at oscar bar)
		(at mirror hut)
		(at bouquet cliff)
		(at bankentrance townsquare)
		(at dorian townarch)
		(at james valley)
		(at hutentrance townarch)
		(at rope forge)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at karina townarch)
		(at avery mansion)
		(at alli junkyard)
		(at roger mansion)
		(at hairtonic hut)
		(at mansionexit mansion)
		(at peter forge)
		(at hutexit hut)
		(at fortentrance valley)
		(at mel basement)
		(at forgeentrance townarch)
		(at mel storage)
		(at frank townsquare)
		(at forgeexit forge)
		(at basemententrance bar)
		(at arthur valley)
		(at mel bar)
		(at basementexit basement)
		(closed fortentrance)
		(closed basemententrance)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected storage basement)
		(connected docks townarch)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected basement storage)
		(connected townarch docks)
		(connected townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway basement storage)
		(has james humanskull)
		(has dorian rubyring)
		(has alli ash)
		(has mel basementbucket)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has james coin)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto forgeexit townarch)
		(leadsto fortentrance fort)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian bouquet)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item giovanna hairtonic)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(and (has jordan loveletter) (has jordan lovecontract) )
			(and (has james coin) (has james humanskull) )
		)

	)

)
