(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch forge hut townsquare cliff mansion valley bank shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance mansionentrance - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave jordan - character
	)
	(:init
		(at peter forge)
		(at forgeexit forge)
		(at oscar bar)
		(at jordan mansion)
		(at hairtonic hut)
		(at forgeentrance townarch)
		(at arthur townsquare)
		(at matthias forge)
		(at mirror hut)
		(at shopentrance townsquare)
		(at mel storage)
		(at alli junkyard)
		(at mel basement)
		(at mansionentrance cliff)
		(at bankentrance townsquare)
		(at hutentrance townarch)
		(at dorian townarch)
		(at book hut)
		(at michael hut)
		(at basementexit basement)
		(at basemententrance bar)
		(at tastycupcake hut)
		(at barexit bar)
		(at frank townsquare)
		(at barentrance docks)
		(at dave townsquare)
		(at hutexit hut)
		(at mel bar)
		(at karina townarch)
		(closed basemententrance)
		(closed bankentrance)
		(closed shopentrance)
		(connected junkyard docks)
		(connected storage basement)
		(connected townsquare valley)
		(connected townarch docks)
		(connected basement storage)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected docks junkyard)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(has arthur mushroom)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has alli ash)
		(has arthur loveletter)
		(has arthur rope)
		(has arthur shinykey)
		(has arthur knightsword)
		(leadsto shopentrance shop)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item alli tastycupcake)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
