(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book bucket knightshield coin - item
		 storage basement bar docks junkyard townarch forge hut townsquare valley fort shop cliff mansion bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance fortentrance fortexit mansionentrance - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave james ian camille phillip jordan - character
	)
	(:init
		(at hutexit hut)
		(at fortexit fort)
		(at matthias forge)
		(at shopentrance townsquare)
		(at basemententrance bar)
		(at james valley)
		(at forgeexit forge)
		(at bankentrance townsquare)
		(at dave townsquare)
		(at forgeentrance townarch)
		(at barexit bar)
		(at mirror hut)
		(at oscar bar)
		(at mel storage)
		(at jordan mansion)
		(at bucket fort)
		(at barentrance docks)
		(at arthur townsquare)
		(at mansionentrance cliff)
		(at hutentrance townarch)
		(at phillip fort)
		(at fortentrance valley)
		(at mel bar)
		(at hairtonic hut)
		(at knightsword forge)
		(at peter forge)
		(at basementexit basement)
		(at dorian townarch)
		(at camille fort)
		(at tastycupcake hut)
		(at knightshield shop)
		(at mel basement)
		(at frank townsquare)
		(at alli junkyard)
		(at book hut)
		(at michael hut)
		(at ian fort)
		(at karina townarch)
		(closed basemententrance)
		(closed shopentrance)
		(closed bankentrance)
		(connected storage basement)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected valley townsquare)
		(connected basement storage)
		(connected townarch docks)
		(connected docks townarch)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway junkyard docks)
		(doorway townsquare townarch)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(has alli ash)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has arthur mushroom)
		(has arthur knightsword)
		(has arthur rope)
		(has arthur shinykey)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto fortexit valley)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto basementexit bar)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto forgeexit townarch)
		(leadsto shopentrance shop)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item ian knightshield)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item james coin)
		(wants-item arthur shinykey)
		(wants-item ian knightsword)
		(wants-item jordan loveletter)
		(wants-item alli tastycupcake)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

		)
	)

)
