(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch hut townsquare mansion cliff valley bank forge shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance mansionentrance - entrance
		 arthur mel oscar alli dorian karina michael frank dave jordan - character
	)
	(:init
		(at mel storage)
		(at mushroom townarch)
		(at hutentrance townarch)
		(at barexit bar)
		(at forgeentrance townarch)
		(at mansionentrance cliff)
		(at dorian townarch)
		(at alli junkyard)
		(at shopentrance townsquare)
		(at basementexit basement)
		(at mel basement)
		(at michael hut)
		(at bankentrance townsquare)
		(at barentrance docks)
		(at hutexit hut)
		(at mel bar)
		(at jordan mansion)
		(at karina townarch)
		(at basemententrance bar)
		(at arthur townsquare)
		(at ash townarch)
		(at dave townsquare)
		(at mirror townarch)
		(at frank townsquare)
		(at oscar bar)
		(closed bankentrance)
		(closed basemententrance)
		(closed shopentrance)
		(closed forgeentrance)
		(connected junkyard docks)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected townarch docks)
		(connected townsquare valley)
		(connected basement storage)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(has arthur hairtonic)
		(has arthur book)
		(has alli tastycupcake)
		(has mel basementbucket)
		(has arthur shinykey)
		(has arthur loveletter)
		(has dorian lovecontract)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
