(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book bucket humanskull bouquet candle rubyring coin - item
		 storage basement bar docks junkyard townarch hut townsquare valley fort cliff mansion shop bank forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance fortentrance fortexit mansionentrance mansionexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave james ian camille phillip jordan avery roger - character
	)
	(:init
		(at phillip fort)
		(at humanskull cliff)
		(at fortexit fort)
		(at fortentrance valley)
		(at frank townsquare)
		(at michael hut)
		(at bouquet cliff)
		(at shopentrance townsquare)
		(at hutentrance townarch)
		(at jordan mansion)
		(at barexit bar)
		(at candle mansion)
		(at oscar bar)
		(at bankentrance townsquare)
		(at forgeentrance townarch)
		(at mushroom townarch)
		(at mansionexit mansion)
		(at barentrance docks)
		(at basemententrance bar)
		(at james valley)
		(at mel storage)
		(at rubyring shop)
		(at ian fort)
		(at mirror townarch)
		(at dorian townarch)
		(at dave townsquare)
		(at bucket fort)
		(at mel basement)
		(at mel bar)
		(at hutexit hut)
		(at avery mansion)
		(at alli junkyard)
		(at roger mansion)
		(at karina townarch)
		(at basementexit basement)
		(at ash townarch)
		(at arthur mansion)
		(at camille fort)
		(at mansionentrance cliff)
		(closed basemententrance)
		(closed shopentrance)
		(closed forgeentrance)
		(closed bankentrance)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected storage basement)
		(connected valley townsquare)
		(connected docks townarch)
		(connected junkyard docks)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townsquare townarch)
		(connected basement storage)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway valley townsquare)
		(has dorian lovecontract)
		(has arthur book)
		(has alli tastycupcake)
		(has arthur hairtonic)
		(has arthur loveletter)
		(has arthur shinykey)
		(has mel basementbucket)
		(leadsto fortentrance fort)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto hutexit townarch)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto fortexit valley)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item james coin)
		(wants-item jordan lovecontract)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur hairtonic)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
