(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book bucket humanskull bouquet candle coin silver rubyring - item
		 storage basement bar docks junkyard townarch hut townsquare valley fort cliff mansion bank shop forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance fortentrance fortexit mansionentrance mansionexit bankexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave james ian camille phillip jordan avery roger - character
	)
	(:init
		(at roger mansion)
		(at bucket fort)
		(at camille fort)
		(at candle mansion)
		(at rubyring shop)
		(at oscar bar)
		(at mel storage)
		(at ian fort)
		(at bankentrance townsquare)
		(at fortentrance valley)
		(at shopentrance townsquare)
		(at jordan mansion)
		(at barexit bar)
		(at phillip fort)
		(at ash townarch)
		(at mushroom townarch)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at basemententrance bar)
		(at frank townsquare)
		(at basementexit basement)
		(at silver bank)
		(at mansionexit mansion)
		(at hutentrance townarch)
		(at karina townarch)
		(at avery mansion)
		(at barentrance docks)
		(at humanskull cliff)
		(at alli junkyard)
		(at fortexit fort)
		(at michael hut)
		(at mirror townarch)
		(at dave townsquare)
		(at mel basement)
		(at james valley)
		(at dorian townarch)
		(at mel bar)
		(at hutexit hut)
		(at arthur valley)
		(at mansionentrance cliff)
		(closed shopentrance)
		(closed forgeentrance)
		(closed basemententrance)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected docks townarch)
		(connected storage basement)
		(connected junkyard docks)
		(connected basement storage)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway junkyard docks)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has alli tastycupcake)
		(has arthur hairtonic)
		(has james coin)
		(has arthur bouquet)
		(has arthur book)
		(has jordan loveletter)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(leadsto fortexit valley)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan lovecontract)
		(wants-item arthur lovecontract)
		(wants-item james humanskull)
		(wants-item arthur shinykey)
		(wants-item dorian rubyring)
		(wants-item dorian bouquet)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur book)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
			(and (has james coin) (has james humanskull) )
		)

	)

)
