(open arthur barexit bar)
(move-through-entrance arthur bar barexit docks)
(move-through-doorway arthur townsquare townarch)
(move-through-doorway arthur townsquare townarch)
(move-through-doorway arthur townsquare townarch)
(move-through-doorway arthur townsquare townarch)
(move-through-doorway arthur townarch docks)
(move-through-entrance arthur docks barentrance bar)
(pickup arthur shinykey bar)
(move-through-entrance arthur bar barexit docks)
(unlock-entrance arthur shinykey bankentrance townsquare)
(open arthur bankentrance townsquare)
(pickup arthur coin bank)
(move-through-entrance arthur bank bankexit townsquare)
(give arthur coin james valley)
(move-through-doorway arthur townsquare townarch)
(move-through-entrance arthur townsquare bankentrance bank)
(move-through-entrance arthur bank bankexit townsquare)
(move-through-doorway arthur townsquare townarch)
(move-through-doorway arthur townarch docks)
