(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver bucket knightshield rubyring humanskull bouquet candle ash - item
		 storage basement bar docks townarch forge hut townsquare bank valley fort shop cliff mansion junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit fortentrance fortexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave james ian camille phillip giovanna jordan avery roger - character
	)
	(:init
		(at fortentrance valley)
		(at frank townsquare)
		(at bankentrance townsquare)
		(at tastycupcake townarch)
		(at basemententrance bar)
		(at dave townsquare)
		(at oscar bar)
		(at rope townarch)
		(at camille fort)
		(at candle mansion)
		(at mushroom townarch)
		(at bouquet cliff)
		(at michael hut)
		(at phillip fort)
		(at barexit bar)
		(at fortexit fort)
		(at jordan mansion)
		(at matthias forge)
		(at shopentrance townsquare)
		(at book townarch)
		(at forgeentrance townarch)
		(at bankexit bank)
		(at dorian townarch)
		(at bucket fort)
		(at basementexit basement)
		(at mel basement)
		(at peter forge)
		(at karina townarch)
		(at hutexit hut)
		(at silver townsquare)
		(at mel storage)
		(at hutentrance townarch)
		(at knightsword forge)
		(at rubyring townsquare)
		(at james valley)
		(at avery mansion)
		(at humanskull cliff)
		(at barentrance docks)
		(at giovanna shop)
		(at roger mansion)
		(at shopexit shop)
		(at arthur mansion)
		(at mel bar)
		(at coin townsquare)
		(at mansionexit mansion)
		(at forgeexit forge)
		(at ian fort)
		(at mansionentrance cliff)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected townsquare valley)
		(connected docks townarch)
		(connected storage basement)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected basement storage)
		(doorway townsquare valley)
		(doorway townarch docks)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway cliff townsquare)
		(has arthur loveletter)
		(has ian knightshield)
		(has mel basementbucket)
		(has giovanna hairtonic)
		(has dorian lovecontract)
		(has ian knightsword)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto shopexit townsquare)
		(leadsto bankexit townsquare)
		(leadsto fortexit valley)
		(leadsto barexit docks)
		(leadsto fortentrance fort)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item james coin)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item jordan lovecontract)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) 
			)

		)
	)

)
