(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 towngate - door
		 arthur mel dorian karina michael peter matthias frank dave giovanna james ian camille phillip jordan avery roger - character
		 shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope knightshield rubyring bucket humanskull bouquet candle - item
		 bar docks townarch hut forge townsquare shop valley fort cliff mansion - location
		 barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance shopexit fortentrance fortexit mansionentrance mansionexit - entrance
	)
	(:init
		(at karina townarch)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at rubyring shop)
		(at ian fort)
		(at roger mansion)
		(at fortentrance valley)
		(at mansionexit mansion)
		(at knightshield shop)
		(at giovanna shop)
		(at mel bar)
		(at hutexit hut)
		(at phillip fort)
		(at frank townsquare)
		(at michael hut)
		(at fortexit fort)
		(at barentrance docks)
		(at camille fort)
		(at dorian townarch)
		(at peter forge)
		(at dave townsquare)
		(at avery mansion)
		(at knightsword forge)
		(at hutentrance townarch)
		(at james valley)
		(at matthias forge)
		(at shopentrance townsquare)
		(at jordan mansion)
		(at barexit bar)
		(at forgeentrance townarch)
		(at arthur townarch)
		(at forgeexit forge)
		(at bankentrance townsquare)
		(closed bankentrance)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected docks junkyard)
		(connected valley townsquare)
		(connected townsquare townarch)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(has arthur tastycupcake)
		(has giovanna hairtonic)
		(has arthur knightshield)
		(has arthur candle)
		(has arthur bouquet)
		(has jordan loveletter)
		(has ian knightsword)
		(has dorian lovecontract)
		(has arthur shinykey)
		(has arthur rubyring)
		(has arthur bucket)
		(has arthur rope)
		(has arthur book)
		(has arthur mushroom)
		(has arthur humanskull)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto mansionexit cliff)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item james coin)
		(wants-item jordan lovecontract)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item ian knightshield)
		(wants-item dorian rubyring)
		(wants-item dorian bouquet)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur candle)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur tastycupcake)
		(willing-to-give-item arthur humanskull)
	)
	(:goal
	  (AND
		
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has james coin)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
