(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle mirror ash coin silver knightshield rubyring tastycupcake - item
		 storage basement bar docks townarch townsquare valley cliff mansion junkyard bank shop hut fort forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance mansionexit bankexit shopexit hutexit - entrance
		 arthur mel oscar dorian karina frank dave james jordan avery roger alli giovanna - character
	)
	(:init
		(at avery mansion)
		(at fortentrance valley)
		(at mel storage)
		(at candle mansion)
		(at basemententrance bar)
		(at giovanna shop)
		(at basementexit basement)
		(at bankentrance townsquare)
		(at jordan mansion)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at oscar bar)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at mushroom townarch)
		(at bankexit bank)
		(at barentrance docks)
		(at frank townsquare)
		(at knightshield shop)
		(at hutexit hut)
		(at alli junkyard)
		(at mansionexit mansion)
		(at mirror townarch)
		(at dave townsquare)
		(at roger mansion)
		(at barexit bar)
		(at dorian townarch)
		(at tastycupcake hut)
		(at james valley)
		(at mel basement)
		(at shopexit shop)
		(at arthur shop)
		(at mansionentrance cliff)
		(at karina townarch)
		(at mel bar)
		(at rubyring shop)
		(closed hutentrance)
		(closed forgeentrance)
		(closed fortentrance)
		(connected townsquare cliff)
		(connected storage basement)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected basement storage)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected townarch docks)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(has arthur coin)
		(has jordan loveletter)
		(has arthur silver)
		(has dorian bouquet)
		(has jordan lovecontract)
		(has alli ash)
		(has mel basementbucket)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto shopexit townsquare)
		(leadsto barentrance bar)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(wants-item alli tastycupcake)
		(wants-item james coin)
		(wants-item arthur ash)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur silver)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
			(has james coin) 
		)

	)

)
