(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle mirror ash coin silver tastycupcake rubyring - item
		 storage basement bar docks townarch townsquare valley cliff mansion junkyard bank hut shop forge fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance mansionexit bankexit hutexit - entrance
		 arthur mel oscar dorian karina frank dave james jordan avery roger alli - character
	)
	(:init
		(at basementexit basement)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at barentrance docks)
		(at mushroom townarch)
		(at bankexit bank)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at mel basement)
		(at candle mansion)
		(at avery mansion)
		(at mirror townarch)
		(at oscar bar)
		(at mel storage)
		(at dave townsquare)
		(at basemententrance bar)
		(at rubyring shop)
		(at humanskull cliff)
		(at tastycupcake hut)
		(at dorian townarch)
		(at roger mansion)
		(at fortentrance valley)
		(at jordan mansion)
		(at alli junkyard)
		(at hutentrance townarch)
		(at barexit bar)
		(at mel bar)
		(at hutexit hut)
		(at frank townsquare)
		(at mansionentrance cliff)
		(at mansionexit mansion)
		(at james valley)
		(at karina townarch)
		(closed fortentrance)
		(closed shopentrance)
		(closed forgeentrance)
		(closed hutentrance)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected junkyard docks)
		(connected valley townsquare)
		(connected storage basement)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected docks junkyard)
		(connected townsquare valley)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway junkyard docks)
		(has alli ash)
		(has jordan loveletter)
		(has mel basementbucket)
		(has arthur coin)
		(has jordan lovecontract)
		(has dorian bouquet)
		(has arthur silver)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item alli tastycupcake)
		(wants-item dorian rubyring)
		(wants-item james coin)
		(wants-item arthur ash)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
			(has james coin) 
		)

	)

)
