(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book knightshield rubyring - item
		 storage basement bar docks junkyard townarch forge hut townsquare shop cliff valley bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance shopexit - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan - character
	)
	(:init
		(at ash townarch)
		(at hutexit hut)
		(at book townarch)
		(at mushroom townarch)
		(at bankentrance townsquare)
		(at mel basement)
		(at hutentrance townarch)
		(at barexit bar)
		(at shopentrance townsquare)
		(at knightshield townsquare)
		(at shopexit shop)
		(at rope townarch)
		(at peter forge)
		(at forgeexit forge)
		(at alli junkyard)
		(at karina townarch)
		(at dave townsquare)
		(at giovanna shop)
		(at barentrance docks)
		(at rubyring townsquare)
		(at knightsword townarch)
		(at mel bar)
		(at michael hut)
		(at dorian townarch)
		(at mirror townarch)
		(at arthur townsquare)
		(at forgeentrance townarch)
		(at matthias forge)
		(at frank townsquare)
		(closed bankentrance)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected townarch docks)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected docks junkyard)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway townsquare valley)
		(has giovanna hairtonic)
		(has arthur loveletter)
		(has alli tastycupcake)
		(has dorian lovecontract)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
