(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book knightshield rubyring coin silver humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch forge hut townsquare shop bank cliff mansion valley - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance shopexit bankexit mansionentrance mansionexit - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan avery roger - character
	)
	(:init
		(at hutexit hut)
		(at bankexit bank)
		(at candle mansion)
		(at shopentrance townsquare)
		(at barentrance docks)
		(at dave townsquare)
		(at bankentrance townsquare)
		(at mushroom townarch)
		(at peter forge)
		(at jordan mansion)
		(at bouquet cliff)
		(at barexit bar)
		(at rubyring townsquare)
		(at arthur mansion)
		(at matthias forge)
		(at knightsword townarch)
		(at book townarch)
		(at ash townarch)
		(at forgeentrance townarch)
		(at frank townsquare)
		(at rope townarch)
		(at shopexit shop)
		(at mansionexit mansion)
		(at mel bar)
		(at knightshield townsquare)
		(at dorian townarch)
		(at forgeexit forge)
		(at coin townsquare)
		(at michael hut)
		(at humanskull cliff)
		(at mirror townarch)
		(at hutentrance townarch)
		(at silver townsquare)
		(at karina townarch)
		(at roger mansion)
		(at rubyring shop)
		(at alli junkyard)
		(at giovanna shop)
		(at avery mansion)
		(at mansionentrance cliff)
		(at mel basement)
		(connected townarch docks)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected townsquare townarch)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(has giovanna hairtonic)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has alli tastycupcake)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto bankexit townsquare)
		(leadsto hutexit townarch)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto shopexit townsquare)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
