(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book knightshield rubyring - item
		 storage basement bar docks junkyard townarch forge hut townsquare shop valley cliff bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance shopexit - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan - character
	)
	(:init
		(at alli junkyard)
		(at rubyring townsquare)
		(at frank townsquare)
		(at karina townarch)
		(at forgeentrance townarch)
		(at hutexit hut)
		(at mushroom townarch)
		(at hutentrance townarch)
		(at forgeexit forge)
		(at knightsword townarch)
		(at book townarch)
		(at dorian townarch)
		(at barexit bar)
		(at shopentrance townsquare)
		(at barentrance docks)
		(at bankentrance townsquare)
		(at michael hut)
		(at rope townarch)
		(at mel bar)
		(at peter forge)
		(at shopexit shop)
		(at mirror townarch)
		(at knightshield townsquare)
		(at matthias forge)
		(at giovanna shop)
		(at shinykey townsquare)
		(at dave townsquare)
		(at ash townarch)
		(at arthur townsquare)
		(at mel basement)
		(closed bankentrance)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected junkyard docks)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(has giovanna hairtonic)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has alli tastycupcake)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
