(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch forge hut townsquare cliff valley shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave jordan - character
	)
	(:init
		(at arthur townsquare)
		(at mushroom townarch)
		(at forgeentrance townarch)
		(at karina townarch)
		(at hutexit hut)
		(at hutentrance townarch)
		(at hairtonic townarch)
		(at knightsword townarch)
		(at book townarch)
		(at forgeexit forge)
		(at barexit bar)
		(at shopentrance townsquare)
		(at shinykey townsquare)
		(at bankentrance townsquare)
		(at barentrance docks)
		(at mel bar)
		(at michael hut)
		(at peter forge)
		(at matthias forge)
		(at mel basement)
		(at alli junkyard)
		(at rope townarch)
		(at ash townarch)
		(at dave townsquare)
		(at dorian townarch)
		(at mirror townarch)
		(at frank townsquare)
		(closed shopentrance)
		(closed bankentrance)
		(connected junkyard docks)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has alli tastycupcake)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
