(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book knightshield rubyring coin silver humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch forge hut townsquare shop bank cliff mansion valley fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance shopexit bankexit mansionentrance mansionexit fortentrance - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan avery roger james - character
	)
	(:init
		(at rubyring shop)
		(at dave townsquare)
		(at humanskull cliff)
		(at michael hut)
		(at dorian townarch)
		(at hutentrance townarch)
		(at matthias forge)
		(at book townarch)
		(at shopentrance townsquare)
		(at mansionexit mansion)
		(at barexit bar)
		(at jordan mansion)
		(at bankentrance townsquare)
		(at rope townarch)
		(at candle mansion)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at mushroom townarch)
		(at peter forge)
		(at james valley)
		(at knightsword townarch)
		(at rubyring townsquare)
		(at alli junkyard)
		(at roger mansion)
		(at mirror townarch)
		(at knightshield townsquare)
		(at arthur valley)
		(at avery mansion)
		(at giovanna shop)
		(at mel basement)
		(at fortentrance valley)
		(at mel bar)
		(at silver townsquare)
		(at karina townarch)
		(at shopexit shop)
		(at ash townarch)
		(at frank townsquare)
		(at coin townsquare)
		(at barentrance docks)
		(at forgeexit forge)
		(at mansionentrance cliff)
		(at hutexit hut)
		(closed fortentrance)
		(connected valley townsquare)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected townarch docks)
		(connected docks junkyard)
		(doorway junkyard docks)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(has giovanna hairtonic)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has dorian bouquet)
		(has alli tastycupcake)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto fortentrance fort)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto hutexit townarch)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
