(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope mirror ash - item
		 storage basement bar docks townarch hut forge junkyard mansion cliff townsquare - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit mansionentrance bankentrance - entrance
		 arthur mel oscar dorian karina michael peter matthias alli jordan - character
	)
	(:init
		(at forgeentrance townarch)
		(at rope forge)
		(at arthur hut)
		(at mansionentrance cliff)
		(at hutexit hut)
		(at alli junkyard)
		(at dorian townarch)
		(at mel storage)
		(at peter forge)
		(at barexit bar)
		(at karina townarch)
		(at michael hut)
		(at forgeexit forge)
		(at mushroom junkyard)
		(at matthias forge)
		(at basemententrance bar)
		(at jordan mansion)
		(at hutentrance townarch)
		(at ash bar)
		(at barentrance docks)
		(at tastycupcake hut)
		(at mel basement)
		(at basementexit basement)
		(at oscar bar)
		(at mel bar)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected basement storage)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected storage basement)
		(connected junkyard docks)
		(connected townarch docks)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway basement storage)
		(doorway docks junkyard)
		(has dorian lovecontract)
		(has arthur knightsword)
		(has arthur mirror)
		(has arthur loveletter)
		(has alli tastycupcake)
		(has arthur book)
		(has arthur hairtonic)
		(has mel basementbucket)
		(has arthur shinykey)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur hairtonic)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
