(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book bucket knightshield ash coin - item
		 storage basement bar docks townarch forge hut townsquare valley fort shop cliff mansion junkyard bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance fortentrance fortexit mansionentrance - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave james ian camille phillip jordan - character
	)
	(:init
		(at karina townarch)
		(at knightsword townarch)
		(at bankentrance townsquare)
		(at hutentrance townarch)
		(at bucket fort)
		(at oscar bar)
		(at james valley)
		(at rope townarch)
		(at arthur fort)
		(at dorian townarch)
		(at matthias forge)
		(at jordan mansion)
		(at barexit bar)
		(at phillip fort)
		(at fortexit fort)
		(at mushroom townarch)
		(at shopentrance townsquare)
		(at mel storage)
		(at knightsword forge)
		(at forgeexit forge)
		(at basementexit basement)
		(at ian fort)
		(at fortentrance valley)
		(at hutexit hut)
		(at book hut)
		(at dave townsquare)
		(at peter forge)
		(at barentrance docks)
		(at michael hut)
		(at knightshield shop)
		(at basemententrance bar)
		(at frank townsquare)
		(at forgeentrance townarch)
		(at mansionentrance cliff)
		(at tastycupcake townarch)
		(at camille fort)
		(at mel bar)
		(at hairtonic townarch)
		(at mel basement)
		(closed bankentrance)
		(closed basemententrance)
		(closed shopentrance)
		(connected docks townarch)
		(connected storage basement)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch townsquare)
		(doorway townarch townsquare)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway townsquare townarch)
		(has mel basementbucket)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has arthur shinykey)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto fortexit valley)
		(leadsto forgeexit townarch)
		(leadsto fortentrance fort)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item james coin)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item ian knightsword)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item ian knightshield)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
