(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book ash coin - item
		 storage basement bar docks townarch forge hut townsquare valley mansion cliff junkyard fort shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance fortentrance mansionentrance - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave james jordan - character
	)
	(:init
		(at james valley)
		(at bankentrance townsquare)
		(at frank townsquare)
		(at mushroom townarch)
		(at matthias forge)
		(at book hut)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at tastycupcake townarch)
		(at knightsword townarch)
		(at barentrance docks)
		(at oscar bar)
		(at peter forge)
		(at basementexit basement)
		(at rope townarch)
		(at basemententrance bar)
		(at forgeexit forge)
		(at mansionentrance cliff)
		(at hutentrance townarch)
		(at dave townsquare)
		(at mel storage)
		(at fortentrance valley)
		(at jordan mansion)
		(at dorian townarch)
		(at barexit bar)
		(at michael hut)
		(at hutexit hut)
		(at hairtonic townarch)
		(at mel basement)
		(at karina townarch)
		(at arthur valley)
		(at mel bar)
		(closed basemententrance)
		(closed shopentrance)
		(closed bankentrance)
		(closed fortentrance)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected valley townsquare)
		(connected docks townarch)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway basement storage)
		(has arthur shinykey)
		(has arthur loveletter)
		(has mel basementbucket)
		(has dorian lovecontract)
		(leadsto basemententrance basement)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto fortentrance fort)
		(leadsto shopentrance shop)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item james coin)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
