(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope ash - item
		 storage basement bar docks townarch forge cliff mansion townsquare junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit mansionentrance bankentrance - entrance
		 arthur mel oscar dorian karina peter matthias jordan - character
	)
	(:init
		(at matthias forge)
		(at barexit bar)
		(at mel basement)
		(at arthur forge)
		(at peter forge)
		(at oscar bar)
		(at dorian townarch)
		(at forgeexit forge)
		(at basementexit basement)
		(at basemententrance bar)
		(at jordan mansion)
		(at forgeentrance townarch)
		(at mel bar)
		(at hutentrance townarch)
		(at mansionentrance cliff)
		(at mel storage)
		(at barentrance docks)
		(at karina townarch)
		(closed hutentrance)
		(closed basemententrance)
		(connected docks junkyard)
		(connected basement storage)
		(connected townarch docks)
		(connected storage basement)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway docks townarch)
		(has arthur knightsword)
		(has arthur shinykey)
		(has dorian lovecontract)
		(has arthur rope)
		(has arthur mushroom)
		(has mel basementbucket)
		(has arthur loveletter)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rope)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
