(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter coin silver tastycupcake - item
		 storage basement bar docks junkyard townarch townsquare bank mansion hut cliff valley shop forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit hutexit mansionentrance - entrance
		 arthur mel oscar alli dorian karina frank dave jordan - character
	)
	(:init
		(at jordan mansion)
		(at hutentrance townarch)
		(at arthur townsquare)
		(at mel storage)
		(at dave townsquare)
		(at basemententrance bar)
		(at oscar bar)
		(at mirror junkyard)
		(at dorian townarch)
		(at basementexit basement)
		(at forgeentrance townarch)
		(at karina townarch)
		(at bankentrance townsquare)
		(at barentrance docks)
		(at mansionentrance cliff)
		(at barexit bar)
		(at bankexit bank)
		(at shopentrance townsquare)
		(at tastycupcake hut)
		(at frank townsquare)
		(at hutexit hut)
		(at mel bar)
		(at mel basement)
		(at alli junkyard)
		(closed hutentrance)
		(closed shopentrance)
		(closed forgeentrance)
		(connected docks townarch)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected basement storage)
		(connected townarch townsquare)
		(connected townsquare valley)
		(connected storage basement)
		(connected docks junkyard)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(has arthur silver)
		(has arthur mushroom)
		(has arthur coin)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has alli ash)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto bankexit townsquare)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item alli tastycupcake)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur silver)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
