(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope - item
		 storage basement bar docks junkyard townarch hut forge townsquare mansion cliff valley shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance mansionentrance - entrance
		 arthur mel oscar alli dorian karina michael peter matthias frank dave jordan - character
	)
	(:init
		(at hutentrance townarch)
		(at matthias forge)
		(at arthur townsquare)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at frank townsquare)
		(at mirror junkyard)
		(at mel storage)
		(at oscar bar)
		(at forgeexit forge)
		(at peter forge)
		(at basementexit basement)
		(at barentrance docks)
		(at basemententrance bar)
		(at rope forge)
		(at mel bar)
		(at hutexit hut)
		(at karina townarch)
		(at bankentrance townsquare)
		(at mansionentrance cliff)
		(at mel basement)
		(at alli junkyard)
		(at michael hut)
		(at book hut)
		(at barexit bar)
		(at jordan mansion)
		(at knightsword forge)
		(at dave townsquare)
		(at dorian townarch)
		(closed shopentrance)
		(closed bankentrance)
		(connected docks townarch)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch docks)
		(connected storage basement)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected townsquare townarch)
		(doorway townsquare valley)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(has arthur shinykey)
		(has arthur mushroom)
		(has arthur hairtonic)
		(has arthur ash)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has alli tastycupcake)
		(has mel basementbucket)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto forgeexit townarch)
		(leadsto basemententrance basement)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
