(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch hut cliff mansion townsquare forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit mansionentrance bankentrance - entrance
		 arthur mel oscar alli dorian karina michael jordan - character
	)
	(:init
		(at mel storage)
		(at alli junkyard)
		(at arthur townarch)
		(at barexit bar)
		(at dorian townarch)
		(at mirror junkyard)
		(at basemententrance bar)
		(at karina townarch)
		(at jordan mansion)
		(at mansionentrance cliff)
		(at barentrance docks)
		(at mel basement)
		(at mel bar)
		(at oscar bar)
		(at michael hut)
		(at hutexit hut)
		(at book hut)
		(at forgeentrance townarch)
		(at hutentrance townarch)
		(at basementexit basement)
		(closed forgeentrance)
		(connected docks junkyard)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected basement storage)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected storage basement)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(has dorian lovecontract)
		(has arthur ash)
		(has arthur mushroom)
		(has alli tastycupcake)
		(has arthur shinykey)
		(has arthur loveletter)
		(has mel basementbucket)
		(has arthur hairtonic)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
