(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet candle tastycupcake rubyring - item
		 storage basement bar docks junkyard townarch townsquare valley cliff mansion hut forge shop fort bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance mansionexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave james jordan avery roger - character
	)
	(:init
		(at dorian townarch)
		(at shopentrance townsquare)
		(at candle mansion)
		(at oscar bar)
		(at jordan mansion)
		(at forgeentrance townarch)
		(at arthur mansion)
		(at basemententrance bar)
		(at basementexit basement)
		(at fortentrance valley)
		(at frank townsquare)
		(at bankentrance townsquare)
		(at mel bar)
		(at mel basement)
		(at avery mansion)
		(at bouquet cliff)
		(at mansionentrance cliff)
		(at james valley)
		(at hutexit hut)
		(at mansionexit mansion)
		(at barentrance docks)
		(at hutentrance townarch)
		(at barexit bar)
		(at dave townsquare)
		(at tastycupcake hut)
		(at roger mansion)
		(at alli junkyard)
		(at karina townarch)
		(at mel storage)
		(at humanskull cliff)
		(closed forgeentrance)
		(closed basemententrance)
		(closed hutentrance)
		(closed bankentrance)
		(closed fortentrance)
		(closed shopentrance)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected townarch docks)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected basement storage)
		(connected junkyard docks)
		(doorway junkyard docks)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway townsquare townarch)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has jordan loveletter)
		(has alli ash)
		(has arthur shinykey)
		(has arthur mushroom)
		(has arthur mirror)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian bouquet)
		(wants-item arthur ash)
		(wants-item alli tastycupcake)
		(wants-item dorian rubyring)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
