(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit mansionentrance bankentrance - entrance
		 storage basement bar docks junkyard townarch forge hut cliff mansion townsquare - location
		 arthur mel oscar alli dorian karina peter matthias michael jordan - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book - item
	)
	(:init
		(at mel storage)
		(at mushroom townarch)
		(at mel basement)
		(at barexit bar)
		(at karina townarch)
		(at hutentrance townarch)
		(at hutexit hut)
		(at basementexit basement)
		(at book hut)
		(at arthur hut)
		(at hairtonic hut)
		(at dorian townarch)
		(at forgeexit forge)
		(at knightsword forge)
		(at alli junkyard)
		(at barentrance docks)
		(at rope forge)
		(at basemententrance bar)
		(at oscar bar)
		(at michael hut)
		(at mel bar)
		(at peter forge)
		(at mansionentrance cliff)
		(at matthias forge)
		(at jordan mansion)
		(at forgeentrance townarch)
		(at mirror townarch)
		(closed basemententrance)
		(connected docks junkyard)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected basement storage)
		(connected storage basement)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected townarch townsquare)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway storage basement)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(has arthur tastycupcake)
		(has arthur loveletter)
		(has arthur shinykey)
		(has mel basementbucket)
		(has alli ash)
		(has dorian lovecontract)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item alli tastycupcake)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur tastycupcake)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
