(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope - item
		 storage basement bar docks junkyard townarch hut forge cliff mansion townsquare - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit mansionentrance bankentrance - entrance
		 arthur mel oscar alli dorian karina michael peter matthias jordan - character
	)
	(:init
		(at peter forge)
		(at hutexit hut)
		(at book hut)
		(at barexit bar)
		(at mel basement)
		(at mel bar)
		(at basementexit basement)
		(at hutentrance townarch)
		(at jordan mansion)
		(at arthur forge)
		(at dorian townarch)
		(at forgeexit forge)
		(at forgeentrance townarch)
		(at rope forge)
		(at karina townarch)
		(at mansionentrance cliff)
		(at barentrance docks)
		(at matthias forge)
		(at michael hut)
		(at mirror junkyard)
		(at knightsword forge)
		(at basemententrance bar)
		(at oscar bar)
		(at mel storage)
		(at alli junkyard)
		(connected townarch docks)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected storage basement)
		(connected junkyard docks)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected basement storage)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway townarch docks)
		(has dorian lovecontract)
		(has arthur shinykey)
		(has arthur loveletter)
		(has arthur hairtonic)
		(has arthur mushroom)
		(has arthur ash)
		(has alli tastycupcake)
		(has mel basementbucket)
		(leadsto forgeexit townarch)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
