(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance bankentrance - entrance
		 storage basement bar docks townarch townsquare junkyard forge hut - location
		 arthur mel oscar dorian karina - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter ash - item
	)
	(:init
		(at barexit bar)
		(at shinykey bar)
		(at karina townarch)
		(at mel bar)
		(at oscar bar)
		(at basemententrance bar)
		(at mel storage)
		(at dorian townarch)
		(at forgeentrance townarch)
		(at mel basement)
		(at barentrance docks)
		(at arthur townarch)
		(at hutentrance townarch)
		(at basementexit basement)
		(closed hutentrance)
		(closed forgeentrance)
		(connected docks junkyard)
		(connected storage basement)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected basement storage)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway docks junkyard)
		(has dorian lovecontract)
		(has arthur mushroom)
		(has dorian loveletter)
		(has mel basementbucket)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item arthur loveletter)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
	)
)
