(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit shopexit fortentrance hutexit - entrance
		 storage basement bar docks junkyard townarch townsquare cliff mansion shop valley hut fort bank forge - location
		 arthur mel oscar alli dorian karina frank dave jordan avery roger giovanna james - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet candle knightshield rubyring tastycupcake hairtonic coin - item
	)
	(:init
		(at mansionexit mansion)
		(at shopentrance townsquare)
		(at james valley)
		(at humanskull townarch)
		(at bankentrance townsquare)
		(at dorian townarch)
		(at avery mansion)
		(at mel basement)
		(at mel storage)
		(at oscar bar)
		(at barexit bar)
		(at dave townsquare)
		(at jordan mansion)
		(at basemententrance bar)
		(at mirror junkyard)
		(at candle mansion)
		(at karina townarch)
		(at arthur valley)
		(at frank townsquare)
		(at rubyring shop)
		(at mel bar)
		(at roger mansion)
		(at knightshield shop)
		(at hutentrance townarch)
		(at tastycupcake hut)
		(at barentrance docks)
		(at hutexit hut)
		(at alli junkyard)
		(at giovanna shop)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at fortentrance valley)
		(at forgeentrance townarch)
		(at basementexit basement)
		(closed fortentrance)
		(closed barentrance)
		(closed basemententrance)
		(closed hutentrance)
		(closed bankentrance)
		(closed forgeentrance)
		(connected townsquare cliff)
		(connected storage basement)
		(connected valley townsquare)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway townsquare valley)
		(has arthur shinykey)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur mushroom)
		(has dorian bouquet)
		(has jordan loveletter)
		(has alli ash)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto mansionexit cliff)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(wants-item alli tastycupcake)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item giovanna hairtonic)
		(wants-item arthur ash)
		(wants-item james coin)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		(or
			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

		)
	)

)
