(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle tastycupcake hairtonic book rubyring ash - item
		 storage basement bar docks townarch townsquare cliff mansion hut valley shop junkyard fort bank forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit hutexit fortentrance - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger michael james - character
	)
	(:init
		(at rubyring shop)
		(at bankentrance townsquare)
		(at candle mansion)
		(at oscar bar)
		(at barentrance docks)
		(at jordan mansion)
		(at barexit bar)
		(at shopentrance townsquare)
		(at tastycupcake hut)
		(at mansionexit mansion)
		(at michael hut)
		(at book hut)
		(at frank townsquare)
		(at humanskull cliff)
		(at hutentrance townarch)
		(at basemententrance bar)
		(at james valley)
		(at shinykey bar)
		(at roger mansion)
		(at mel storage)
		(at dorian townarch)
		(at hairtonic hut)
		(at avery mansion)
		(at mel basement)
		(at mel bar)
		(at arthur valley)
		(at karina townarch)
		(at mansionentrance cliff)
		(at forgeentrance townarch)
		(at dave townsquare)
		(at basementexit basement)
		(at fortentrance valley)
		(at hutexit hut)
		(closed shopentrance)
		(closed fortentrance)
		(closed forgeentrance)
		(closed bankentrance)
		(connected storage basement)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected basement storage)
		(connected townarch docks)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway storage basement)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has mel basementbucket)
		(has dorian bouquet)
		(has arthur mushroom)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto hutexit townarch)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		
			(and (has jordan loveletter) (has jordan lovecontract) )
		

	)

)
