(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle tastycupcake hairtonic book knightshield rubyring ash coin - item
		 storage basement bar docks townarch townsquare cliff mansion hut valley shop junkyard fort bank forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit hutexit fortentrance shopexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger michael james giovanna - character
	)
	(:init
		(at mel storage)
		(at humanskull cliff)
		(at dorian townarch)
		(at book hut)
		(at michael hut)
		(at hutentrance townarch)
		(at mansionexit mansion)
		(at jordan mansion)
		(at knightshield shop)
		(at barentrance docks)
		(at tastycupcake hut)
		(at barexit bar)
		(at bankentrance townsquare)
		(at candle mansion)
		(at oscar bar)
		(at shopentrance townsquare)
		(at frank townsquare)
		(at basemententrance bar)
		(at james valley)
		(at shinykey bar)
		(at karina townarch)
		(at shopexit shop)
		(at avery mansion)
		(at rubyring shop)
		(at hairtonic hut)
		(at mansionentrance cliff)
		(at mel bar)
		(at hutexit hut)
		(at roger mansion)
		(at giovanna shop)
		(at forgeentrance townarch)
		(at mel basement)
		(at dave townsquare)
		(at basementexit basement)
		(at fortentrance valley)
		(at arthur shop)
		(closed forgeentrance)
		(closed bankentrance)
		(closed fortentrance)
		(connected storage basement)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected basement storage)
		(connected townarch docks)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway valley townsquare)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has arthur mushroom)
		(has mel basementbucket)
		(has dorian bouquet)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(leadsto shopexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto hutentrance hut)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item james coin)
		(wants-item arthur shinykey)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		(and
			(and (has jordan loveletter) (has jordan lovecontract) )
			(has james coin) 
		)

	)

)
