(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter ash - item
		 storage basement bar docks townarch junkyard townsquare forge hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance bankentrance - entrance
		 arthur mel oscar dorian karina - character
	)
	(:init
		(at mel basement)
		(at arthur townarch)
		(at barentrance docks)
		(at dorian townarch)
		(at karina townarch)
		(at barexit bar)
		(at hutentrance townarch)
		(at basementexit basement)
		(at basemententrance bar)
		(at mel storage)
		(at oscar bar)
		(at forgeentrance townarch)
		(at shinykey bar)
		(at mel bar)
		(closed hutentrance)
		(closed forgeentrance)
		(connected basement storage)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected storage basement)
		(connected docks townarch)
		(connected townarch docks)
		(doorway townarch townsquare)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway storage basement)
		(has dorian loveletter)
		(has dorian lovecontract)
		(has arthur mushroom)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item arthur loveletter)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		(game-has-been-won)
	)
)
