(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter ash - item
		 storage basement bar docks townarch townsquare valley mansion cliff junkyard forge fort bank hut shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave james jordan - character
	)
	(:init
		(at arthur valley)
		(at bankentrance townsquare)
		(at shopentrance townsquare)
		(at barexit bar)
		(at basementexit basement)
		(at mel basement)
		(at james valley)
		(at fortentrance valley)
		(at oscar bar)
		(at basemententrance bar)
		(at mansionentrance cliff)
		(at dave townsquare)
		(at forgeentrance townarch)
		(at mel bar)
		(at hutentrance townarch)
		(at jordan mansion)
		(at dorian townarch)
		(at barentrance docks)
		(at mel storage)
		(at frank townsquare)
		(at karina townarch)
		(closed fortentrance)
		(closed hutentrance)
		(closed basemententrance)
		(closed bankentrance)
		(closed forgeentrance)
		(closed shopentrance)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected basement storage)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected docks townarch)
		(connected storage basement)
		(connected docks junkyard)
		(connected townsquare cliff)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(has mel basementbucket)
		(has arthur shinykey)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has arthur mushroom)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
