(pickup arthur mushroom docks)
(open arthur hutentrance townarch)
(move-through-entrance arthur townarch hutentrance hut)
(move-through-entrance arthur hut hutexit townarch)
(move-through-doorway arthur townarch docks)
(move-through-doorway arthur docks junkyard)
(pickup arthur rope forge)
(move-through-doorway arthur townarch docks)
(move-through-doorway arthur docks junkyard)
(drop arthur mushroom docks)
(drop arthur rope docks)
(move-through-entrance arthur docks barentrance bar)
(move-through-entrance arthur townarch hutentrance hut)
(move-through-entrance arthur hut hutexit townarch)
(move-through-entrance arthur townarch hutentrance hut)
(pickup arthur tastycupcake hut)
(move-through-entrance arthur hut hutexit townarch)
(move-through-doorway arthur townarch docks)
(move-through-doorway arthur docks junkyard)
(give arthur tastycupcake alli junkyard)
(move-through-door arthur townsquare towngate townarch)
(pickup arthur mirror townarch)
(move-through-doorway arthur townarch docks)
