(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle knightshield rubyring bucket ash - item
		 storage basement bar docks townarch hut forge townsquare valley cliff mansion shop fort junkyard bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit fortexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave james jordan avery roger giovanna ian camille phillip - character
	)
	(:init
		(at mel basement)
		(at mansionentrance cliff)
		(at frank townsquare)
		(at roger mansion)
		(at hairtonic cliff)
		(at phillip fort)
		(at bouquet cliff)
		(at jordan mansion)
		(at forgeexit forge)
		(at shopexit shop)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at oscar bar)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at barexit bar)
		(at candle cliff)
		(at tastycupcake forge)
		(at mel storage)
		(at matthias forge)
		(at karina townarch)
		(at ian fort)
		(at humanskull cliff)
		(at peter forge)
		(at camille fort)
		(at basementexit basement)
		(at book cliff)
		(at mushroom cliff)
		(at mel bar)
		(at michael hut)
		(at dave townsquare)
		(at basemententrance bar)
		(at barentrance docks)
		(at fortentrance valley)
		(at mansionexit mansion)
		(at giovanna shop)
		(at hutentrance townarch)
		(at avery mansion)
		(at fortexit fort)
		(at james valley)
		(at dorian townarch)
		(at hutexit hut)
		(closed basemententrance)
		(closed bankentrance)
		(connected cliff townsquare)
		(connected storage basement)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected docks townarch)
		(connected townarch docks)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway docks townarch)
		(has arthur knightshield)
		(has arthur rope)
		(has mel basementbucket)
		(has arthur loveletter)
		(has arthur rubyring)
		(has arthur bucket)
		(has arthur knightsword)
		(has dorian lovecontract)
		(has arthur shinykey)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto shopentrance shop)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item jordan lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
