(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle knightshield rubyring bucket ash - item
		 storage basement bar docks townarch hut forge townsquare valley cliff mansion shop fort junkyard bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit fortexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave james jordan avery roger giovanna ian camille phillip - character
	)
	(:init
		(at arthur townarch)
		(at humanskull cliff)
		(at rubyring cliff)
		(at james valley)
		(at frank townsquare)
		(at knightshield cliff)
		(at fortexit fort)
		(at michael hut)
		(at shopentrance townsquare)
		(at hairtonic cliff)
		(at oscar bar)
		(at forgeentrance townarch)
		(at forgeexit forge)
		(at jordan mansion)
		(at bankentrance townsquare)
		(at candle cliff)
		(at matthias forge)
		(at barexit bar)
		(at mansionexit mansion)
		(at fortentrance valley)
		(at tastycupcake forge)
		(at basemententrance bar)
		(at hutentrance townarch)
		(at barentrance docks)
		(at ian fort)
		(at karina townarch)
		(at roger mansion)
		(at dave townsquare)
		(at dorian townarch)
		(at phillip fort)
		(at avery mansion)
		(at mel storage)
		(at mushroom cliff)
		(at hutexit hut)
		(at mel basement)
		(at mansionentrance cliff)
		(at shopexit shop)
		(at book cliff)
		(at giovanna shop)
		(at camille fort)
		(at bucket cliff)
		(at basementexit basement)
		(at peter forge)
		(at mel bar)
		(closed bankentrance)
		(closed basemententrance)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected valley townsquare)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch townsquare)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway docks townarch)
		(has dorian lovecontract)
		(has arthur rope)
		(has arthur shinykey)
		(has arthur loveletter)
		(has mel basementbucket)
		(has arthur knightsword)
		(has arthur bouquet)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto shopexit townsquare)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto fortexit valley)
		(leadsto mansionexit cliff)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(wants-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
