(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book bucket humanskull bouquet candle coin silver rubyring - item
		 storage basement bar docks junkyard townarch hut townsquare valley fort cliff mansion bank shop forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance fortentrance fortexit mansionentrance mansionexit bankexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave james ian camille phillip jordan avery roger - character
	)
	(:init
		(at phillip fort)
		(at james valley)
		(at hairtonic townsquare)
		(at frank townsquare)
		(at michael hut)
		(at fortexit fort)
		(at mansionexit mansion)
		(at candle mansion)
		(at jordan mansion)
		(at shopentrance townsquare)
		(at oscar bar)
		(at barentrance docks)
		(at barexit bar)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at mushroom townarch)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at hutentrance townarch)
		(at basemententrance bar)
		(at dorian townarch)
		(at mel storage)
		(at rubyring shop)
		(at ian fort)
		(at mirror townarch)
		(at dave townsquare)
		(at silver bank)
		(at bucket fort)
		(at mel basement)
		(at mel bar)
		(at hutexit hut)
		(at avery mansion)
		(at alli junkyard)
		(at roger mansion)
		(at karina townarch)
		(at basementexit basement)
		(at ash townarch)
		(at fortentrance valley)
		(at camille fort)
		(at mansionentrance cliff)
		(closed basemententrance)
		(closed shopentrance)
		(closed forgeentrance)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected townsquare valley)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(doorway junkyard docks)
		(doorway basement storage)
		(has arthur book)
		(has james humanskull)
		(has alli tastycupcake)
		(has mel basementbucket)
		(has jordan loveletter)
		(has dorian lovecontract)
		(has james coin)
		(has arthur bouquet)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto hutexit townarch)
		(leadsto bankexit townsquare)
		(leadsto fortexit valley)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item dorian bouquet)
		(wants-item jordan lovecontract)
		(wants-item james candle)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
			(and (has james coin) (has james humanskull) (has james candle) )
		)

	)

)
