(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina michael frank dave giovanna james jordan avery roger - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop valley cliff mansion - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit - entrance
	)
	(:init
		(at silver townsquare)
		(at karina townarch)
		(at shopexit shop)
		(at roger mansion)
		(at arthur cliff)
		(at rubyring shop)
		(at alli junkyard)
		(at mel bar)
		(at hutexit hut)
		(at mirror junkyard)
		(at ash townsquare)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at mel basement)
		(at avery mansion)
		(at basementexit basement)
		(at fortentrance valley)
		(at frank townsquare)
		(at basemententrance bar)
		(at mel storage)
		(at barentrance docks)
		(at coin bank)
		(at dorian townarch)
		(at dave townsquare)
		(at mushroom townsquare)
		(at james valley)
		(at michael hut)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at candle mansion)
		(at book townarch)
		(at jordan mansion)
		(at oscar bar)
		(at barexit bar)
		(at bouquet cliff)
		(at bankentrance townsquare)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at knightshield shop)
		(at mansionexit mansion)
		(closed basemententrance)
		(closed forgeentrance)
		(closed fortentrance)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected storage basement)
		(connected valley townsquare)
		(connected basement storage)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected townarch docks)
		(doorway townarch townsquare)
		(doorway valley townsquare)
		(doorway basement storage)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(has arthur loveletter)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has arthur rubyring)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(leadsto mansionexit cliff)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto bankexit townsquare)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur ash)
		(has giovanna hairtonic)
	  )
	)
)
