(open arthur barexit bar)
(move-through-entrance arthur bar barexit docks)
(pickup arthur mushroom docks)
(move-through-doorway arthur docks townarch)
(open arthur hutentrance townarch)
(move-through-entrance arthur townarch hutentrance hut)
(pickup arthur book hut)
(pickup arthur hairtonic hut)
(pickup arthur tastycupcake hut)
(move-through-entrance arthur hut hutexit townarch)
(drop arthur book townarch)
(open arthur forgeentrance townarch)
(move-through-entrance arthur townarch forgeentrance forge)
(pickup arthur rope forge)
(pickup arthur knightsword forge)
(move-through-entrance arthur forge forgeexit townarch)
(drop arthur rope townarch)
(pickup arthur book townarch)
(drop arthur knightsword townarch)
(drop arthur mushroom townarch)
(pickup arthur rope townarch)
(pickup arthur mushroom townarch)
(move-through-door arthur townarch towngate townsquare)
(open arthur shopentrance townsquare)
(move-through-entrance arthur townsquare shopentrance shop)
(give arthur hairtonic giovanna shop)
(pickup arthur knightshield shop)
(move-through-entrance arthur shop shopexit townsquare)
(drop arthur tastycupcake townsquare)
(move-through-doorway arthur townsquare valley)
(open arthur fortentrance valley)
(move-through-entrance arthur valley fortentrance fort)
(give arthur knightshield ian fort)
(pickup arthur bucket fort)
(move-through-entrance arthur fort fortexit valley)
(move-through-doorway arthur valley townsquare)
(move-through-door arthur townsquare towngate townarch)
(drop arthur book townarch)
(drop arthur bucket townarch )
(drop arthur rope townarch )
(pickup arthur rope townarch )
(pickup arthur book townarch )
(drop arthur mushroom townarch)
(pickup arthur mushroom townarch )
(drop arthur rope townarch )
(drop arthur book townarch )
(move-through-door arthur townarch towngate townsquare)
(pickup arthur tastycupcake townsquare)
(move-through-door arthur townsquare towngate townarch)
(move-through-doorway arthur townarch docks)
(move-through-doorway arthur docks townarch)
(pickup arthur knightsword townarch)
(move-through-door arthur townarch towngate townsquare)
(close arthur shopentrance townsquare)
(move-through-doorway arthur townsquare valley)
(move-through-entrance arthur valley fortentrance fort)
(give arthur knightsword ian fort)
(move-through-entrance arthur fort fortexit valley)
(move-through-doorway arthur valley townsquare)
(move-through-door arthur townsquare towngate townarch)
(move-through-doorway arthur townarch docks)
(move-through-doorway arthur docks junkyard)
(give arthur tastycupcake alli junkyard)
