(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina peter matthias michael frank dave james ian camille phillip jordan avery roger alli giovanna - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book bucket humanskull bouquet candle mirror ash knightshield rubyring coin silver - item
		 storage basement bar docks townarch forge hut townsquare valley fort cliff mansion junkyard shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance fortentrance fortexit mansionentrance mansionexit shopexit bankexit - entrance
	)
	(:init
		(at dorian townarch)
		(at james valley)
		(at fortentrance valley)
		(at dave townsquare)
		(at forgeexit forge)
		(at hutexit hut)
		(at fortexit fort)
		(at michael hut)
		(at tastycupcake hut)
		(at mansionexit mansion)
		(at humanskull cliff)
		(at hutentrance townarch)
		(at knightsword forge)
		(at mansionentrance cliff)
		(at roger mansion)
		(at giovanna shop)
		(at shopexit shop)
		(at karina townarch)
		(at mel bar)
		(at phillip fort)
		(at avery mansion)
		(at silver bank)
		(at alli junkyard)
		(at arthur bank)
		(at mel basement)
		(at coin bank)
		(at camille fort)
		(at basemententrance bar)
		(at ian fort)
		(at bankentrance townsquare)
		(at peter forge)
		(at barentrance docks)
		(at mirror junkyard)
		(at bucket fort)
		(at oscar bar)
		(at rope townarch)
		(at mel storage)
		(at candle mansion)
		(at mushroom townarch)
		(at book hut)
		(at frank townsquare)
		(at barexit bar)
		(at jordan mansion)
		(at tastycupcake townarch)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at basementexit basement)
		(at matthias forge)
		(closed basemententrance)
		(connected junkyard docks)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected basement storage)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare valley)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected townarch docks)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(has ian knightshield)
		(has dorian rubyring)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has dorian bouquet)
		(has ian knightsword)
		(has giovanna hairtonic)
		(has alli ash)
		(has mel basementbucket)
		(leadsto shopexit townsquare)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto basemententrance basement)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item james coin)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item alli tastycupcake)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has ian knightsword)
		(has ian knightshield)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has jordan lovecontract)
	  )
	)
)
