(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina peter matthias michael frank dave james ian camille phillip jordan avery roger alli giovanna - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book bucket humanskull bouquet candle mirror ash knightshield rubyring coin silver - item
		 storage basement bar docks townarch forge hut townsquare valley fort cliff mansion junkyard shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance fortentrance fortexit mansionentrance mansionexit shopexit bankexit - entrance
	)
	(:init
		(at fortexit fort)
		(at barentrance docks)
		(at mansionentrance cliff)
		(at hutentrance townarch)
		(at mansionexit mansion)
		(at michael hut)
		(at silver cliff)
		(at barexit bar)
		(at shopexit shop)
		(at arthur cliff)
		(at tastycupcake hut)
		(at dorian townarch)
		(at james valley)
		(at bucket townarch)
		(at mel basement)
		(at dave townsquare)
		(at avery mansion)
		(at knightsword forge)
		(at fortentrance valley)
		(at giovanna shop)
		(at mel bar)
		(at hutexit hut)
		(at karina townarch)
		(at rope townarch)
		(at alli junkyard)
		(at roger mansion)
		(at peter forge)
		(at camille fort)
		(at candle mansion)
		(at forgeexit forge)
		(at oscar bar)
		(at ian fort)
		(at basemententrance bar)
		(at mel storage)
		(at matthias forge)
		(at book townarch)
		(at phillip fort)
		(at jordan mansion)
		(at frank townsquare)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at basementexit basement)
		(at ash townarch)
		(at bankexit bank)
		(at forgeentrance townarch)
		(closed basemententrance)
		(connected townarch docks)
		(connected docks junkyard)
		(connected townsquare cliff)
		(connected basement storage)
		(connected docks townarch)
		(connected junkyard docks)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected valley townsquare)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(has ian knightshield)
		(has dorian bouquet)
		(has arthur mirror)
		(has jordan lovecontract)
		(has mel basementbucket)
		(has arthur mushroom)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has jordan loveletter)
		(has james coin)
		(has james humanskull)
		(has dorian rubyring)
		(has ian knightsword)
		(leadsto bankentrance bank)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto fortexit valley)
		(leadsto mansionentrance mansion)
		(leadsto bankexit townsquare)
		(leadsto hutexit townarch)
		(leadsto forgeexit townarch)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item james candle)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has ian knightsword)
		(has ian knightshield)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has jordan lovecontract)
		(has arthur ash)
		(has james humanskull)
		(has james candle)
	  )
	)
)
