(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina peter matthias michael frank dave - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book - item
		 storage basement bar docks townarch forge hut townsquare - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance - entrance
	)
	(:init
		(at matthias forge)
		(at mushroom townarch)
		(at tastycupcake townarch)
		(at mel storage)
		(at arthur townsquare)
		(at barentrance docks)
		(at frank townsquare)
		(at michael hut)
		(at mel bar)
		(at dave townsquare)
		(at dorian townarch)
		(at jordan mansion)
		(at karina townarch)
		(at mansionentrance cliff)
		(at forgeentrance townarch)
		(at knightsword townarch)
		(at hairtonic townarch)
		(at forgeexit forge)
		(at basemententrance bar)
		(at oscar bar)
		(at peter forge)
		(at book hut)
		(at basementexit basement)
		(at hutentrance townarch)
		(at bankentrance townsquare)
		(at rope townarch)
		(at mel basement)
		(at hutexit hut)
		(at shopentrance townsquare)
		(at barexit bar)
		(closed shopentrance)
		(closed bankentrance)
		(closed basemententrance)
		(connected townsquare townarch)
		(connected basement storage)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected storage basement)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected docks townarch)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(has arthur loveletter)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur shinykey)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(leadsto forgeexit townarch)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
	  )
	)
)
