(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina peter matthias michael frank dave james ian camille phillip jordan avery roger alli giovanna - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book bucket humanskull bouquet candle mirror ash knightshield rubyring - item
		 storage basement bar docks townarch forge hut townsquare valley fort cliff mansion junkyard shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance fortentrance fortexit mansionentrance mansionexit shopexit - entrance
	)
	(:init
		(at camille fort)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at peter forge)
		(at basementexit basement)
		(at karina townarch)
		(at shopexit shop)
		(at forgeentrance townarch)
		(at mel bar)
		(at hutexit hut)
		(at fortentrance valley)
		(at basemententrance bar)
		(at mel basement)
		(at dave townsquare)
		(at hairtonic townarch)
		(at roger mansion)
		(at humanskull cliff)
		(at james valley)
		(at dorian townarch)
		(at hutentrance townarch)
		(at michael hut)
		(at fortexit fort)
		(at knightsword forge)
		(at book hut)
		(at tastycupcake townarch)
		(at frank townsquare)
		(at alli junkyard)
		(at ian fort)
		(at bucket fort)
		(at avery mansion)
		(at knightsword townarch)
		(at mansionexit mansion)
		(at matthias forge)
		(at shopentrance townsquare)
		(at oscar bar)
		(at barexit bar)
		(at jordan mansion)
		(at phillip fort)
		(at arthur townsquare)
		(at rope townarch)
		(at candle mansion)
		(at mushroom townarch)
		(at mirror junkyard)
		(at bankentrance townsquare)
		(at tastycupcake hut)
		(at forgeexit forge)
		(at mel storage)
		(at knightshield shop)
		(at barentrance docks)
		(closed bankentrance)
		(closed basemententrance)
		(connected storage basement)
		(connected junkyard docks)
		(connected townsquare townarch)
		(connected townarch townsquare)
		(connected valley townsquare)
		(connected docks junkyard)
		(connected basement storage)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected townsquare valley)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(has arthur lovecontract)
		(has arthur shinykey)
		(has mel basementbucket)
		(has dorian rubyring)
		(has dorian bouquet)
		(has alli ash)
		(has jordan loveletter)
		(leadsto shopexit townsquare)
		(leadsto fortexit valley)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item ian knightsword)
		(wants-item arthur ash)
		(wants-item giovanna hairtonic)
		(wants-item alli tastycupcake)
		(wants-item james coin)
		(wants-item jordan lovecontract)
		(wants-item ian knightshield)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has ian knightsword)
		(has ian knightshield)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has jordan lovecontract)
	  )
	)
)
