(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop cliff mansion valley forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna jordan avery roger - character
	)
	(:init
		(at avery mansion)
		(at bankentrance townsquare)
		(at coin townsquare)
		(at mel storage)
		(at oscar bar)
		(at basemententrance bar)
		(at dave townsquare)
		(at candle mansion)
		(at basementexit basement)
		(at book townarch)
		(at hutentrance townarch)
		(at jordan mansion)
		(at bouquet cliff)
		(at michael hut)
		(at mushroom townarch)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at frank townsquare)
		(at shopexit shop)
		(at ash junkyard)
		(at knightshield townsquare)
		(at mirror townarch)
		(at mansionentrance cliff)
		(at mansionexit mansion)
		(at barexit bar)
		(at humanskull cliff)
		(at rubyring shop)
		(at barentrance docks)
		(at dorian townarch)
		(at karina townarch)
		(at arthur townarch)
		(at alli junkyard)
		(at roger mansion)
		(at mel basement)
		(at hutexit hut)
		(at giovanna shop)
		(at mel bar)
		(at silver townsquare)
		(closed forgeentrance)
		(closed basemententrance)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townarch docks)
		(connected docks junkyard)
		(connected basement storage)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected cliff townsquare)
		(doorway townsquare cliff)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(has dorian lovecontract)
		(has arthur rubyring)
		(has jordan loveletter)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto bankexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item dorian bouquet)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
