(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch hut cliff mansion townsquare forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit mansionentrance bankentrance - entrance
		 arthur mel oscar alli dorian karina michael jordan - character
	)
	(:init
		(at mansionentrance cliff)
		(at barexit bar)
		(at arthur hut)
		(at basementexit basement)
		(at oscar bar)
		(at basemententrance bar)
		(at karina townarch)
		(at dorian townarch)
		(at alli junkyard)
		(at hutexit hut)
		(at hutentrance townarch)
		(at michael hut)
		(at mel basement)
		(at mel bar)
		(at barentrance docks)
		(at mel storage)
		(at jordan mansion)
		(at forgeentrance townarch)
		(closed forgeentrance)
		(closed basemententrance)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected basement storage)
		(connected storage basement)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected docks junkyard)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(has arthur hairtonic)
		(has arthur mushroom)
		(has arthur mirror)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has alli ash)
		(has mel basementbucket)
		(has arthur shinykey)
		(has arthur tastycupcake)
		(has arthur book)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item alli tastycupcake)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur tastycupcake)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
