(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch hut cliff mansion townsquare forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit mansionentrance bankentrance - entrance
		 arthur mel oscar alli dorian karina michael jordan - character
	)
	(:init
		(at mansionentrance cliff)
		(at mushroom townarch)
		(at oscar bar)
		(at dorian townarch)
		(at hutentrance townarch)
		(at mel storage)
		(at barexit bar)
		(at arthur townarch)
		(at hutexit hut)
		(at mel bar)
		(at forgeentrance townarch)
		(at shinykey townarch)
		(at alli junkyard)
		(at jordan mansion)
		(at michael hut)
		(at tastycupcake townarch)
		(at karina townarch)
		(at basementexit basement)
		(at basemententrance bar)
		(at mel basement)
		(at barentrance docks)
		(at mirror townarch)
		(closed forgeentrance)
		(closed basemententrance)
		(connected junkyard docks)
		(connected townsquare cliff)
		(connected basement storage)
		(connected storage basement)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected docks junkyard)
		(doorway townarch townsquare)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway junkyard docks)
		(has arthur book)
		(has alli ash)
		(has arthur loveletter)
		(has arthur hairtonic)
		(has dorian lovecontract)
		(has mel basementbucket)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item alli tastycupcake)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur book)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
