(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop cliff mansion valley forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna jordan avery roger - character
	)
	(:init
		(at mansionexit mansion)
		(at arthur townsquare)
		(at michael hut)
		(at bankentrance townsquare)
		(at basementexit basement)
		(at barentrance docks)
		(at oscar bar)
		(at basemententrance bar)
		(at coin townsquare)
		(at dave townsquare)
		(at mushroom townarch)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at book townarch)
		(at bouquet cliff)
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at candle mansion)
		(at jordan mansion)
		(at frank townsquare)
		(at silver townsquare)
		(at mirror townarch)
		(at hutexit hut)
		(at rubyring shop)
		(at mel bar)
		(at barexit bar)
		(at humanskull cliff)
		(at mel basement)
		(at avery mansion)
		(at knightshield townsquare)
		(at dorian townarch)
		(at mel storage)
		(at mansionentrance cliff)
		(at shopexit shop)
		(at karina townarch)
		(at alli junkyard)
		(at ash junkyard)
		(at roger mansion)
		(at giovanna shop)
		(closed basemententrance)
		(closed forgeentrance)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townarch docks)
		(connected basement storage)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected docks junkyard)
		(doorway storage basement)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway townsquare townarch)
		(has alli tastycupcake)
		(has arthur rubyring)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto bankexit townsquare)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
