(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch hut townsquare mansion cliff valley shop forge bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance mansionentrance - entrance
		 arthur mel oscar alli dorian karina michael frank dave jordan - character
	)
	(:init
		(at basemententrance bar)
		(at alli junkyard)
		(at book townarch)
		(at hairtonic townarch)
		(at hutexit hut)
		(at basementexit basement)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at mansionentrance cliff)
		(at shopentrance townsquare)
		(at dorian townarch)
		(at karina townarch)
		(at barentrance docks)
		(at barexit bar)
		(at mel storage)
		(at oscar bar)
		(at mel bar)
		(at arthur townsquare)
		(at frank townsquare)
		(at ash junkyard)
		(at hutentrance townarch)
		(at mel basement)
		(at mushroom townarch)
		(at mirror townarch)
		(at dave townsquare)
		(at jordan mansion)
		(at michael hut)
		(closed shopentrance)
		(closed basemententrance)
		(closed bankentrance)
		(closed forgeentrance)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected basement storage)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare valley)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway docks junkyard)
		(has arthur shinykey)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has arthur loveletter)
		(has alli tastycupcake)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
