(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch hut mansion cliff townsquare forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit mansionentrance bankentrance - entrance
		 arthur mel oscar alli dorian karina michael jordan - character
	)
	(:init
		(at jordan mansion)
		(at arthur townarch)
		(at barexit bar)
		(at shinykey townarch)
		(at dorian townarch)
		(at basemententrance bar)
		(at mel storage)
		(at karina townarch)
		(at mel bar)
		(at forgeentrance townarch)
		(at oscar bar)
		(at alli junkyard)
		(at michael hut)
		(at hutentrance townarch)
		(at basementexit basement)
		(at hutexit hut)
		(at mansionentrance cliff)
		(at tastycupcake townarch)
		(at barentrance docks)
		(at mel basement)
		(closed basemententrance)
		(closed forgeentrance)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected storage basement)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townarch docks)
		(connected docks townarch)
		(connected townsquare cliff)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway storage basement)
		(has mel basementbucket)
		(has arthur mirror)
		(has arthur book)
		(has alli ash)
		(has dorian lovecontract)
		(has arthur mushroom)
		(has arthur loveletter)
		(has arthur hairtonic)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item alli tastycupcake)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur mirror)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
