(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter coin silver knightshield rubyring tastycupcake hairtonic - item
		 storage basement bar docks junkyard townarch townsquare bank shop cliff hut mansion valley forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit shopexit mansionentrance hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave giovanna jordan - character
	)
	(:init
		(at arthur shop)
		(at barexit bar)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at oscar bar)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at hutentrance townarch)
		(at mirror junkyard)
		(at dorian townarch)
		(at rubyring shop)
		(at alli junkyard)
		(at basemententrance bar)
		(at jordan mansion)
		(at dave townsquare)
		(at mel storage)
		(at mel basement)
		(at mansionentrance cliff)
		(at frank townsquare)
		(at barentrance docks)
		(at shopexit shop)
		(at karina townarch)
		(at mel bar)
		(at hutexit hut)
		(at basementexit basement)
		(at giovanna shop)
		(at tastycupcake hut)
		(closed forgeentrance)
		(closed hutentrance)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected basement storage)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(has alli ash)
		(has arthur knightshield)
		(has arthur silver)
		(has arthur loveletter)
		(has arthur coin)
		(has arthur mushroom)
		(has dorian lovecontract)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto shopexit townsquare)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto barentrance bar)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item alli tastycupcake)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item giovanna hairtonic)
		(wants-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur coin)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
