(move-through-doorway arthur valley townsquare)
(move-through-doorway arthur townsquare cliff)
(move-through-entrance arthur cliff mansionentrance mansion)
(give arthur loveletter jordan mansion)
(drop arthur coin mansion)
(pickup arthur coin mansion)
(move-through-entrance arthur mansion mansionexit cliff)
(move-through-doorway arthur cliff townsquare)
(move-through-entrance arthur townsquare shopentrance shop)
(move-through-entrance arthur shop shopexit townsquare )
(move-through-doorway arthur townsquare valley )
(move-through-doorway arthur valley townsquare )
(move-through-entrance arthur townsquare bankentrance bank )
(drop arthur coin bank)
(pickup arthur coin bank )
(move-through-entrance arthur bank bankexit townsquare )
(move-through-doorway arthur townsquare valley )
