(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop cliff mansion valley forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit mansionentrance - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna jordan - character
	)
	(:init
		(at mel storage)
		(at michael hut)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at barentrance docks)
		(at shopentrance townsquare)
		(at oscar bar)
		(at knightshield townsquare)
		(at bankexit bank)
		(at jordan mansion)
		(at bouquet cliff)
		(at book townarch)
		(at mushroom townarch)
		(at bankentrance townsquare)
		(at forgeentrance townarch)
		(at barexit bar)
		(at dorian townarch)
		(at mirror townarch)
		(at basemententrance bar)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at arthur cliff)
		(at alli junkyard)
		(at silver townsquare)
		(at dave townsquare)
		(at hutexit hut)
		(at karina townarch)
		(at mel bar)
		(at mel basement)
		(at ash junkyard)
		(at basementexit basement)
		(at frank townsquare)
		(at coin townsquare)
		(at rubyring townsquare)
		(at giovanna shop)
		(closed forgeentrance)
		(closed basemententrance)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected junkyard docks)
		(doorway townarch docks)
		(doorway junkyard docks)
		(doorway townsquare townarch)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway townsquare cliff)
		(has mel basementbucket)
		(has arthur loveletter)
		(has giovanna hairtonic)
		(has alli tastycupcake)
		(has dorian lovecontract)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(leadsto bankexit townsquare)
		(leadsto shopexit townsquare)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
