(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter coin silver bucket humanskull bouquet knightshield knightsword ash - item
		 storage basement bar docks townarch townsquare bank valley fort cliff shop forge mansion junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit fortentrance fortexit mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip peter jordan - character
	)
	(:init
		(at bankentrance townsquare)
		(at oscar bar)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at barexit bar)
		(at forgeentrance townarch)
		(at jordan mansion)
		(at frank townsquare)
		(at fortentrance valley)
		(at fortexit fort)
		(at knightsword forge)
		(at hutentrance townarch)
		(at basementexit basement)
		(at basemententrance bar)
		(at mel storage)
		(at bouquet cliff)
		(at peter forge)
		(at camille fort)
		(at james valley)
		(at ian fort)
		(at mel bar)
		(at karina townarch)
		(at barentrance docks)
		(at knightshield shop)
		(at mel basement)
		(at phillip fort)
		(at dorian townarch)
		(at arthur cliff)
		(at mansionentrance cliff)
		(at dave townsquare)
		(closed shopentrance)
		(closed mansionentrance)
		(closed forgeentrance)
		(closed basemententrance)
		(closed hutentrance)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected valley townsquare)
		(connected basement storage)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected storage basement)
		(connected townsquare valley)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway valley townsquare)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway docks townarch)
		(has james coin)
		(has arthur bucket)
		(has dorian lovecontract)
		(has arthur silver)
		(has arthur loveletter)
		(has arthur humanskull)
		(has mel basementbucket)
		(has arthur mushroom)
		(leadsto fortentrance fort)
		(leadsto hutentrance hut)
		(leadsto bankexit townsquare)
		(leadsto basemententrance basement)
		(leadsto shopentrance shop)
		(leadsto barexit docks)
		(leadsto fortexit valley)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item james humanskull)
		(wants-item ian knightsword)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item ian knightshield)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur humanskull)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(and (has james coin) (has james humanskull) )
		)

	)

)
