(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter coin silver bucket knightshield ash humanskull - item
		 storage basement bar docks townarch townsquare bank valley fort shop cliff mansion junkyard forge hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit fortentrance fortexit mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip jordan - character
	)
	(:init
		(at mel bar)
		(at barexit bar)
		(at jordan mansion)
		(at basemententrance bar)
		(at oscar bar)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at mel storage)
		(at fortexit fort)
		(at mansionentrance cliff)
		(at frank townsquare)
		(at phillip fort)
		(at bankentrance townsquare)
		(at dorian townarch)
		(at hutentrance townarch)
		(at arthur fort)
		(at fortentrance valley)
		(at barentrance docks)
		(at knightshield shop)
		(at dave townsquare)
		(at camille fort)
		(at karina townarch)
		(at james valley)
		(at basementexit basement)
		(at mel basement)
		(at ian fort)
		(closed forgeentrance)
		(closed basemententrance)
		(closed shopentrance)
		(closed hutentrance)
		(connected townsquare cliff)
		(connected valley townsquare)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected storage basement)
		(connected basement storage)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(has arthur bucket)
		(has arthur loveletter)
		(has arthur silver)
		(has arthur mushroom)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has james coin)
		(leadsto shopentrance shop)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto fortexit valley)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item james humanskull)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has jordan loveletter) 
			(and (has james coin) (has james humanskull) )
		)

	)

)
