(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter coin silver bucket humanskull bouquet candle knightshield rubyring tastycupcake hairtonic book knightsword rope ash - item
		 storage basement bar docks townarch townsquare bank valley fort cliff mansion shop hut forge junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit fortentrance fortexit mansionentrance mansionexit shopexit hutexit forgeexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip jordan avery roger giovanna michael peter matthias - character
	)
	(:init
		(at dorian townarch)
		(at bankentrance townsquare)
		(at arthur valley)
		(at peter forge)
		(at fortexit fort)
		(at oscar bar)
		(at hutentrance townarch)
		(at candle mansion)
		(at james valley)
		(at michael hut)
		(at ian fort)
		(at matthias forge)
		(at book hut)
		(at jordan mansion)
		(at phillip fort)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at bankexit bank)
		(at bouquet cliff)
		(at bucket townsquare)
		(at dave townsquare)
		(at mushroom townsquare)
		(at karina townarch)
		(at mel storage)
		(at mansionexit mansion)
		(at basemententrance bar)
		(at barentrance docks)
		(at forgeexit forge)
		(at barexit bar)
		(at avery mansion)
		(at mel bar)
		(at frank townsquare)
		(at tastycupcake hut)
		(at rope forge)
		(at basementexit basement)
		(at mel basement)
		(at camille fort)
		(at giovanna shop)
		(at shopexit shop)
		(at roger mansion)
		(at fortentrance valley)
		(at hutexit hut)
		(at mansionentrance cliff)
		(closed basemententrance)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected storage basement)
		(connected docks junkyard)
		(connected basement storage)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected cliff townsquare)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway townarch townsquare)
		(has arthur knightsword)
		(has jordan loveletter)
		(has dorian rubyring)
		(has mel basementbucket)
		(has arthur silver)
		(has james humanskull)
		(has jordan lovecontract)
		(has james coin)
		(has arthur hairtonic)
		(has arthur knightshield)
		(leadsto hutexit townarch)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto shopexit townsquare)
		(leadsto basemententrance basement)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item ian knightsword)
		(wants-item dorian bouquet)
		(wants-item ian knightshield)
		(wants-item giovanna hairtonic)
		(wants-item james candle)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur knightshield)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

		)
	)

)
