(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter coin silver bucket humanskull bouquet candle knightshield rubyring knightsword hairtonic ash - item
		 storage basement bar docks townarch townsquare bank valley fort cliff mansion shop forge junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit fortentrance fortexit mansionentrance mansionexit shopexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip jordan avery roger giovanna peter - character
	)
	(:init
		(at giovanna shop)
		(at frank townsquare)
		(at hutentrance townarch)
		(at phillip fort)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at mel storage)
		(at roger mansion)
		(at bucket townsquare)
		(at candle mansion)
		(at bankentrance townsquare)
		(at bouquet cliff)
		(at oscar bar)
		(at jordan mansion)
		(at barentrance docks)
		(at barexit bar)
		(at arthur townsquare)
		(at fortexit fort)
		(at avery mansion)
		(at james valley)
		(at mel basement)
		(at basementexit basement)
		(at fortentrance valley)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at dave townsquare)
		(at mansionexit mansion)
		(at basemententrance bar)
		(at camille fort)
		(at mel bar)
		(at ian fort)
		(at karina townarch)
		(at knightshield townsquare)
		(at mushroom townsquare)
		(at knightsword forge)
		(at dorian townarch)
		(at peter forge)
		(closed hutentrance)
		(closed basemententrance)
		(closed forgeentrance)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare valley)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected basement storage)
		(connected valley townsquare)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected townarch docks)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(has mel basementbucket)
		(has arthur lovecontract)
		(has arthur silver)
		(has jordan loveletter)
		(has james coin)
		(has james humanskull)
		(has dorian rubyring)
		(leadsto basementexit bar)
		(leadsto bankexit townsquare)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto shopexit townsquare)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item ian knightshield)
		(wants-item arthur ash)
		(wants-item dorian bouquet)
		(wants-item jordan lovecontract)
		(wants-item ian knightsword)
		(wants-item arthur shinykey)
		(wants-item james candle)
		(wants-item giovanna hairtonic)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur silver)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

		)
	)

)
