(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring humanskull bouquet candle coin silver knightsword ash - item
		 storage basement bar docks townarch townsquare valley fort shop cliff mansion bank forge junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit mansionentrance mansionexit bankexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna jordan avery roger peter - character
	)
	(:init
		(at mansionentrance cliff)
		(at rubyring shop)
		(at fortexit fort)
		(at roger mansion)
		(at hutentrance townarch)
		(at phillip fort)
		(at knightsword forge)
		(at bouquet mansion)
		(at avery mansion)
		(at mel storage)
		(at jordan mansion)
		(at shopentrance townsquare)
		(at arthur townsquare)
		(at oscar bar)
		(at bankexit bank)
		(at bankentrance townsquare)
		(at basemententrance bar)
		(at barexit bar)
		(at dave townsquare)
		(at barentrance docks)
		(at dorian townarch)
		(at mushroom cliff)
		(at frank townsquare)
		(at shopexit shop)
		(at fortentrance valley)
		(at mel basement)
		(at mansionexit mansion)
		(at peter forge)
		(at giovanna shop)
		(at camille fort)
		(at mel bar)
		(at ian fort)
		(at basementexit basement)
		(at karina townarch)
		(at forgeentrance townarch)
		(at silver bank)
		(at humanskull cliff)
		(at james valley)
		(closed forgeentrance)
		(closed hutentrance)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch docks)
		(connected valley townsquare)
		(connected cliff townsquare)
		(connected storage basement)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway storage basement)
		(doorway basement storage)
		(has arthur bucket)
		(has arthur coin)
		(has jordan loveletter)
		(has arthur rubyring)
		(has ian knightshield)
		(has mel basementbucket)
		(has arthur candle)
		(has dorian lovecontract)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto bankexit townsquare)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto fortexit valley)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian bouquet)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(wants-item arthur ash)
		(wants-item ian knightsword)
		(wants-item james coin)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur candle)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
