(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring humanskull bouquet candle coin silver knightsword rope ash - item
		 storage basement bar docks townarch townsquare valley fort shop cliff mansion bank forge junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit mansionentrance mansionexit bankexit forgeexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna jordan avery roger peter matthias - character
	)
	(:init
		(at fortentrance valley)
		(at forgeexit forge)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at fortexit fort)
		(at frank townsquare)
		(at hutentrance townarch)
		(at james valley)
		(at humanskull cliff)
		(at silver bank)
		(at dave townsquare)
		(at barexit bar)
		(at bouquet mansion)
		(at rope forge)
		(at matthias forge)
		(at shopentrance townsquare)
		(at oscar bar)
		(at dorian townarch)
		(at candle forge)
		(at jordan mansion)
		(at mel basement)
		(at bankentrance townsquare)
		(at basemententrance bar)
		(at mel storage)
		(at phillip fort)
		(at mel bar)
		(at ian fort)
		(at basementexit basement)
		(at arthur valley)
		(at barentrance docks)
		(at roger mansion)
		(at mansionexit mansion)
		(at bucket valley)
		(at karina townarch)
		(at camille fort)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at mushroom cliff)
		(at peter forge)
		(at rubyring shop)
		(at avery mansion)
		(closed hutentrance)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected docks townarch)
		(connected storage basement)
		(connected townsquare cliff)
		(connected basement storage)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected townarch docks)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(has james coin)
		(has ian knightshield)
		(has dorian rubyring)
		(has ian knightsword)
		(has jordan loveletter)
		(has mel basementbucket)
		(has jordan lovecontract)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto fortentrance fort)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto fortexit valley)
		(leadsto shopexit townsquare)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item james humanskull)
		(wants-item dorian bouquet)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(and (has jordan loveletter) (has jordan lovecontract) )
			(and (has james coin) (has james humanskull) )
		)

	)

)
