(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter ash - item
		 storage basement bar docks townarch townsquare junkyard forge hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance bankentrance - entrance
		 arthur mel oscar dorian karina - character
	)
	(:init
		(at basemententrance bar)
		(at dorian townarch)
		(at shinykey bar)
		(at barexit bar)
		(at arthur townarch)
		(at basementexit basement)
		(at mushroom docks)
		(at forgeentrance townarch)
		(at oscar bar)
		(at mel storage)
		(at mel bar)
		(at mel basement)
		(at hutentrance townarch)
		(at barentrance docks)
		(at karina townarch)
		(closed hutentrance)
		(closed basemententrance)
		(closed forgeentrance)
		(connected townarch townsquare)
		(connected basement storage)
		(connected docks townarch)
		(connected storage basement)
		(connected townarch docks)
		(connected docks junkyard)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway basement storage)
		(has dorian lovecontract)
		(has dorian loveletter)
		(has mel basementbucket)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item arthur loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		(game-has-been-won)
	)
)
