(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch hut townsquare forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit bankentrance - entrance
		 arthur mel oscar alli dorian karina michael - character
	)
	(:init
		(at barentrance docks)
		(at dorian townarch)
		(at hutexit hut)
		(at arthur docks)
		(at forgeentrance townarch)
		(at alli junkyard)
		(at oscar bar)
		(at mel storage)
		(at basemententrance bar)
		(at barexit bar)
		(at michael hut)
		(at mel bar)
		(at basementexit basement)
		(at book hut)
		(at karina townarch)
		(at hutentrance townarch)
		(at mel basement)
		(at mirror junkyard)
		(closed forgeentrance)
		(connected basement storage)
		(connected townarch townsquare)
		(connected storage basement)
		(connected docks junkyard)
		(connected townarch docks)
		(connected junkyard docks)
		(connected docks townarch)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway docks junkyard)
		(has arthur shinykey)
		(has dorian lovecontract)
		(has arthur tastycupcake)
		(has mel basementbucket)
		(has alli ash)
		(has dorian loveletter)
		(has arthur hairtonic)
		(has arthur mushroom)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur loveletter)
		(wants-item alli tastycupcake)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur tastycupcake)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		
			(has alli tastycupcake) 
		

	)

)
