(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina michael peter matthias frank dave james - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope - item
		 storage basement bar docks townarch hut forge townsquare valley - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance - entrance
	)
	(:init
		(at jordan mansion)
		(at dave townsquare)
		(at barexit bar)
		(at dorian townarch)
		(at matthias forge)
		(at hutentrance townarch)
		(at james valley)
		(at karina townarch)
		(at hutexit hut)
		(at fortentrance valley)
		(at mel bar)
		(at mel storage)
		(at mansionentrance cliff)
		(at mel basement)
		(at basemententrance bar)
		(at peter forge)
		(at basementexit basement)
		(at tastycupcake forge)
		(at oscar bar)
		(at forgeexit forge)
		(at barentrance docks)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at frank townsquare)
		(at michael hut)
		(closed shopentrance)
		(closed basemententrance)
		(closed fortentrance)
		(closed bankentrance)
		(connected townarch docks)
		(connected basement storage)
		(connected storage basement)
		(connected townsquare valley)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected valley townsquare)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway valley townsquare)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has arthur knightsword)
		(has arthur hairtonic)
		(has arthur shinykey)
		(has arthur rope)
		(has arthur loveletter)
		(has arthur mushroom)
		(has arthur book)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto forgeexit townarch)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto fortentrance fort)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur knightsword)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
	  )
	)
)
