(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop cliff mansion valley forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna jordan avery roger - character
	)
	(:init
		(at mirror townarch)
		(at mushroom townarch)
		(at basemententrance bar)
		(at bankentrance townsquare)
		(at michael hut)
		(at coin townsquare)
		(at arthur townsquare)
		(at frank townsquare)
		(at candle mansion)
		(at humanskull cliff)
		(at oscar bar)
		(at bouquet cliff)
		(at book townarch)
		(at forgeentrance townarch)
		(at ash junkyard)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at hutentrance townarch)
		(at jordan mansion)
		(at basementexit basement)
		(at silver townsquare)
		(at avery mansion)
		(at mansionexit mansion)
		(at mel bar)
		(at hutexit hut)
		(at dorian townarch)
		(at barexit bar)
		(at mel basement)
		(at barentrance docks)
		(at knightshield townsquare)
		(at dave townsquare)
		(at mel storage)
		(at mansionentrance cliff)
		(at shopexit shop)
		(at karina townarch)
		(at alli junkyard)
		(at rubyring shop)
		(at roger mansion)
		(at giovanna shop)
		(closed basemententrance)
		(closed forgeentrance)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected junkyard docks)
		(connected basement storage)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway townsquare valley)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway townsquare cliff)
		(has giovanna hairtonic)
		(has dorian lovecontract)
		(has arthur rubyring)
		(has alli tastycupcake)
		(has mel basementbucket)
		(has arthur loveletter)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(leadsto bankexit townsquare)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur rubyring)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
