(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop cliff mansion valley forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit mansionentrance - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna jordan - character
	)
	(:init
		(at giovanna shop)
		(at jordan mansion)
		(at bankentrance townsquare)
		(at mushroom townarch)
		(at oscar bar)
		(at arthur townsquare)
		(at shopentrance townsquare)
		(at book townarch)
		(at forgeentrance townarch)
		(at bankexit bank)
		(at barexit bar)
		(at dorian townarch)
		(at hutentrance townarch)
		(at alli junkyard)
		(at mirror townarch)
		(at dave townsquare)
		(at ash junkyard)
		(at mel basement)
		(at mansionentrance cliff)
		(at mel storage)
		(at shopexit shop)
		(at basemententrance bar)
		(at barentrance docks)
		(at hutexit hut)
		(at karina townarch)
		(at mel bar)
		(at silver townsquare)
		(at frank townsquare)
		(at michael hut)
		(at basementexit basement)
		(at hairtonic townarch)
		(closed basemententrance)
		(closed forgeentrance)
		(connected basement storage)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected docks townarch)
		(connected storage basement)
		(connected junkyard docks)
		(connected cliff townsquare)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway basement storage)
		(has arthur rubyring)
		(has arthur loveletter)
		(has arthur coin)
		(has dorian lovecontract)
		(has arthur knightshield)
		(has alli tastycupcake)
		(has mel basementbucket)
		(leadsto hutentrance hut)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto shopentrance shop)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item giovanna hairtonic)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur rubyring)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
