(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch hut cliff mansion townsquare forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit mansionentrance bankentrance - entrance
		 arthur mel oscar alli dorian karina michael jordan - character
	)
	(:init
		(at mel storage)
		(at barexit bar)
		(at shinykey townarch)
		(at book townarch)
		(at mel basement)
		(at hutexit hut)
		(at mushroom townarch)
		(at hutentrance townarch)
		(at basementexit basement)
		(at basemententrance bar)
		(at alli junkyard)
		(at dorian townarch)
		(at arthur junkyard)
		(at forgeentrance townarch)
		(at mansionentrance cliff)
		(at oscar bar)
		(at hairtonic townarch)
		(at jordan mansion)
		(at michael hut)
		(at loveletter townarch)
		(at barentrance docks)
		(at mirror townarch)
		(at karina townarch)
		(at mel bar)
		(closed basemententrance)
		(closed forgeentrance)
		(connected basement storage)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected storage basement)
		(connected docks junkyard)
		(connected townarch docks)
		(connected docks townarch)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway storage basement)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has alli tastycupcake)
		(has alli ash)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
