(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle knightshield rubyring bucket mirror ash - item
		 storage basement bar docks townarch hut forge townsquare valley cliff mansion shop fort junkyard bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit fortexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave james jordan avery roger giovanna ian camille phillip alli - character
	)
	(:init
		(at fortentrance valley)
		(at ian fort)
		(at mushroom townarch)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at candle cliff)
		(at forgeexit forge)
		(at oscar bar)
		(at frank townsquare)
		(at fortexit fort)
		(at tastycupcake hut)
		(at michael hut)
		(at jordan mansion)
		(at humanskull cliff)
		(at dorian townarch)
		(at rubyring cliff)
		(at james valley)
		(at hutentrance townarch)
		(at matthias forge)
		(at mirror junkyard)
		(at phillip fort)
		(at barexit bar)
		(at alli junkyard)
		(at bankentrance townsquare)
		(at book cliff)
		(at basementexit basement)
		(at mansionexit mansion)
		(at mel bar)
		(at hutexit hut)
		(at peter forge)
		(at barentrance docks)
		(at arthur mansion)
		(at roger mansion)
		(at avery mansion)
		(at dave townsquare)
		(at hairtonic cliff)
		(at karina townarch)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at bucket cliff)
		(at shopexit shop)
		(at basemententrance bar)
		(at mel basement)
		(at camille fort)
		(at knightshield cliff)
		(at mel storage)
		(closed bankentrance)
		(closed basemententrance)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected townsquare valley)
		(connected storage basement)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected basement storage)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(doorway junkyard docks)
		(doorway townarch townsquare)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(has arthur rope)
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur ash)
		(has arthur shinykey)
		(has arthur knightsword)
		(has dorian bouquet)
		(has mel basementbucket)
		(has jordan lovecontract)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto fortentrance fort)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto fortexit valley)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
