(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle rubyring ash - item
		 storage basement bar docks townarch hut forge townsquare valley cliff mansion shop junkyard fort bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave james jordan avery roger - character
	)
	(:init
		(at karina townarch)
		(at avery mansion)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at james valley)
		(at forgeexit forge)
		(at bankentrance townsquare)
		(at bouquet cliff)
		(at matthias forge)
		(at jordan mansion)
		(at barexit bar)
		(at candle cliff)
		(at forgeentrance townarch)
		(at oscar bar)
		(at shopentrance townsquare)
		(at hairtonic cliff)
		(at dorian townarch)
		(at michael hut)
		(at arthur cliff)
		(at basemententrance bar)
		(at mansionentrance cliff)
		(at book cliff)
		(at rubyring shop)
		(at roger mansion)
		(at dave townsquare)
		(at mushroom cliff)
		(at fortentrance valley)
		(at mansionexit mansion)
		(at mel storage)
		(at mel basement)
		(at mel bar)
		(at hutexit hut)
		(at peter forge)
		(at basementexit basement)
		(at frank townsquare)
		(at tastycupcake forge)
		(at barentrance docks)
		(closed fortentrance)
		(closed basemententrance)
		(closed shopentrance)
		(closed bankentrance)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected valley townsquare)
		(connected storage basement)
		(connected cliff townsquare)
		(connected townsquare townarch)
		(connected basement storage)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected townsquare valley)
		(connected docks junkyard)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(has dorian lovecontract)
		(has arthur rope)
		(has arthur shinykey)
		(has arthur loveletter)
		(has mel basementbucket)
		(has arthur knightsword)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(leadsto mansionexit cliff)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto bankentrance bank)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item jordan lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
