(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet ash - item
		 storage basement bar docks townarch hut forge townsquare valley cliff mansion junkyard fort shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave james jordan - character
	)
	(:init
		(at mansionentrance cliff)
		(at bouquet cliff)
		(at oscar bar)
		(at forgeentrance townarch)
		(at jordan mansion)
		(at barexit bar)
		(at shopentrance townsquare)
		(at matthias forge)
		(at hutentrance townarch)
		(at michael hut)
		(at frank townsquare)
		(at james valley)
		(at humanskull cliff)
		(at basemententrance bar)
		(at tastycupcake forge)
		(at dorian townarch)
		(at basementexit basement)
		(at book cliff)
		(at mushroom cliff)
		(at forgeexit forge)
		(at bankentrance townsquare)
		(at mel storage)
		(at fortentrance valley)
		(at karina townarch)
		(at arthur cliff)
		(at mel basement)
		(at mel bar)
		(at hutexit hut)
		(at dave townsquare)
		(at peter forge)
		(at barentrance docks)
		(closed basemententrance)
		(closed bankentrance)
		(closed shopentrance)
		(closed mansionentrance)
		(closed fortentrance)
		(connected docks junkyard)
		(connected storage basement)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected townsquare townarch)
		(connected basement storage)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected townarch docks)
		(connected cliff townsquare)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway valley townsquare)
		(has arthur rope)
		(has dorian lovecontract)
		(has arthur shinykey)
		(has arthur loveletter)
		(has arthur hairtonic)
		(has mel basementbucket)
		(has arthur knightsword)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
