(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver bucket knightshield rubyring humanskull bouquet candle ash - item
		 storage basement bar docks townarch forge hut townsquare bank valley fort shop cliff mansion junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit fortentrance fortexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave james ian camille phillip giovanna jordan avery roger - character
	)
	(:init
		(at phillip fort)
		(at forgeentrance townarch)
		(at michael hut)
		(at mushroom townarch)
		(at rope townarch)
		(at basemententrance bar)
		(at candle mansion)
		(at hutentrance townarch)
		(at knightsword forge)
		(at fortexit fort)
		(at jordan mansion)
		(at bouquet cliff)
		(at james valley)
		(at frank townsquare)
		(at barexit bar)
		(at peter forge)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at bucket fort)
		(at oscar bar)
		(at matthias forge)
		(at book townarch)
		(at humanskull cliff)
		(at forgeexit forge)
		(at bankentrance townsquare)
		(at arthur mansion)
		(at avery mansion)
		(at fortentrance valley)
		(at camille fort)
		(at mel bar)
		(at hutexit hut)
		(at tastycupcake townarch)
		(at barentrance docks)
		(at mel storage)
		(at dorian townarch)
		(at coin townsquare)
		(at dave townsquare)
		(at mansionexit mansion)
		(at roger mansion)
		(at basementexit basement)
		(at mansionentrance cliff)
		(at silver townsquare)
		(at karina townarch)
		(at shopexit shop)
		(at ian fort)
		(at mel basement)
		(at rubyring shop)
		(at giovanna shop)
		(at rubyring townsquare)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected storage basement)
		(connected basement storage)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway townsquare cliff)
		(has dorian lovecontract)
		(has ian knightsword)
		(has giovanna hairtonic)
		(has ian knightshield)
		(has jordan loveletter)
		(has mel basementbucket)
		(leadsto fortentrance fort)
		(leadsto mansionentrance mansion)
		(leadsto mansionexit cliff)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto bankexit townsquare)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto forgeexit townarch)
		(leadsto bankentrance bank)
		(leadsto fortexit valley)
		(leadsto shopexit townsquare)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item james coin)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) 
			)

		)
	)

)
