(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver ash - item
		 storage basement bar docks townarch forge hut townsquare bank mansion cliff valley junkyard shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit mansionentrance - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave jordan - character
	)
	(:init
		(at arthur townsquare)
		(at knightsword townarch)
		(at michael hut)
		(at mushroom townarch)
		(at hairtonic townarch)
		(at forgeexit forge)
		(at barexit bar)
		(at basemententrance bar)
		(at mel basement)
		(at dave townsquare)
		(at book townarch)
		(at mel storage)
		(at dorian townarch)
		(at shopentrance townsquare)
		(at rope townarch)
		(at karina townarch)
		(at bankentrance townsquare)
		(at matthias forge)
		(at peter forge)
		(at barentrance docks)
		(at jordan mansion)
		(at hutexit hut)
		(at coin townsquare)
		(at hutentrance townarch)
		(at oscar bar)
		(at basementexit basement)
		(at mansionentrance cliff)
		(at bankexit bank)
		(at tastycupcake townarch)
		(at forgeentrance townarch)
		(at frank townsquare)
		(at mel bar)
		(closed shopentrance)
		(connected docks junkyard)
		(connected storage basement)
		(connected townsquare townarch)
		(connected basement storage)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected townsquare valley)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(has arthur silver)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has mel basementbucket)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto bankexit townsquare)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
