(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope ash - item
		 storage basement bar docks townarch forge mansion cliff townsquare junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit mansionentrance bankentrance - entrance
		 arthur mel oscar dorian karina peter matthias jordan - character
	)
	(:init
		(at barentrance docks)
		(at mushroom townarch)
		(at karina townarch)
		(at arthur townarch)
		(at mel basement)
		(at oscar bar)
		(at peter forge)
		(at mel storage)
		(at basemententrance bar)
		(at barexit bar)
		(at dorian townarch)
		(at forgeentrance townarch)
		(at hutentrance townarch)
		(at mel bar)
		(at mansionentrance cliff)
		(at jordan mansion)
		(at basementexit basement)
		(at matthias forge)
		(at forgeexit forge)
		(closed hutentrance)
		(connected docks townarch)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected basement storage)
		(connected cliff townsquare)
		(connected storage basement)
		(connected townarch townsquare)
		(connected docks junkyard)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(has dorian lovecontract)
		(has arthur knightsword)
		(has arthur shinykey)
		(has arthur loveletter)
		(has arthur rope)
		(has mel basementbucket)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur knightsword)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
