(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina frank dave james jordan avery roger alli giovanna ian camille phillip michael - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle mirror ash coin silver knightshield rubyring bucket tastycupcake hairtonic book - item
		 storage basement bar docks townarch townsquare valley cliff mansion junkyard bank shop fort hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance mansionexit bankexit shopexit fortexit hutexit - entrance
	)
	(:init
		(at dorian townarch)
		(at james valley)
		(at hutexit hut)
		(at avery mansion)
		(at mel bar)
		(at mansionexit mansion)
		(at hutentrance townarch)
		(at fortexit fort)
		(at barentrance docks)
		(at humanskull cliff)
		(at knightshield shop)
		(at alli junkyard)
		(at mansionentrance cliff)
		(at roger mansion)
		(at karina townarch)
		(at shopexit shop)
		(at giovanna shop)
		(at phillip fort)
		(at mirror townarch)
		(at mel basement)
		(at arthur townarch)
		(at rubyring shop)
		(at fortentrance valley)
		(at basementexit basement)
		(at coin hut)
		(at mushroom townarch)
		(at ian fort)
		(at bankentrance townsquare)
		(at basemententrance bar)
		(at mel storage)
		(at oscar bar)
		(at camille fort)
		(at dave townsquare)
		(at candle mansion)
		(at book hut)
		(at jordan mansion)
		(at frank townsquare)
		(at michael hut)
		(at bucket fort)
		(at barexit bar)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(closed forgeentrance)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected basement storage)
		(connected townarch townsquare)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected storage basement)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected townarch docks)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway townarch docks)
		(doorway docks townarch)
		(has arthur ash)
		(has arthur silver)
		(has jordan lovecontract)
		(has giovanna hairtonic)
		(has alli tastycupcake)
		(has jordan loveletter)
		(has mel basementbucket)
		(has dorian bouquet)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto fortexit valley)
		(leadsto shopexit townsquare)
		(leadsto basementexit bar)
		(leadsto bankexit townsquare)
		(leadsto bankentrance bank)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item dorian rubyring)
		(wants-item james coin)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has alli tastycupcake)
		(has jordan lovecontract)
		(has giovanna hairtonic)
		(has arthur ash)
	  )
	)
)
