(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina frank dave james jordan avery roger alli - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle mirror ash - item
		 storage basement bar docks townarch townsquare valley cliff mansion junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance mansionexit - entrance
	)
	(:init
		(at rubyring shop)
		(at arthur townarch)
		(at alli junkyard)
		(at tastycupcake hut)
		(at dorian townarch)
		(at jordan mansion)
		(at avery mansion)
		(at barexit bar)
		(at mel basement)
		(at mansionentrance cliff)
		(at mel bar)
		(at hutexit hut)
		(at roger mansion)
		(at barentrance docks)
		(at mansionexit mansion)
		(at karina townarch)
		(at dave townsquare)
		(at candle mansion)
		(at fortentrance valley)
		(at basementexit basement)
		(at mirror townarch)
		(at oscar bar)
		(at basemententrance bar)
		(at mel storage)
		(at frank townsquare)
		(at shopentrance townsquare)
		(at mushroom townarch)
		(at forgeentrance townarch)
		(at humanskull cliff)
		(at james valley)
		(at hutentrance townarch)
		(at bankentrance townsquare)
		(closed shopentrance)
		(closed bankentrance)
		(closed fortentrance)
		(closed forgeentrance)
		(closed hutentrance)
		(connected docks townarch)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected basement storage)
		(connected junkyard docks)
		(connected storage basement)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected valley townsquare)
		(connected townsquare townarch)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway valley townsquare)
		(doorway basement storage)
		(doorway storage basement)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(has jordan loveletter)
		(has mel basementbucket)
		(has dorian bouquet)
		(has arthur lovecontract)
		(has alli ash)
		(has arthur shinykey)
		(leadsto mansionentrance mansion)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian rubyring)
		(wants-item jordan lovecontract)
		(wants-item arthur ash)
		(wants-item james coin)
		(wants-item arthur shinykey)
		(wants-item alli tastycupcake)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has alli tastycupcake)
		(has jordan lovecontract)
	  )
	)
)
