(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake - item
		 storage basement bar docks junkyard townarch cliff mansion hut townsquare forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance mansionentrance hutexit bankentrance - entrance
		 arthur mel oscar alli dorian karina jordan - character
	)
	(:init
		(at barentrance docks)
		(at hutexit hut)
		(at barexit bar)
		(at arthur townarch)
		(at tastycupcake hut)
		(at mirror docks)
		(at alli junkyard)
		(at basemententrance bar)
		(at basementexit basement)
		(at hutentrance townarch)
		(at karina townarch)
		(at forgeentrance townarch)
		(at jordan mansion)
		(at mel bar)
		(at mel basement)
		(at mansionentrance cliff)
		(at oscar bar)
		(at mel storage)
		(at dorian townarch)
		(closed forgeentrance)
		(closed basemententrance)
		(closed hutentrance)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected storage basement)
		(connected townarch townsquare)
		(connected basement storage)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(has arthur shinykey)
		(has alli ash)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has mel basementbucket)
		(has arthur mushroom)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item alli tastycupcake)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
