(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter coin - item
		 storage basement bar docks junkyard townarch townsquare valley cliff mansion fort forge shop hut bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance - entrance
		 arthur mel oscar alli dorian karina frank dave james jordan - character
	)
	(:init
		(at dorian townarch)
		(at oscar bar)
		(at frank townsquare)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at basemententrance bar)
		(at alli junkyard)
		(at basementexit basement)
		(at bankentrance townsquare)
		(at fortentrance valley)
		(at mel storage)
		(at mel bar)
		(at mel basement)
		(at arthur valley)
		(at dave townsquare)
		(at james valley)
		(at barexit bar)
		(at jordan mansion)
		(at mansionentrance cliff)
		(at barentrance docks)
		(at hutentrance townarch)
		(at karina townarch)
		(closed basemententrance)
		(closed hutentrance)
		(closed shopentrance)
		(closed forgeentrance)
		(closed fortentrance)
		(closed bankentrance)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected storage basement)
		(connected townarch docks)
		(connected basement storage)
		(doorway townarch townsquare)
		(doorway junkyard docks)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway storage basement)
		(has arthur shinykey)
		(has mel basementbucket)
		(has arthur loveletter)
		(has arthur mushroom)
		(has arthur mirror)
		(has alli ash)
		(has dorian lovecontract)
		(leadsto bankentrance bank)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item james coin)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
