(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet tastycupcake hairtonic book knightsword rope knightshield rubyring coin - item
		 storage basement bar docks junkyard townarch townsquare valley cliff hut forge shop mansion fort bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance hutexit forgeexit shopexit - entrance
		 arthur mel oscar alli dorian karina frank dave james michael peter matthias giovanna jordan - character
	)
	(:init
		(at mel basement)
		(at bankentrance townsquare)
		(at alli junkyard)
		(at matthias forge)
		(at shopentrance townsquare)
		(at mushroom hut)
		(at jordan mansion)
		(at james valley)
		(at shinykey hut)
		(at oscar bar)
		(at forgeexit forge)
		(at giovanna shop)
		(at forgeentrance townarch)
		(at dorian townarch)
		(at barentrance docks)
		(at barexit bar)
		(at book hut)
		(at shopexit shop)
		(at basemententrance bar)
		(at rubyring shop)
		(at basementexit basement)
		(at arthur shop)
		(at frank townsquare)
		(at mansionentrance cliff)
		(at mel storage)
		(at karina townarch)
		(at knightshield shop)
		(at peter forge)
		(at mel bar)
		(at fortentrance valley)
		(at knightsword forge)
		(at michael hut)
		(at hutentrance townarch)
		(at dave townsquare)
		(at humanskull cliff)
		(at hutexit hut)
		(closed basemententrance)
		(closed mansionentrance)
		(closed bankentrance)
		(closed fortentrance)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected storage basement)
		(connected basement storage)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected junkyard docks)
		(connected valley townsquare)
		(connected townsquare valley)
		(doorway townarch townsquare)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway townarch docks)
		(has arthur rope)
		(has alli tastycupcake)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has arthur hairtonic)
		(has mel basementbucket)
		(has arthur mirror)
		(has arthur ash)
		(has arthur bouquet)
		(leadsto shopentrance shop)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(leadsto shopexit townsquare)
		(leadsto fortentrance fort)
		(leadsto forgeexit townarch)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item james coin)
		(wants-item jordan loveletter)
		(wants-item giovanna hairtonic)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rope)
	)
	(:goal
		(or
			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

		)
	)

)
