(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet tastycupcake hairtonic book knightsword rope coin - item
		 storage basement bar docks junkyard townarch townsquare valley cliff hut forge mansion fort bank shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance hutexit forgeexit - entrance
		 arthur mel oscar alli dorian karina frank dave james michael peter matthias jordan - character
	)
	(:init
		(at basementexit basement)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at matthias forge)
		(at jordan mansion)
		(at mushroom hut)
		(at barentrance docks)
		(at forgeexit forge)
		(at dave townsquare)
		(at oscar bar)
		(at shinykey hut)
		(at frank townsquare)
		(at alli junkyard)
		(at dorian townarch)
		(at bankentrance townsquare)
		(at fortentrance valley)
		(at james valley)
		(at karina townarch)
		(at peter forge)
		(at mansionentrance cliff)
		(at knightsword forge)
		(at basemententrance bar)
		(at barexit bar)
		(at arthur forge)
		(at hutentrance townarch)
		(at michael hut)
		(at mel bar)
		(at hutexit hut)
		(at book hut)
		(at mel basement)
		(at humanskull cliff)
		(at mel storage)
		(closed fortentrance)
		(closed basemententrance)
		(closed mansionentrance)
		(closed bankentrance)
		(closed shopentrance)
		(connected townsquare townarch)
		(connected townarch townsquare)
		(connected valley townsquare)
		(connected storage basement)
		(connected junkyard docks)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected townarch docks)
		(connected basement storage)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(has arthur rope)
		(has arthur loveletter)
		(has arthur mirror)
		(has dorian lovecontract)
		(has arthur hairtonic)
		(has alli ash)
		(has arthur tastycupcake)
		(has arthur bouquet)
		(has mel basementbucket)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto shopentrance shop)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto forgeexit townarch)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto bankentrance bank)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item alli tastycupcake)
		(wants-item james coin)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur tastycupcake)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur rope)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
