(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring mirror ash humanskull bouquet candle bucket - item
		 storage basement bar docks townarch forge hut townsquare bank shop junkyard valley cliff mansion fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit fortexit - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave giovanna alli james jordan avery roger ian camille phillip - character
	)
	(:init
		(at phillip fort)
		(at humanskull cliff)
		(at dorian townarch)
		(at james valley)
		(at frank townsquare)
		(at fortentrance valley)
		(at fortexit fort)
		(at michael hut)
		(at forgeentrance townarch)
		(at knightshield shop)
		(at bankexit bank)
		(at candle mansion)
		(at tastycupcake hut)
		(at barexit bar)
		(at bankentrance townsquare)
		(at jordan mansion)
		(at matthias forge)
		(at shopentrance townsquare)
		(at oscar bar)
		(at mansionexit mansion)
		(at barentrance docks)
		(at bucket fort)
		(at hutentrance townarch)
		(at mel storage)
		(at avery mansion)
		(at alli junkyard)
		(at ian fort)
		(at arthur fort)
		(at book townsquare)
		(at mushroom townsquare)
		(at silver bank)
		(at forgeexit forge)
		(at giovanna shop)
		(at hutexit hut)
		(at mel basement)
		(at karina townarch)
		(at peter forge)
		(at mel bar)
		(at basemententrance bar)
		(at camille fort)
		(at basementexit basement)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at roger mansion)
		(at dave townsquare)
		(closed hutentrance)
		(closed basemententrance)
		(closed forgeentrance)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected storage basement)
		(connected junkyard docks)
		(connected basement storage)
		(connected valley townsquare)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected docks townarch)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway junkyard docks)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway basement storage)
		(has arthur rope)
		(has arthur mirror)
		(has alli ash)
		(has arthur knightsword)
		(has mel basementbucket)
		(has james coin)
		(has jordan lovecontract)
		(has giovanna hairtonic)
		(has dorian bouquet)
		(has jordan loveletter)
		(has arthur rubyring)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto hutexit townarch)
		(leadsto bankexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto fortexit valley)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item dorian rubyring)
		(wants-item alli tastycupcake)
		(wants-item james humanskull)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mirror)
	)
	(:goal
		(or
			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) (has jordan lovecontract) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

		)
	)

)
