(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance mansionentrance - entrance
		 storage basement bar docks townarch hut junkyard forge townsquare cliff mansion valley bank shop - location
		 arthur mel oscar dorian karina michael alli peter matthias frank dave jordan - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book mirror ash knightsword rope humanskull bouquet - item
	)
	(:init
		(at peter forge)
		(at matthias forge)
		(at book hut)
		(at arthur cliff)
		(at jordan mansion)
		(at shopentrance townsquare)
		(at hutentrance townarch)
		(at dorian townarch)
		(at oscar bar)
		(at forgeexit forge)
		(at mirror townarch)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at mushroom docks)
		(at alli junkyard)
		(at michael hut)
		(at mel bar)
		(at basemententrance bar)
		(at dave townsquare)
		(at karina townarch)
		(at hutexit hut)
		(at hairtonic hut)
		(at barexit bar)
		(at mel storage)
		(at barentrance docks)
		(at mel basement)
		(at rope docks)
		(at mansionentrance cliff)
		(at humanskull cliff)
		(at basementexit basement)
		(at frank townsquare)
		(closed basemententrance)
		(closed shopentrance)
		(closed bankentrance)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected basement storage)
		(connected townarch docks)
		(connected docks junkyard)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has arthur knightsword)
		(has arthur bouquet)
		(has arthur ash)
		(has alli tastycupcake)
		(has arthur shinykey)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto forgeexit townarch)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
