(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter coin silver bucket humanskull bouquet candle knightshield rubyring tastycupcake hairtonic book knightsword rope ash - item
		 storage basement bar docks townarch townsquare bank valley fort cliff mansion shop hut forge junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit fortentrance fortexit mansionentrance mansionexit shopexit hutexit forgeexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip jordan avery roger giovanna michael peter matthias - character
	)
	(:init
		(at mel basement)
		(at book hut)
		(at frank townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at bucket townsquare)
		(at matthias forge)
		(at bankentrance townsquare)
		(at karina townarch)
		(at candle mansion)
		(at bouquet cliff)
		(at ian fort)
		(at phillip fort)
		(at barexit bar)
		(at rope forge)
		(at oscar bar)
		(at jordan mansion)
		(at tastycupcake hut)
		(at forgeexit forge)
		(at dorian townarch)
		(at avery mansion)
		(at arthur valley)
		(at camille fort)
		(at mel bar)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at basementexit basement)
		(at hutexit hut)
		(at mansionexit mansion)
		(at roger mansion)
		(at mel storage)
		(at fortentrance valley)
		(at barentrance docks)
		(at basemententrance bar)
		(at shopexit shop)
		(at fortexit fort)
		(at michael hut)
		(at mushroom townsquare)
		(at hutentrance townarch)
		(at james valley)
		(at peter forge)
		(at dave townsquare)
		(closed basemententrance)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townarch docks)
		(connected storage basement)
		(connected basement storage)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway basement storage)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(has arthur hairtonic)
		(has mel basementbucket)
		(has jordan loveletter)
		(has arthur knightshield)
		(has jordan lovecontract)
		(has arthur silver)
		(has dorian rubyring)
		(has james humanskull)
		(has james coin)
		(has arthur knightsword)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto bankexit townsquare)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto shopexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto fortentrance fort)
		(leadsto fortexit valley)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item giovanna hairtonic)
		(wants-item ian knightshield)
		(wants-item arthur shinykey)
		(wants-item ian knightsword)
		(wants-item james candle)
		(wants-item dorian bouquet)
		(wants-item arthur ash)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur hairtonic)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

		)
	)

)
