(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter coin silver bucket humanskull bouquet candle knightshield rubyring tastycupcake hairtonic book knightsword rope mirror ash - item
		 storage basement bar docks townarch townsquare bank valley fort cliff mansion shop hut forge junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit fortentrance fortexit mansionentrance mansionexit shopexit hutexit forgeexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip jordan avery roger giovanna michael peter matthias alli - character
	)
	(:init
		(at mushroom townsquare)
		(at bankentrance townsquare)
		(at bouquet cliff)
		(at ian fort)
		(at forgeexit forge)
		(at oscar bar)
		(at book hut)
		(at michael hut)
		(at candle mansion)
		(at forgeentrance townarch)
		(at peter forge)
		(at james valley)
		(at matthias forge)
		(at bucket townsquare)
		(at phillip fort)
		(at dorian townarch)
		(at barexit bar)
		(at bankexit bank)
		(at jordan mansion)
		(at shopentrance townsquare)
		(at hutentrance townarch)
		(at mel storage)
		(at fortexit fort)
		(at camille fort)
		(at mansionexit mansion)
		(at alli junkyard)
		(at hutexit hut)
		(at fortentrance valley)
		(at avery mansion)
		(at rope forge)
		(at tastycupcake hut)
		(at dave townsquare)
		(at basementexit basement)
		(at barentrance docks)
		(at arthur junkyard)
		(at shopexit shop)
		(at karina townarch)
		(at mel basement)
		(at basemententrance bar)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at roger mansion)
		(at frank townsquare)
		(at mel bar)
		(at mirror junkyard)
		(closed basemententrance)
		(connected townsquare cliff)
		(connected storage basement)
		(connected valley townsquare)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected basement storage)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway valley townsquare)
		(doorway basement storage)
		(doorway cliff townsquare)
		(has dorian rubyring)
		(has alli ash)
		(has james humanskull)
		(has james coin)
		(has mel basementbucket)
		(has ian knightsword)
		(has jordan loveletter)
		(has arthur hairtonic)
		(has ian knightshield)
		(has jordan lovecontract)
		(has arthur silver)
		(leadsto bankexit townsquare)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto fortexit valley)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item james candle)
		(wants-item dorian bouquet)
		(wants-item giovanna hairtonic)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

		)
	)

)
