(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle bucket - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop valley cliff mansion fort forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit fortexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna james jordan avery roger ian camille phillip - character
	)
	(:init
		(at shopexit shop)
		(at hutentrance townarch)
		(at rubyring shop)
		(at book townarch)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at jordan mansion)
		(at basemententrance bar)
		(at barentrance docks)
		(at forgeentrance townarch)
		(at candle mansion)
		(at bucket fort)
		(at oscar bar)
		(at bouquet cliff)
		(at mel storage)
		(at bankentrance townsquare)
		(at barexit bar)
		(at camille fort)
		(at basementexit basement)
		(at knightshield shop)
		(at ian fort)
		(at alli junkyard)
		(at phillip fort)
		(at mirror junkyard)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at karina townarch)
		(at roger mansion)
		(at silver townsquare)
		(at michael hut)
		(at mel bar)
		(at fortexit fort)
		(at mansionexit mansion)
		(at fortentrance valley)
		(at hutexit hut)
		(at frank townsquare)
		(at ash townsquare)
		(at james valley)
		(at avery mansion)
		(at humanskull cliff)
		(at arthur valley)
		(at dorian townarch)
		(at dave townsquare)
		(at mel basement)
		(at mushroom townsquare)
		(closed forgeentrance)
		(closed basemententrance)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected docks townarch)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected basement storage)
		(connected townsquare townarch)
		(connected storage basement)
		(connected valley townsquare)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(has dorian lovecontract)
		(has arthur rubyring)
		(has arthur loveletter)
		(has arthur coin)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(leadsto barexit docks)
		(leadsto shopentrance shop)
		(leadsto bankexit townsquare)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto shopexit townsquare)
		(leadsto fortentrance fort)
		(leadsto forgeentrance forge)
		(leadsto fortexit valley)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item james coin)
		(wants-item jordan loveletter)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		(or
			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

		)
	)

)
