(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop cliff mansion valley forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit mansionentrance - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna jordan - character
	)
	(:init
		(at mel basement)
		(at bankentrance townsquare)
		(at coin bank)
		(at oscar bar)
		(at bankexit bank)
		(at shopentrance townsquare)
		(at book townarch)
		(at barexit bar)
		(at jordan mansion)
		(at forgeentrance townarch)
		(at dorian townarch)
		(at hutentrance townarch)
		(at alli junkyard)
		(at rubyring shop)
		(at michael hut)
		(at mel storage)
		(at basemententrance bar)
		(at hairtonic townarch)
		(at arthur shop)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at dave townsquare)
		(at knightshield shop)
		(at barentrance docks)
		(at mel bar)
		(at hutexit hut)
		(at mirror junkyard)
		(at giovanna shop)
		(at frank townsquare)
		(at basementexit basement)
		(at karina townarch)
		(closed basemententrance)
		(closed forgeentrance)
		(connected townarch townsquare)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected basement storage)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected junkyard docks)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway docks junkyard)
		(has dorian lovecontract)
		(has alli tastycupcake)
		(has arthur loveletter)
		(has arthur silver)
		(has arthur mushroom)
		(has mel basementbucket)
		(has arthur ash)
		(leadsto bankexit townsquare)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
