(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake - item
		 storage basement bar docks junkyard townarch hut townsquare forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit bankentrance - entrance
		 arthur mel oscar alli dorian karina - character
	)
	(:init
		(at hutexit hut)
		(at basementexit basement)
		(at oscar bar)
		(at arthur townarch)
		(at dorian townarch)
		(at forgeentrance townarch)
		(at mel storage)
		(at barentrance docks)
		(at hutentrance townarch)
		(at mirror junkyard)
		(at tastycupcake hut)
		(at mel basement)
		(at basemententrance bar)
		(at karina townarch)
		(at barexit bar)
		(at mel bar)
		(at alli junkyard)
		(closed hutentrance)
		(closed forgeentrance)
		(closed basemententrance)
		(connected junkyard docks)
		(connected basement storage)
		(connected storage basement)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected docks townarch)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway basement storage)
		(has dorian lovecontract)
		(has arthur shinykey)
		(has alli ash)
		(has dorian loveletter)
		(has arthur mushroom)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur loveletter)
		(wants-item arthur ash)
		(wants-item alli tastycupcake)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		
			(has alli tastycupcake) 
		

	)

)
