(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop valley cliff mansion fort forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna james jordan avery roger - character
	)
	(:init
		(at mushroom townsquare)
		(at dave townsquare)
		(at arthur townsquare)
		(at coin bank)
		(at mirror junkyard)
		(at rubyring townsquare)
		(at oscar bar)
		(at basemententrance bar)
		(at mel storage)
		(at basementexit basement)
		(at candle mansion)
		(at book townarch)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at barexit bar)
		(at michael hut)
		(at jordan mansion)
		(at bouquet cliff)
		(at forgeentrance townarch)
		(at frank townsquare)
		(at fortentrance valley)
		(at bankentrance townsquare)
		(at alli junkyard)
		(at dorian townarch)
		(at hutexit hut)
		(at avery mansion)
		(at mel bar)
		(at mansionexit mansion)
		(at humanskull cliff)
		(at mel basement)
		(at barentrance docks)
		(at james valley)
		(at knightshield shop)
		(at hutentrance townarch)
		(at mansionentrance cliff)
		(at roger mansion)
		(at hairtonic townarch)
		(at ash townsquare)
		(at rubyring shop)
		(at karina townarch)
		(at shopexit shop)
		(at silver townsquare)
		(at giovanna shop)
		(closed basemententrance)
		(closed forgeentrance)
		(closed fortentrance)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected basement storage)
		(connected storage basement)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected junkyard docks)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(has alli tastycupcake)
		(has arthur loveletter)
		(has mel basementbucket)
		(has dorian lovecontract)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto fortentrance fort)
		(leadsto hutexit townarch)
		(leadsto shopentrance shop)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto bankentrance bank)
		(leadsto shopexit townsquare)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item giovanna hairtonic)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
