(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop valley cliff mansion fort forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna james jordan avery roger - character
	)
	(:init
		(at shopexit shop)
		(at avery mansion)
		(at dorian townarch)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at james valley)
		(at forgeentrance townarch)
		(at barexit bar)
		(at bankentrance townsquare)
		(at bouquet cliff)
		(at book townarch)
		(at jordan mansion)
		(at bankexit bank)
		(at shopentrance townsquare)
		(at oscar bar)
		(at candle mansion)
		(at knightshield shop)
		(at arthur townsquare)
		(at dave townsquare)
		(at coin bank)
		(at rubyring shop)
		(at mel storage)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at karina townarch)
		(at alli junkyard)
		(at roger mansion)
		(at barentrance docks)
		(at mirror junkyard)
		(at basemententrance bar)
		(at mansionexit mansion)
		(at silver townsquare)
		(at mel basement)
		(at ash townsquare)
		(at mel bar)
		(at fortentrance valley)
		(at frank townsquare)
		(at michael hut)
		(at basementexit basement)
		(at hutexit hut)
		(closed forgeentrance)
		(closed basemententrance)
		(closed fortentrance)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected docks townarch)
		(connected valley townsquare)
		(connected storage basement)
		(connected basement storage)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected townarch docks)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(has alli tastycupcake)
		(has dorian lovecontract)
		(has arthur rubyring)
		(has arthur mushroom)
		(has mel basementbucket)
		(has arthur loveletter)
		(has arthur hairtonic)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto shopexit townsquare)
		(leadsto fortentrance fort)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto mansionexit cliff)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item giovanna hairtonic)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
