(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle bucket - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop valley cliff mansion fort forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit fortexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna james jordan avery roger ian camille phillip - character
	)
	(:init
		(at alli junkyard)
		(at dorian townarch)
		(at dave townsquare)
		(at hutentrance townarch)
		(at frank townsquare)
		(at michael hut)
		(at fortexit fort)
		(at jordan mansion)
		(at bankentrance townsquare)
		(at fortentrance valley)
		(at shopentrance townsquare)
		(at mansionexit mansion)
		(at forgeentrance townarch)
		(at bankexit bank)
		(at knightshield shop)
		(at barexit bar)
		(at hutexit hut)
		(at book townarch)
		(at oscar bar)
		(at mirror junkyard)
		(at barentrance docks)
		(at james valley)
		(at bucket fort)
		(at roger mansion)
		(at silver townsquare)
		(at ian fort)
		(at avery mansion)
		(at phillip fort)
		(at rubyring shop)
		(at karina townarch)
		(at mel storage)
		(at mel basement)
		(at mel bar)
		(at giovanna shop)
		(at arthur bar)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at mushroom townsquare)
		(at camille fort)
		(at ash valley)
		(at basementexit basement)
		(at basemententrance bar)
		(at rubyring valley)
		(closed basemententrance)
		(closed forgeentrance)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected storage basement)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected basement storage)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected docks junkyard)
		(doorway docks junkyard)
		(doorway valley townsquare)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway basement storage)
		(has alli tastycupcake)
		(has james candle)
		(has james coin)
		(has dorian lovecontract)
		(has james humanskull)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(has arthur bouquet)
		(has arthur loveletter)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto bankexit townsquare)
		(leadsto bankentrance bank)
		(leadsto hutexit townarch)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto fortexit valley)
		(leadsto shopexit townsquare)
		(leadsto basementexit bar)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item jordan lovecontract)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		(or
			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

		)
	)

)
