(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter ash - item
		 storage basement bar docks townarch cliff mansion townsquare junkyard forge hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance mansionentrance bankentrance - entrance
		 arthur mel oscar dorian karina jordan - character
	)
	(:init
		(at mel storage)
		(at basementexit basement)
		(at barexit bar)
		(at karina townarch)
		(at dorian townarch)
		(at arthur townarch)
		(at mushroom docks)
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at shinykey bar)
		(at jordan mansion)
		(at mel bar)
		(at mel basement)
		(at basemententrance bar)
		(at oscar bar)
		(at mansionentrance cliff)
		(at barentrance docks)
		(closed basemententrance)
		(closed hutentrance)
		(closed forgeentrance)
		(connected docks junkyard)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected storage basement)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway basement storage)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
