(give dorian loveletter arthur townarch)
(open arthur mansionentrance cliff)
(move-through-entrance arthur cliff mansionentrance mansion)
(move-through-entrance arthur mansion mansionexit cliff)
(move-through-doorway arthur cliff townsquare)
(move-through-entrance arthur cliff mansionentrance mansion)
(give arthur loveletter jordan mansion)
(move-through-entrance arthur mansion mansionexit cliff)
(move-through-doorway arthur cliff townsquare)
(move-through-doorway arthur townsquare cliff)
(move-through-entrance arthur cliff mansionentrance mansion)
(move-through-entrance arthur mansion mansionexit cliff)
(move-through-doorway arthur cliff townsquare)
(move-through-doorway arthur townsquare cliff)
(move-through-entrance arthur cliff mansionentrance mansion)
(move-through-entrance arthur mansion mansionexit cliff)
(move-through-doorway arthur cliff townsquare)
(move-through-doorway arthur townsquare cliff)
(move-through-entrance arthur cliff mansionentrance mansion)
(move-through-entrance arthur mansion mansionexit cliff)
(move-through-doorway arthur cliff townsquare)
(move-through-doorway arthur townarch docks)
(move-through-entrance arthur docks barentrance bar)
