(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina frank dave giovanna james jordan avery roger michael peter matthias - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightshield rubyring humanskull bouquet candle tastycupcake hairtonic book knightsword rope coin silver - item
		 storage basement bar docks junkyard townarch townsquare shop valley cliff mansion hut forge bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance shopexit fortentrance mansionentrance mansionexit hutexit forgeexit bankexit - entrance
	)
	(:init
		(at peter forge)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at shopexit shop)
		(at roger mansion)
		(at basementexit basement)
		(at karina townarch)
		(at hutexit hut)
		(at barentrance docks)
		(at basemententrance bar)
		(at mel bar)
		(at mel basement)
		(at coin bank)
		(at arthur shop)
		(at james valley)
		(at dorian townarch)
		(at book hut)
		(at knightsword forge)
		(at michael hut)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at avery mansion)
		(at rubyring shop)
		(at alli junkyard)
		(at fortentrance valley)
		(at frank townsquare)
		(at dave townsquare)
		(at silver bank)
		(at mansionexit mansion)
		(at matthias forge)
		(at shopentrance townsquare)
		(at rope forge)
		(at barexit bar)
		(at jordan mansion)
		(at bankexit bank)
		(at forgeexit forge)
		(at oscar bar)
		(at candle mansion)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at knightshield shop)
		(at mel storage)
		(closed bankentrance)
		(closed fortentrance)
		(closed hutentrance)
		(closed basemententrance)
		(closed barentrance)
		(closed forgeentrance)
		(connected docks junkyard)
		(connected basement storage)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected storage basement)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected junkyard docks)
		(connected townarch docks)
		(connected cliff townsquare)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway valley townsquare)
		(doorway townarch docks)
		(has alli tastycupcake)
		(has arthur mushroom)
		(has arthur mirror)
		(has dorian bouquet)
		(has arthur ash)
		(has jordan loveletter)
		(has mel basementbucket)
		(has giovanna hairtonic)
		(has jordan lovecontract)
		(leadsto mansionentrance mansion)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mirror)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has jordan lovecontract)
		(has arthur ash)
	  )
	)
)
