(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope - item
		 storage basement bar docks junkyard townarch townsquare hut forge cliff mansion valley bank shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance hutexit forgeexit mansionentrance - entrance
		 arthur mel oscar alli dorian karina frank dave michael peter matthias jordan - character
	)
	(:init
		(at karina townarch)
		(at rope forge)
		(at oscar bar)
		(at matthias forge)
		(at forgeexit forge)
		(at jordan mansion)
		(at knightsword forge)
		(at dorian townarch)
		(at hutentrance townarch)
		(at michael hut)
		(at bankentrance townsquare)
		(at shopentrance townsquare)
		(at mirror docks)
		(at barexit bar)
		(at peter forge)
		(at forgeentrance townarch)
		(at mel bar)
		(at book docks)
		(at arthur forge)
		(at dave townsquare)
		(at mel basement)
		(at frank townsquare)
		(at barentrance docks)
		(at basemententrance bar)
		(at mel storage)
		(at basementexit basement)
		(at mansionentrance cliff)
		(at alli junkyard)
		(at mushroom docks)
		(at hairtonic docks)
		(at hutexit hut)
		(closed shopentrance)
		(closed basemententrance)
		(closed bankentrance)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townarch townsquare)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townarch docks)
		(connected basement storage)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(has alli tastycupcake)
		(has dorian lovecontract)
		(has arthur shinykey)
		(has arthur ash)
		(has arthur loveletter)
		(has mel basementbucket)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
