(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring - item
		 storage basement bar docks junkyard townarch townsquare hut forge bank shop valley cliff mansion fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance hutexit forgeexit bankexit shopexit fortentrance mansionentrance - entrance
		 arthur mel oscar alli dorian karina frank dave michael peter matthias giovanna james jordan - character
	)
	(:init
		(at dave townsquare)
		(at basemententrance bar)
		(at coin bank)
		(at forgeexit forge)
		(at oscar bar)
		(at rubyring shop)
		(at rope forge)
		(at book docks)
		(at alli junkyard)
		(at matthias forge)
		(at jordan mansion)
		(at barexit bar)
		(at silver bank)
		(at forgeentrance townarch)
		(at mushroom docks)
		(at arthur bank)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at mel storage)
		(at barentrance docks)
		(at bankentrance townsquare)
		(at giovanna shop)
		(at knightshield shop)
		(at michael hut)
		(at dorian townarch)
		(at karina townarch)
		(at basementexit basement)
		(at mel bar)
		(at frank townsquare)
		(at shopexit shop)
		(at mirror docks)
		(at peter forge)
		(at james valley)
		(at hutentrance townarch)
		(at mel basement)
		(at knightsword forge)
		(at mansionentrance cliff)
		(at fortentrance valley)
		(at hutexit hut)
		(at hairtonic docks)
		(closed fortentrance)
		(closed basemententrance)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected storage basement)
		(connected townsquare townarch)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected docks junkyard)
		(connected basement storage)
		(connected townarch docks)
		(connected junkyard docks)
		(doorway townsquare townarch)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway townarch townsquare)
		(has mel basementbucket)
		(has arthur ash)
		(has alli tastycupcake)
		(has arthur loveletter)
		(has dorian lovecontract)
		(leadsto bankexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto fortentrance fort)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item james coin)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
