(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch townsquare hut cliff mansion valley shop forge bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance hutexit mansionentrance - entrance
		 arthur mel oscar alli dorian karina frank dave michael jordan - character
	)
	(:init
		(at basementexit basement)
		(at mel basement)
		(at hairtonic docks)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at karina townarch)
		(at barexit bar)
		(at basemententrance bar)
		(at jordan mansion)
		(at oscar bar)
		(at mel storage)
		(at michael hut)
		(at mansionentrance cliff)
		(at mushroom docks)
		(at arthur junkyard)
		(at frank townsquare)
		(at book docks)
		(at mirror docks)
		(at dave townsquare)
		(at dorian townarch)
		(at hutexit hut)
		(at forgeentrance townarch)
		(at hutentrance townarch)
		(at mel bar)
		(at barentrance docks)
		(at alli junkyard)
		(at shinykey docks)
		(closed shopentrance)
		(closed bankentrance)
		(closed forgeentrance)
		(closed basemententrance)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected basement storage)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare valley)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway junkyard docks)
		(doorway townsquare townarch)
		(has arthur ash)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has arthur loveletter)
		(has alli tastycupcake)
		(leadsto bankentrance bank)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
