(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 towngate - door
		 arthur mel oscar alli dorian karina peter matthias michael frank dave jordan avery roger - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch forge hut townsquare cliff mansion - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance mansionentrance mansionexit - entrance
	)
	(:init
		(at humanskull cliff)
		(at mansionexit mansion)
		(at hutexit hut)
		(at mel basement)
		(at mel bar)
		(at knightsword forge)
		(at michael hut)
		(at barentrance docks)
		(at peter forge)
		(at hutentrance townarch)
		(at dorian townarch)
		(at alli junkyard)
		(at roger mansion)
		(at arthur cliff)
		(at rubyring shop)
		(at hairtonic hut)
		(at avery mansion)
		(at mansionentrance cliff)
		(at mirror townarch)
		(at rope forge)
		(at karina townarch)
		(at mel storage)
		(at forgeexit forge)
		(at bankentrance townsquare)
		(at mushroom townarch)
		(at ash townarch)
		(at basementexit basement)
		(at basemententrance bar)
		(at oscar bar)
		(at bouquet cliff)
		(at dave townsquare)
		(at candle mansion)
		(at frank townsquare)
		(at matthias forge)
		(at shopentrance townsquare)
		(at book hut)
		(at barexit bar)
		(at jordan mansion)
		(at forgeentrance townarch)
		(closed bankentrance)
		(closed shopentrance)
		(closed basemententrance)
		(connected junkyard docks)
		(connected docks townarch)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected basement storage)
		(connected townsquare cliff)
		(connected storage basement)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway junkyard docks)
		(doorway docks townarch)
		(has mel basementbucket)
		(has arthur shinykey)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has alli tastycupcake)
		(leadsto forgeexit townarch)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item jordan lovecontract)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
	  (AND
		
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur ash)
	  )
	)
)
