(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle knightshield rubyring bucket mirror ash coin silver - item
		 storage basement bar docks townarch hut forge townsquare valley cliff mansion shop fort junkyard bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit fortexit bankexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave james jordan avery roger giovanna ian camille phillip alli - character
	)
	(:init
		(at roger mansion)
		(at rubyring cliff)
		(at fortexit fort)
		(at knightshield cliff)
		(at dave townsquare)
		(at michael hut)
		(at barexit bar)
		(at jordan mansion)
		(at ian fort)
		(at hairtonic cliff)
		(at tastycupcake hut)
		(at bankentrance townsquare)
		(at bankexit bank)
		(at shopentrance townsquare)
		(at matthias forge)
		(at phillip fort)
		(at mushroom townarch)
		(at forgeentrance townarch)
		(at barentrance docks)
		(at oscar bar)
		(at hutentrance townarch)
		(at basementexit basement)
		(at james valley)
		(at mirror junkyard)
		(at karina townarch)
		(at shopexit shop)
		(at alli junkyard)
		(at arthur valley)
		(at avery mansion)
		(at frank townsquare)
		(at mansionentrance cliff)
		(at hutexit hut)
		(at mel storage)
		(at mansionexit mansion)
		(at fortentrance valley)
		(at giovanna shop)
		(at book cliff)
		(at mel basement)
		(at dorian townarch)
		(at bucket cliff)
		(at camille fort)
		(at peter forge)
		(at basemententrance bar)
		(at forgeexit forge)
		(at mel bar)
		(closed basemententrance)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected basement storage)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(has arthur rope)
		(has arthur knightsword)
		(has arthur silver)
		(has james coin)
		(has james humanskull)
		(has arthur ash)
		(has alli tastycupcake)
		(has jordan loveletter)
		(has mel basementbucket)
		(has dorian bouquet)
		(has james candle)
		(has jordan lovecontract)
		(leadsto forgeexit townarch)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto bankexit townsquare)
		(leadsto mansionexit cliff)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto fortexit valley)
		(leadsto shopexit townsquare)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
			(and (has james coin) (has james humanskull) (has james candle) )
		)

	)

)
