(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle knightshield rubyring bucket mirror ash coin silver - item
		 storage basement bar docks townarch hut forge townsquare valley cliff mansion shop fort junkyard bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit fortexit bankexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave james jordan avery roger giovanna ian camille phillip alli - character
	)
	(:init
		(at camille fort)
		(at dave townsquare)
		(at avery mansion)
		(at knightshield cliff)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at barexit bar)
		(at jordan mansion)
		(at matthias forge)
		(at alli junkyard)
		(at mushroom townarch)
		(at forgeexit forge)
		(at oscar bar)
		(at ian fort)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at tastycupcake hut)
		(at barentrance docks)
		(at hairtonic cliff)
		(at mel storage)
		(at candle cliff)
		(at frank townsquare)
		(at phillip fort)
		(at dorian townarch)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at shopexit shop)
		(at roger mansion)
		(at peter forge)
		(at karina townarch)
		(at book cliff)
		(at fortentrance valley)
		(at basementexit basement)
		(at mansionexit mansion)
		(at hutexit hut)
		(at basemententrance bar)
		(at bucket cliff)
		(at mel bar)
		(at humanskull cliff)
		(at james valley)
		(at rubyring cliff)
		(at hutentrance townarch)
		(at michael hut)
		(at fortexit fort)
		(at mirror junkyard)
		(at mel basement)
		(closed basemententrance)
		(connected townarch docks)
		(connected storage basement)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected basement storage)
		(connected junkyard docks)
		(connected docks junkyard)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway junkyard docks)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway storage basement)
		(doorway cliff townsquare)
		(has arthur rope)
		(has arthur ash)
		(has jordan loveletter)
		(has dorian bouquet)
		(has arthur silver)
		(has alli tastycupcake)
		(has arthur knightsword)
		(has james coin)
		(has jordan lovecontract)
		(has mel basementbucket)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto shopexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto fortexit valley)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item james humanskull)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
			(and (has james coin) (has james humanskull) )
		)

	)

)
