(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring ash - item
		 storage basement bar docks townarch forge hut townsquare bank shop cliff mansion valley junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit mansionentrance - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave giovanna jordan - character
	)
	(:init
		(at shopexit shop)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at hutentrance townarch)
		(at matthias forge)
		(at bankexit bank)
		(at shopentrance townsquare)
		(at michael hut)
		(at mel storage)
		(at oscar bar)
		(at forgeexit forge)
		(at basementexit basement)
		(at frank townsquare)
		(at coin bank)
		(at peter forge)
		(at dorian townarch)
		(at arthur hut)
		(at mel basement)
		(at barentrance docks)
		(at knightshield shop)
		(at mel bar)
		(at hutexit hut)
		(at karina townarch)
		(at basemententrance bar)
		(at jordan mansion)
		(at rubyring shop)
		(at dave townsquare)
		(at silver bank)
		(at tastycupcake hut)
		(at mansionentrance cliff)
		(at barexit bar)
		(at giovanna shop)
		(closed forgeentrance)
		(closed basemententrance)
		(closed bankentrance)
		(connected docks townarch)
		(connected storage basement)
		(connected townsquare valley)
		(connected townarch docks)
		(connected basement storage)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway townarch docks)
		(has arthur knightsword)
		(has dorian lovecontract)
		(has arthur book)
		(has arthur mushroom)
		(has arthur rope)
		(has arthur hairtonic)
		(has mel basementbucket)
		(has dorian loveletter)
		(leadsto shopexit townsquare)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto bankexit townsquare)
		(leadsto forgeexit townarch)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur loveletter)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item giovanna hairtonic)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		
			(has giovanna hairtonic) 
		

	)

)
