(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring ash - item
		 storage basement bar docks townarch forge hut townsquare bank shop cliff mansion valley junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit mansionentrance - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave giovanna jordan - character
	)
	(:init
		(at basementexit basement)
		(at jordan mansion)
		(at basemententrance bar)
		(at barexit bar)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at oscar bar)
		(at mel storage)
		(at matthias forge)
		(at shopentrance townsquare)
		(at dorian townarch)
		(at hutentrance townarch)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at michael hut)
		(at arthur townarch)
		(at bankexit bank)
		(at dave townsquare)
		(at mel bar)
		(at mel basement)
		(at giovanna shop)
		(at frank townsquare)
		(at hutexit hut)
		(at peter forge)
		(at silver bank)
		(at barentrance docks)
		(at karina townarch)
		(at knightshield shop)
		(at coin bank)
		(at rubyring shop)
		(at forgeexit forge)
		(at tastycupcake hut)
		(closed hutentrance)
		(closed forgeentrance)
		(closed bankentrance)
		(closed basemententrance)
		(connected townsquare valley)
		(connected townarch docks)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected basement storage)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected storage basement)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(has arthur knightsword)
		(has dorian lovecontract)
		(has arthur book)
		(has arthur rope)
		(has arthur mushroom)
		(has dorian loveletter)
		(has arthur hairtonic)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto hutexit townarch)
		(leadsto bankexit townsquare)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item giovanna hairtonic)
		(wants-item arthur lovecontract)
		(wants-item arthur loveletter)
		(wants-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur knightsword)
	)
	(:goal
		
		
			(has giovanna hairtonic) 
		

	)

)
