(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring ash - item
		 storage basement bar docks townarch forge hut townsquare bank shop cliff mansion valley junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit mansionentrance - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave giovanna jordan - character
	)
	(:init
		(at giovanna shop)
		(at coin bank)
		(at jordan mansion)
		(at bankentrance townsquare)
		(at oscar bar)
		(at shopentrance townsquare)
		(at arthur townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at frank townsquare)
		(at basementexit basement)
		(at michael hut)
		(at dorian townarch)
		(at hutentrance townarch)
		(at peter forge)
		(at mel storage)
		(at matthias forge)
		(at barentrance docks)
		(at mel basement)
		(at mansionentrance cliff)
		(at rubyring shop)
		(at shopexit shop)
		(at mel bar)
		(at tastycupcake hut)
		(at forgeexit forge)
		(at knightshield shop)
		(at hutexit hut)
		(at karina townarch)
		(at silver bank)
		(at basemententrance bar)
		(at dave townsquare)
		(at barexit bar)
		(closed hutentrance)
		(closed basemententrance)
		(closed forgeentrance)
		(closed bankentrance)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected basement storage)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare cliff)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(has arthur book)
		(has dorian lovecontract)
		(has arthur knightsword)
		(has arthur rope)
		(has arthur mushroom)
		(has dorian loveletter)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(leadsto basementexit bar)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
	)
	(:goal
		
		
			(has giovanna hairtonic) 
		

	)

)
