(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver ash - item
		 storage basement bar docks townarch forge hut townsquare bank cliff mansion valley junkyard shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit mansionentrance - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave jordan - character
	)
	(:init
		(at mel basement)
		(at jordan mansion)
		(at oscar bar)
		(at shopentrance townsquare)
		(at arthur townsquare)
		(at matthias forge)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at michael hut)
		(at frank townsquare)
		(at dorian townarch)
		(at coin bank)
		(at hutentrance townarch)
		(at hairtonic hut)
		(at bankentrance townsquare)
		(at basemententrance bar)
		(at basementexit basement)
		(at peter forge)
		(at dave townsquare)
		(at karina townarch)
		(at hutexit hut)
		(at barentrance docks)
		(at forgeexit forge)
		(at barexit bar)
		(at tastycupcake hut)
		(at mel storage)
		(at silver bank)
		(at mansionentrance cliff)
		(at mel bar)
		(closed shopentrance)
		(closed basemententrance)
		(connected storage basement)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townarch docks)
		(connected basement storage)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected townsquare cliff)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway storage basement)
		(has dorian loveletter)
		(has arthur mushroom)
		(has arthur knightsword)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur rope)
		(has arthur book)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto hutexit townarch)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
	)
	(:goal
		(game-has-been-won)
	)
)
