(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring mirror ash humanskull bouquet - item
		 storage basement bar docks townarch forge hut townsquare bank shop junkyard valley cliff mansion fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave giovanna alli james jordan - character
	)
	(:init
		(at hutexit hut)
		(at coin bank)
		(at dave townsquare)
		(at shopexit shop)
		(at matthias forge)
		(at mirror junkyard)
		(at oscar bar)
		(at shopentrance townsquare)
		(at giovanna shop)
		(at forgeentrance townarch)
		(at bouquet cliff)
		(at jordan mansion)
		(at forgeexit forge)
		(at barexit bar)
		(at arthur townsquare)
		(at dorian townarch)
		(at hutentrance townarch)
		(at bankexit bank)
		(at mansionentrance cliff)
		(at michael hut)
		(at fortentrance valley)
		(at humanskull cliff)
		(at karina townarch)
		(at james valley)
		(at bankentrance townsquare)
		(at mel bar)
		(at tastycupcake hut)
		(at basemententrance bar)
		(at mel storage)
		(at basementexit basement)
		(at barentrance docks)
		(at peter forge)
		(at mel basement)
		(at frank townsquare)
		(at alli junkyard)
		(at silver bank)
		(at rubyring shop)
		(at knightshield shop)
		(closed forgeentrance)
		(closed hutentrance)
		(closed basemententrance)
		(closed shopentrance)
		(closed fortentrance)
		(closed mansionentrance)
		(closed bankentrance)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected storage basement)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected townarch docks)
		(connected basement storage)
		(doorway junkyard docks)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway docks junkyard)
		(has mel basementbucket)
		(has arthur loveletter)
		(has alli ash)
		(has dorian lovecontract)
		(has arthur book)
		(has arthur rope)
		(has arthur knightsword)
		(has giovanna hairtonic)
		(has arthur mushroom)
		(leadsto shopentrance shop)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto shopexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto fortentrance fort)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item james coin)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
