(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina frank dave james ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket - item
		 storage basement bar docks townarch townsquare valley fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit - entrance
	)
	(:init
		(at bucket fort)
		(at barexit bar)
		(at barentrance docks)
		(at camille fort)
		(at phillip fort)
		(at mel basement)
		(at karina townarch)
		(at hutentrance townarch)
		(at mel bar)
		(at mel storage)
		(at mansionentrance cliff)
		(at forgeentrance townarch)
		(at dave townsquare)
		(at dorian townarch)
		(at basementexit basement)
		(at basemententrance bar)
		(at fortexit fort)
		(at fortentrance valley)
		(at james valley)
		(at shopentrance townsquare)
		(at arthur valley)
		(at jordan mansion)
		(at oscar bar)
		(at frank townsquare)
		(at ian fort)
		(at bankentrance townsquare)
		(closed bankentrance)
		(closed forgeentrance)
		(closed shopentrance)
		(closed hutentrance)
		(connected storage basement)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch docks)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway townsquare townarch)
		(has arthur shinykey)
		(has arthur mushroom)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur loveletter)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto fortexit valley)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto bankentrance bank)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
	  )
	)
)
