(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna peter matthias jordan avery roger - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring coin silver knightsword rope humanskull bouquet candle - item
		 storage basement bar docks townarch townsquare valley fort shop bank forge cliff mansion - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit bankexit forgeexit mansionentrance mansionexit - entrance
	)
	(:init
		(at barentrance docks)
		(at rubyring shop)
		(at roger mansion)
		(at knightshield shop)
		(at phillip fort)
		(at jordan mansion)
		(at arthur cliff)
		(at barexit bar)
		(at karina townarch)
		(at ian fort)
		(at giovanna shop)
		(at mel basement)
		(at mel bar)
		(at shopexit shop)
		(at mansionexit mansion)
		(at mansionentrance cliff)
		(at fortentrance valley)
		(at bankentrance townsquare)
		(at hutentrance townarch)
		(at bouquet cliff)
		(at james valley)
		(at camille fort)
		(at bucket fort)
		(at fortexit fort)
		(at frank townsquare)
		(at forgeentrance townarch)
		(at dave townsquare)
		(at matthias forge)
		(at dorian townarch)
		(at avery mansion)
		(at bankexit bank)
		(at shopentrance townsquare)
		(closed hutentrance)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected docks townarch)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway docks townarch)
		(has james humanskull)
		(has ian knightshield)
		(has arthur mushroom)
		(has james candle)
		(has jordan loveletter)
		(has arthur lovecontract)
		(has arthur silver)
		(has ian knightsword)
		(has james coin)
		(has dorian rubyring)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto fortexit valley)
		(leadsto mansionexit cliff)
		(leadsto fortentrance fort)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item jordan lovecontract)
		(wants-item giovanna hairtonic)
		(wants-item arthur shinykey)
		(wants-item dorian bouquet)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has james coin)
		(has james humanskull)
		(has ian knightsword)
		(has ian knightshield)
		(has james candle)
		(has jordan lovecontract)
	  )
	)
)
