(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna peter matthias jordan avery roger - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring coin silver knightsword rope humanskull bouquet candle - item
		 storage basement bar docks townarch townsquare valley fort shop bank forge cliff mansion - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit bankexit forgeexit mansionentrance mansionexit - entrance
	)
	(:init
		(at giovanna shop)
		(at camille fort)
		(at arthur mansion)
		(at jordan mansion)
		(at frank townsquare)
		(at bucket fort)
		(at matthias forge)
		(at mel bar)
		(at phillip fort)
		(at barexit bar)
		(at bankexit bank)
		(at ian fort)
		(at karina townarch)
		(at rubyring shop)
		(at bouquet cliff)
		(at candle mansion)
		(at mansionentrance cliff)
		(at roger mansion)
		(at fortexit fort)
		(at james valley)
		(at forgeentrance townarch)
		(at shopexit shop)
		(at humanskull cliff)
		(at bankentrance townsquare)
		(at shopentrance townsquare)
		(at fortentrance valley)
		(at knightshield shop)
		(at dave townsquare)
		(at mansionexit mansion)
		(at mel basement)
		(at avery mansion)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected storage basement)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway valley townsquare)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway storage basement)
		(has arthur silver)
		(has arthur loveletter)
		(has arthur mushroom)
		(has james coin)
		(has arthur rubyring)
		(has ian knightsword)
		(has ian knightshield)
		(leadsto mansionexit cliff)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto fortentrance fort)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto fortexit valley)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(wants-item jordan lovecontract)
		(wants-item james humanskull)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item giovanna hairtonic)
		(wants-item arthur ash)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur ash)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has james coin)
		(has james humanskull)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
