(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle rubyring ash - item
		 storage basement bar docks townarch townsquare cliff mansion shop junkyard valley forge bank hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger - character
	)
	(:init
		(at frank townsquare)
		(at forgeentrance townarch)
		(at dorian townarch)
		(at mansionexit mansion)
		(at mel storage)
		(at arthur townarch)
		(at barexit bar)
		(at roger mansion)
		(at mansionentrance cliff)
		(at jordan mansion)
		(at bankentrance townsquare)
		(at shopentrance townsquare)
		(at avery mansion)
		(at shinykey bar)
		(at oscar bar)
		(at basemententrance bar)
		(at mel basement)
		(at humanskull cliff)
		(at basementexit basement)
		(at candle mansion)
		(at karina townarch)
		(at mel bar)
		(at hutentrance townarch)
		(at barentrance docks)
		(at dave townsquare)
		(at rubyring shop)
		(closed shopentrance)
		(closed bankentrance)
		(closed forgeentrance)
		(connected docks junkyard)
		(connected docks townarch)
		(connected basement storage)
		(connected townarch docks)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected storage basement)
		(connected townsquare townarch)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway basement storage)
		(has jordan loveletter)
		(has mel basementbucket)
		(has arthur mushroom)
		(has jordan lovecontract)
		(has dorian bouquet)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto mansionexit cliff)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto barexit docks)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		
			(and (has jordan loveletter) (has jordan lovecontract) )
		

	)

)
