(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle rubyring ash - item
		 storage basement bar docks townarch townsquare cliff mansion shop valley junkyard forge bank hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger - character
	)
	(:init
		(at barentrance docks)
		(at barexit bar)
		(at arthur townarch)
		(at candle mansion)
		(at dorian townarch)
		(at mansionentrance cliff)
		(at jordan mansion)
		(at shopentrance townsquare)
		(at avery mansion)
		(at karina townarch)
		(at bankentrance townsquare)
		(at basemententrance bar)
		(at mel bar)
		(at mansionexit mansion)
		(at mel storage)
		(at basementexit basement)
		(at mel basement)
		(at humanskull cliff)
		(at forgeentrance townarch)
		(at oscar bar)
		(at shinykey bar)
		(at rubyring shop)
		(at dave townsquare)
		(at roger mansion)
		(at hutentrance townarch)
		(at frank townsquare)
		(closed shopentrance)
		(closed forgeentrance)
		(closed bankentrance)
		(closed hutentrance)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected docks junkyard)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected storage basement)
		(connected townsquare valley)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(has arthur mushroom)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has mel basementbucket)
		(has dorian bouquet)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		
			(and (has jordan loveletter) (has jordan lovecontract) )
		

	)

)
