(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet ash - item
		 storage basement bar docks townarch townsquare cliff mansion valley junkyard hut shop bank forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave jordan - character
	)
	(:init
		(at jordan mansion)
		(at barexit bar)
		(at arthur cliff)
		(at shinykey bar)
		(at mansionentrance cliff)
		(at karina townarch)
		(at dorian townarch)
		(at shopentrance townsquare)
		(at basementexit basement)
		(at bankentrance townsquare)
		(at frank townsquare)
		(at forgeentrance townarch)
		(at mel bar)
		(at hutentrance townarch)
		(at oscar bar)
		(at dave townsquare)
		(at bouquet cliff)
		(at basemententrance bar)
		(at mel storage)
		(at barentrance docks)
		(at humanskull cliff)
		(at mel basement)
		(closed mansionentrance)
		(closed bankentrance)
		(closed shopentrance)
		(closed hutentrance)
		(closed forgeentrance)
		(connected townarch docks)
		(connected docks junkyard)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected storage basement)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway storage basement)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has arthur mushroom)
		(has mel basementbucket)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto barexit docks)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
