(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance - entrance
		 storage basement bar docks junkyard townarch hut forge townsquare bank shop valley cliff mansion fort - location
		 arthur mel oscar alli dorian karina michael peter matthias frank dave giovanna james jordan - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring - item
	)
	(:init
		(at peter forge)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at arthur valley)
		(at forgeexit forge)
		(at oscar bar)
		(at rubyring shop)
		(at michael hut)
		(at shopentrance townsquare)
		(at book hut)
		(at barexit bar)
		(at jordan mansion)
		(at frank townsquare)
		(at rope forge)
		(at matthias forge)
		(at hairtonic hut)
		(at dorian townarch)
		(at knightsword forge)
		(at bankentrance townsquare)
		(at mel bar)
		(at knightshield shop)
		(at karina townarch)
		(at fortentrance valley)
		(at hutentrance townarch)
		(at mel storage)
		(at james valley)
		(at barentrance docks)
		(at dave townsquare)
		(at tastycupcake hut)
		(at mel basement)
		(at basementexit basement)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at alli junkyard)
		(at hutexit hut)
		(at shopexit shop)
		(at basemententrance bar)
		(closed basemententrance)
		(closed fortentrance)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare cliff)
		(connected valley townsquare)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected junkyard docks)
		(connected townarch docks)
		(connected docks junkyard)
		(connected basement storage)
		(connected townarch townsquare)
		(connected townsquare valley)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(has alli ash)
		(has dorian lovecontract)
		(has arthur silver)
		(has mel basementbucket)
		(has arthur mushroom)
		(has arthur mirror)
		(has dorian loveletter)
		(has james coin)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(leadsto bankexit townsquare)
		(leadsto shopentrance shop)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item giovanna hairtonic)
		(wants-item jordan loveletter)
		(wants-item arthur loveletter)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has james coin) 
		)

	)

)
