(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit mansionentrance bankentrance - entrance
		 storage basement bar docks junkyard townarch hut mansion cliff townsquare forge - location
		 arthur mel oscar alli dorian karina michael jordan - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book - item
	)
	(:init
		(at tastycupcake hut)
		(at arthur townarch)
		(at hairtonic hut)
		(at karina townarch)
		(at mansionentrance cliff)
		(at dorian townarch)
		(at mel storage)
		(at jordan mansion)
		(at barentrance docks)
		(at alli junkyard)
		(at barexit bar)
		(at mel basement)
		(at hutentrance townarch)
		(at mel bar)
		(at michael hut)
		(at basementexit basement)
		(at hutexit hut)
		(at book hut)
		(at basemententrance bar)
		(at oscar bar)
		(at forgeentrance townarch)
		(closed basemententrance)
		(closed forgeentrance)
		(connected basement storage)
		(connected docks junkyard)
		(connected docks townarch)
		(connected junkyard docks)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected storage basement)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway storage basement)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(has arthur mirror)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has arthur shinykey)
		(has dorian loveletter)
		(has alli ash)
		(has arthur mushroom)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur loveletter)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
	)
)
