(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit mansionentrance - entrance
		 storage basement bar docks junkyard townarch hut forge townsquare bank cliff mansion valley shop - location
		 arthur mel oscar alli dorian karina michael peter matthias frank dave jordan - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver - item
	)
	(:init
		(at basementexit basement)
		(at jordan mansion)
		(at barexit bar)
		(at hairtonic hut)
		(at bankentrance townsquare)
		(at forgeentrance townarch)
		(at oscar bar)
		(at forgeexit forge)
		(at matthias forge)
		(at rope forge)
		(at bankexit bank)
		(at shopentrance townsquare)
		(at frank townsquare)
		(at alli junkyard)
		(at book hut)
		(at mel storage)
		(at arthur bank)
		(at coin bank)
		(at karina townarch)
		(at hutexit hut)
		(at mel basement)
		(at mel bar)
		(at knightsword forge)
		(at tastycupcake hut)
		(at basemententrance bar)
		(at barentrance docks)
		(at dave townsquare)
		(at mansionentrance cliff)
		(at hutentrance townarch)
		(at michael hut)
		(at dorian townarch)
		(at peter forge)
		(closed shopentrance)
		(closed basemententrance)
		(connected basement storage)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected storage basement)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected junkyard docks)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(has mel basementbucket)
		(has arthur mushroom)
		(has alli ash)
		(has arthur mirror)
		(has dorian loveletter)
		(has dorian lovecontract)
		(has arthur silver)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto forgeexit townarch)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur loveletter)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mirror)
	)
	(:goal
	)
)
