(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina frank dave james jordan avery roger giovanna michael ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet candle knightshield rubyring tastycupcake hairtonic book bucket - item
		 storage basement bar docks junkyard townarch townsquare valley cliff mansion shop hut fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit hutexit fortexit - entrance
	)
	(:init
		(at barentrance docks)
		(at mirror townarch)
		(at knightshield shop)
		(at alli junkyard)
		(at phillip fort)
		(at dorian townarch)
		(at jordan mansion)
		(at barexit bar)
		(at avery mansion)
		(at humanskull townarch)
		(at mansionentrance cliff)
		(at mel bar)
		(at giovanna shop)
		(at mel basement)
		(at bucket townarch)
		(at roger mansion)
		(at mansionexit mansion)
		(at karina townarch)
		(at hutexit hut)
		(at shopexit shop)
		(at james valley)
		(at candle townarch)
		(at peter forge)
		(at basementexit basement)
		(at frank townsquare)
		(at fortentrance valley)
		(at mel storage)
		(at oscar bar)
		(at basemententrance bar)
		(at camille fort)
		(at dave townsquare)
		(at michael hut)
		(at mushroom townarch)
		(at ian fort)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at knightsword forge)
		(at arthur townsquare)
		(at hutentrance townarch)
		(at fortexit fort)
		(at bankentrance townsquare)
		(closed bankentrance)
		(closed basemententrance)
		(closed forgeentrance)
		(connected valley townsquare)
		(connected basement storage)
		(connected cliff townsquare)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected townarch docks)
		(connected docks junkyard)
		(connected storage basement)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected docks townarch)
		(connected townarch townsquare)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway junkyard docks)
		(has alli ash)
		(has jordan loveletter)
		(has arthur knightshield)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(has jordan lovecontract)
		(has dorian bouquet)
		(has arthur tastycupcake)
		(has arthur shinykey)
		(has dorian rubyring)
		(has arthur book)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto fortexit valley)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item ian knightsword)
		(wants-item arthur shinykey)
		(wants-item ian knightshield)
		(wants-item alli tastycupcake)
		(wants-item arthur ash)
		(wants-item james coin)
		(willing-to-give-item arthur tastycupcake)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has jordan lovecontract)
		(has giovanna hairtonic)
		(has james coin)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
