(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring mirror ash humanskull bouquet candle - item
		 storage basement bar docks townarch forge hut townsquare bank shop junkyard valley cliff mansion fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave giovanna alli james jordan avery roger - character
	)
	(:init
		(at tastycupcake hut)
		(at fortentrance valley)
		(at michael hut)
		(at forgeexit forge)
		(at oscar bar)
		(at mel storage)
		(at candle mansion)
		(at basemententrance bar)
		(at arthur townsquare)
		(at hutentrance townarch)
		(at matthias forge)
		(at james valley)
		(at humanskull cliff)
		(at shopentrance townsquare)
		(at dorian townarch)
		(at forgeentrance townarch)
		(at bankexit bank)
		(at bankentrance townsquare)
		(at peter forge)
		(at basementexit basement)
		(at frank townsquare)
		(at shopexit shop)
		(at silver bank)
		(at mushroom townsquare)
		(at knightshield shop)
		(at barentrance docks)
		(at jordan mansion)
		(at karina townarch)
		(at dave townsquare)
		(at book townsquare)
		(at barexit bar)
		(at coin bank)
		(at mel bar)
		(at hutexit hut)
		(at mansionentrance cliff)
		(at mel basement)
		(at giovanna shop)
		(at mansionexit mansion)
		(at alli junkyard)
		(at roger mansion)
		(at avery mansion)
		(closed hutentrance)
		(closed fortentrance)
		(closed basemententrance)
		(closed bankentrance)
		(closed forgeentrance)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected storage basement)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected docks junkyard)
		(connected basement storage)
		(connected valley townsquare)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected townarch docks)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway docks townarch)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(has dorian bouquet)
		(has arthur rope)
		(has giovanna hairtonic)
		(has arthur knightsword)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has arthur mirror)
		(has arthur rubyring)
		(has alli ash)
		(has mel basementbucket)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto fortentrance fort)
		(leadsto forgeexit townarch)
		(leadsto bankentrance bank)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto mansionexit cliff)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item james coin)
		(wants-item alli tastycupcake)
		(wants-item dorian rubyring)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
		(or
			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) (has jordan lovecontract) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) 
			)

		)
	)

)
