(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 towngate - door
		 arthur mel oscar dorian karina michael alli peter matthias - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book mirror ash knightsword rope - item
		 storage basement bar docks townarch hut junkyard forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit - entrance
	)
	(:init
		(at michael hut)
		(at mel bar)
		(at oscar bar)
		(at mirror junkyard)
		(at arthur junkyard)
		(at basementexit basement)
		(at basemententrance bar)
		(at jordan mansion)
		(at matthias forge)
		(at mansionentrance cliff)
		(at karina townarch)
		(at forgeentrance townarch)
		(at mel storage)
		(at peter forge)
		(at barentrance docks)
		(at hairtonic hut)
		(at tastycupcake hut)
		(at alli junkyard)
		(at barexit bar)
		(at book hut)
		(at forgeexit forge)
		(at mel basement)
		(at dorian townarch)
		(at hutexit hut)
		(at hutentrance townarch)
		(closed basemententrance)
		(connected cliff townsquare)
		(connected basement storage)
		(connected docks townarch)
		(connected storage basement)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected townarch docks)
		(connected docks junkyard)
		(connected townsquare cliff)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(has arthur loveletter)
		(has arthur knightsword)
		(has mel basementbucket)
		(has arthur rope)
		(has alli ash)
		(has dorian lovecontract)
		(has arthur shinykey)
		(has arthur mushroom)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto forgeexit townarch)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
	  (AND
		
		(not (locked basementexit))
		(has jordan loveletter)
	  )
	)
)
