(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 towngate - door
		 arthur mel oscar dorian karina michael alli peter matthias frank dave jordan avery roger james - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book mirror ash knightsword rope humanskull bouquet candle - item
		 storage basement bar docks townarch hut junkyard forge townsquare cliff mansion valley - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance mansionentrance mansionexit fortentrance - entrance
	)
	(:init
		(at roger mansion)
		(at mel bar)
		(at karina townarch)
		(at alli junkyard)
		(at mirror townarch)
		(at rubyring shop)
		(at mushroom docks)
		(at forgeexit forge)
		(at hutexit hut)
		(at fortentrance valley)
		(at mel basement)
		(at rope docks)
		(at mansionentrance cliff)
		(at humanskull cliff)
		(at basementexit basement)
		(at frank townsquare)
		(at book hut)
		(at dave townsquare)
		(at hairtonic hut)
		(at mel storage)
		(at basemententrance bar)
		(at peter forge)
		(at arthur valley)
		(at avery mansion)
		(at james valley)
		(at michael hut)
		(at dorian townarch)
		(at hutentrance townarch)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at barexit bar)
		(at jordan mansion)
		(at matthias forge)
		(at barentrance docks)
		(at candle mansion)
		(at oscar bar)
		(at mansionexit mansion)
		(closed shopentrance)
		(closed basemententrance)
		(closed fortentrance)
		(closed bankentrance)
		(connected docks townarch)
		(connected basement storage)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected valley townsquare)
		(connected storage basement)
		(connected townsquare valley)
		(connected townsquare townarch)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway junkyard docks)
		(has arthur ash)
		(has arthur shinykey)
		(has arthur bouquet)
		(has arthur loveletter)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has alli tastycupcake)
		(has arthur knightsword)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto forgeexit townarch)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
	  (AND
		
		(not (locked basementexit))
		(has jordan loveletter)
		(has alli tastycupcake)
		(has arthur ash)
	  )
	)
)
