(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet tastycupcake - item
		 storage basement bar docks junkyard townarch townsquare cliff valley hut forge shop mansion bank fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave james - character
	)
	(:init
		(at bankentrance townsquare)
		(at fortentrance valley)
		(at arthur townsquare)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at hutentrance townarch)
		(at bouquet cliff)
		(at shinykey bar)
		(at mirror junkyard)
		(at barentrance docks)
		(at basementexit basement)
		(at dave townsquare)
		(at basemententrance bar)
		(at oscar bar)
		(at mel storage)
		(at tastycupcake hut)
		(at mansionentrance cliff)
		(at dorian townarch)
		(at humanskull cliff)
		(at james valley)
		(at barexit bar)
		(at frank townsquare)
		(at mel bar)
		(at hutexit hut)
		(at karina townarch)
		(at alli junkyard)
		(at mel basement)
		(closed fortentrance)
		(closed basemententrance)
		(closed bankentrance)
		(closed mansionentrance)
		(closed forgeentrance)
		(closed hutentrance)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected storage basement)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected junkyard docks)
		(connected basement storage)
		(connected townsquare valley)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected docks junkyard)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(doorway townarch docks)
		(doorway junkyard docks)
		(has mel basementbucket)
		(has arthur mushroom)
		(has dorian loveletter)
		(has alli ash)
		(has dorian lovecontract)
		(leadsto barexit docks)
		(leadsto fortentrance fort)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item alli tastycupcake)
		(wants-item arthur ash)
		(wants-item arthur loveletter)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		
			(has alli tastycupcake) 
		

	)

)
