(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightshield rubyring tastycupcake hairtonic book candle - item
		 storage basement bar docks junkyard townarch townsquare cliff valley shop hut mansion bank forge fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance shopexit hutexit mansionexit - entrance
		 arthur mel oscar alli dorian karina frank dave james giovanna michael jordan avery roger - character
	)
	(:init
		(at dave townsquare)
		(at roger mansion)
		(at frank townsquare)
		(at avery mansion)
		(at mushroom hut)
		(at mirror junkyard)
		(at jordan mansion)
		(at barentrance docks)
		(at barexit bar)
		(at candle mansion)
		(at oscar bar)
		(at bankentrance townsquare)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at knightshield shop)
		(at mansionexit mansion)
		(at alli junkyard)
		(at rubyring shop)
		(at fortentrance valley)
		(at hutentrance townarch)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at karina townarch)
		(at basementexit basement)
		(at humanskull cliff)
		(at mel bar)
		(at hutexit hut)
		(at mel storage)
		(at shopexit shop)
		(at arthur bar)
		(at mel basement)
		(at shinykey bar)
		(at james valley)
		(at dorian townarch)
		(at book hut)
		(at michael hut)
		(at basemententrance bar)
		(closed bankentrance)
		(closed forgeentrance)
		(closed basemententrance)
		(closed fortentrance)
		(connected townarch docks)
		(connected junkyard docks)
		(connected townsquare valley)
		(connected storage basement)
		(connected townsquare cliff)
		(connected valley townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected townsquare townarch)
		(connected docks townarch)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway valley townsquare)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(has arthur ash)
		(has mel basementbucket)
		(has giovanna hairtonic)
		(has dorian bouquet)
		(has alli tastycupcake)
		(has jordan loveletter)
		(has jordan lovecontract)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
