(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring humanskull bouquet candle coin silver knightsword ash - item
		 storage basement bar docks townarch townsquare valley fort shop cliff mansion bank forge junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit mansionentrance mansionexit bankexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna jordan avery roger peter - character
	)
	(:init
		(at fortexit fort)
		(at barentrance docks)
		(at mushroom cliff)
		(at roger mansion)
		(at giovanna shop)
		(at rubyring shop)
		(at oscar bar)
		(at mel storage)
		(at basemententrance bar)
		(at karina townarch)
		(at shopentrance townsquare)
		(at camille fort)
		(at peter forge)
		(at phillip fort)
		(at bankentrance townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at basementexit basement)
		(at shopexit shop)
		(at silver bank)
		(at humanskull cliff)
		(at knightsword forge)
		(at bouquet mansion)
		(at mel basement)
		(at jordan mansion)
		(at fortentrance valley)
		(at frank townsquare)
		(at barexit bar)
		(at avery mansion)
		(at hutentrance townarch)
		(at james valley)
		(at mel bar)
		(at dorian townarch)
		(at dave townsquare)
		(at ian fort)
		(at arthur valley)
		(at mansionentrance cliff)
		(at mansionexit mansion)
		(closed forgeentrance)
		(closed hutentrance)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected valley townsquare)
		(connected basement storage)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected storage basement)
		(connected townsquare valley)
		(connected docks junkyard)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway townsquare cliff)
		(has arthur rubyring)
		(has dorian lovecontract)
		(has arthur knightshield)
		(has arthur bucket)
		(has jordan loveletter)
		(has arthur candle)
		(has mel basementbucket)
		(has arthur coin)
		(leadsto basemententrance basement)
		(leadsto shopentrance shop)
		(leadsto bankexit townsquare)
		(leadsto fortentrance fort)
		(leadsto mansionexit cliff)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(leadsto fortexit valley)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item ian knightshield)
		(wants-item dorian rubyring)
		(wants-item arthur lovecontract)
		(wants-item james coin)
		(wants-item dorian bouquet)
		(wants-item ian knightsword)
		(wants-item jordan lovecontract)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur candle)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
