(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring humanskull bouquet candle coin silver knightsword ash - item
		 storage basement bar docks townarch townsquare valley fort shop cliff mansion bank forge junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit mansionentrance mansionexit bankexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna jordan avery roger peter - character
	)
	(:init
		(at mushroom cliff)
		(at karina townarch)
		(at shopexit shop)
		(at humanskull cliff)
		(at frank townsquare)
		(at roger mansion)
		(at peter forge)
		(at basemententrance bar)
		(at knightsword forge)
		(at jordan mansion)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at oscar bar)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at barexit bar)
		(at camille fort)
		(at dave townsquare)
		(at rubyring shop)
		(at mel storage)
		(at dorian townarch)
		(at arthur bank)
		(at fortexit fort)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at fortentrance valley)
		(at mansionexit mansion)
		(at barentrance docks)
		(at mel basement)
		(at bouquet mansion)
		(at mel bar)
		(at ian fort)
		(at basementexit basement)
		(at james valley)
		(at hutentrance townarch)
		(at phillip fort)
		(at silver bank)
		(at avery mansion)
		(closed hutentrance)
		(closed forgeentrance)
		(connected docks junkyard)
		(connected storage basement)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected basement storage)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(has arthur coin)
		(has jordan loveletter)
		(has arthur candle)
		(has arthur bucket)
		(has arthur knightshield)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur rubyring)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto fortexit valley)
		(leadsto mansionentrance mansion)
		(leadsto shopexit townsquare)
		(leadsto bankexit townsquare)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian bouquet)
		(wants-item ian knightshield)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(wants-item arthur ash)
		(wants-item ian knightsword)
		(wants-item james coin)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur candle)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
