(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring humanskull bouquet candle knightsword ash coin - item
		 storage basement bar docks townarch townsquare valley fort shop cliff mansion forge junkyard bank hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna jordan avery roger peter - character
	)
	(:init
		(at mel basement)
		(at frank townsquare)
		(at shinykey bar)
		(at karina townarch)
		(at oscar bar)
		(at shopentrance townsquare)
		(at basemententrance bar)
		(at jordan mansion)
		(at james valley)
		(at barexit bar)
		(at mel storage)
		(at bankentrance townsquare)
		(at bouquet mansion)
		(at dave townsquare)
		(at forgeentrance townarch)
		(at dorian townarch)
		(at shopexit shop)
		(at fortexit fort)
		(at roger mansion)
		(at humanskull cliff)
		(at avery mansion)
		(at mel bar)
		(at giovanna shop)
		(at fortentrance valley)
		(at mushroom cliff)
		(at phillip fort)
		(at camille fort)
		(at barentrance docks)
		(at mansionexit mansion)
		(at basementexit basement)
		(at peter forge)
		(at mansionentrance cliff)
		(at hutentrance townarch)
		(at rubyring shop)
		(at arthur townarch)
		(at knightsword forge)
		(at ian fort)
		(closed bankentrance)
		(closed hutentrance)
		(closed forgeentrance)
		(connected basement storage)
		(connected cliff townsquare)
		(connected storage basement)
		(connected valley townsquare)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected docks junkyard)
		(connected townsquare valley)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway docks townarch)
		(doorway townsquare valley)
		(has arthur candle)
		(has arthur knightshield)
		(has dorian lovecontract)
		(has arthur bucket)
		(has arthur rubyring)
		(has jordan loveletter)
		(has mel basementbucket)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto shopentrance shop)
		(leadsto fortexit valley)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto shopexit townsquare)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto fortentrance fort)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item ian knightshield)
		(wants-item dorian bouquet)
		(wants-item jordan lovecontract)
		(wants-item james coin)
		(wants-item ian knightsword)
		(wants-item dorian rubyring)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur candle)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur rubyring)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
