(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring humanskull bouquet candle knightsword ash coin - item
		 storage basement bar docks townarch townsquare valley fort shop cliff mansion forge junkyard bank hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna jordan avery roger peter - character
	)
	(:init
		(at shopexit shop)
		(at mel storage)
		(at barentrance docks)
		(at bankentrance townsquare)
		(at candle mansion)
		(at oscar bar)
		(at phillip fort)
		(at rubyring shop)
		(at forgeentrance townarch)
		(at roger mansion)
		(at dave townsquare)
		(at camille fort)
		(at jordan mansion)
		(at peter forge)
		(at basemententrance bar)
		(at shopentrance townsquare)
		(at dorian townarch)
		(at fortexit fort)
		(at avery mansion)
		(at mansionentrance cliff)
		(at fortentrance valley)
		(at mansionexit mansion)
		(at james valley)
		(at frank townsquare)
		(at basementexit basement)
		(at knightsword forge)
		(at shinykey bar)
		(at arthur mansion)
		(at barexit bar)
		(at giovanna shop)
		(at mel basement)
		(at mushroom cliff)
		(at humanskull cliff)
		(at hutentrance townarch)
		(at mel bar)
		(at ian fort)
		(at karina townarch)
		(closed forgeentrance)
		(closed bankentrance)
		(closed hutentrance)
		(connected townsquare cliff)
		(connected storage basement)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townarch docks)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(has dorian lovecontract)
		(has arthur bucket)
		(has arthur rubyring)
		(has jordan loveletter)
		(has mel basementbucket)
		(has arthur bouquet)
		(has arthur knightshield)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(leadsto fortexit valley)
		(leadsto mansionentrance mansion)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item james coin)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item ian knightshield)
		(wants-item ian knightsword)
		(wants-item arthur ash)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur rubyring)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
