(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring humanskull bouquet candle coin silver knightsword rope ash - item
		 storage basement bar docks townarch townsquare valley fort shop cliff mansion bank forge junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit mansionentrance mansionexit bankexit forgeexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna jordan avery roger peter matthias - character
	)
	(:init
		(at basemententrance bar)
		(at candle forge)
		(at bucket valley)
		(at avery mansion)
		(at peter forge)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at matthias forge)
		(at jordan mansion)
		(at mushroom valley)
		(at forgeexit forge)
		(at oscar bar)
		(at bankentrance townsquare)
		(at forgeentrance townarch)
		(at ian fort)
		(at barexit bar)
		(at silver valley)
		(at bouquet mansion)
		(at phillip fort)
		(at basementexit basement)
		(at rubyring shop)
		(at hutentrance townarch)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at roger mansion)
		(at karina townarch)
		(at shopexit shop)
		(at barentrance docks)
		(at fortentrance valley)
		(at arthur valley)
		(at mansionexit mansion)
		(at rope forge)
		(at mel storage)
		(at mel bar)
		(at camille fort)
		(at james valley)
		(at dorian townarch)
		(at dave townsquare)
		(at frank townsquare)
		(at fortexit fort)
		(at mel basement)
		(closed hutentrance)
		(connected docks junkyard)
		(connected townarch docks)
		(connected townsquare valley)
		(connected storage basement)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected basement storage)
		(connected valley townsquare)
		(connected townarch townsquare)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(has ian knightsword)
		(has james humanskull)
		(has dorian rubyring)
		(has jordan loveletter)
		(has james coin)
		(has ian knightshield)
		(has mel basementbucket)
		(has jordan lovecontract)
		(leadsto bankexit townsquare)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto fortexit valley)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto fortentrance fort)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item james candle)
		(wants-item arthur shinykey)
		(wants-item dorian bouquet)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(and (has jordan loveletter) (has jordan lovecontract) )
			(and (has james coin) (has james humanskull) (has james candle) )
		)

	)

)
