(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring humanskull bouquet candle coin silver knightsword ash - item
		 storage basement bar docks townarch townsquare valley fort shop cliff mansion bank forge junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit mansionentrance mansionexit bankexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna jordan avery roger peter - character
	)
	(:init
		(at roger mansion)
		(at silver bank)
		(at phillip fort)
		(at knightsword forge)
		(at bankentrance townsquare)
		(at dorian townarch)
		(at arthur valley)
		(at james valley)
		(at fortexit fort)
		(at mel storage)
		(at dave townsquare)
		(at rubyring shop)
		(at jordan mansion)
		(at basemententrance bar)
		(at forgeentrance townarch)
		(at bankexit bank)
		(at shopentrance townsquare)
		(at oscar bar)
		(at fortentrance valley)
		(at avery mansion)
		(at ian fort)
		(at mansionexit mansion)
		(at hutentrance townarch)
		(at basementexit basement)
		(at camille fort)
		(at barexit bar)
		(at humanskull cliff)
		(at bouquet mansion)
		(at barentrance docks)
		(at peter forge)
		(at karina townarch)
		(at giovanna shop)
		(at mansionentrance cliff)
		(at mel basement)
		(at mushroom cliff)
		(at frank townsquare)
		(at mel bar)
		(at shopexit shop)
		(closed forgeentrance)
		(closed hutentrance)
		(connected basement storage)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected docks townarch)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(has arthur knightshield)
		(has arthur rubyring)
		(has dorian lovecontract)
		(has arthur coin)
		(has arthur candle)
		(has arthur bucket)
		(has mel basementbucket)
		(has jordan loveletter)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto shopexit townsquare)
		(leadsto fortexit valley)
		(leadsto barentrance bar)
		(leadsto bankexit townsquare)
		(leadsto fortentrance fort)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian bouquet)
		(wants-item ian knightshield)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(wants-item arthur ash)
		(wants-item ian knightsword)
		(wants-item james coin)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur candle)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
