(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle rubyring ash coin - item
		 storage basement bar docks townarch townsquare cliff mansion valley shop junkyard fort hut forge bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit fortentrance - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger james - character
	)
	(:init
		(at shinykey bar)
		(at arthur townsquare)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at hutentrance townarch)
		(at basemententrance bar)
		(at candle mansion)
		(at oscar bar)
		(at barentrance docks)
		(at frank townsquare)
		(at dave townsquare)
		(at basementexit basement)
		(at jordan mansion)
		(at karina townarch)
		(at fortentrance valley)
		(at mel storage)
		(at rubyring shop)
		(at mel bar)
		(at avery mansion)
		(at james valley)
		(at barexit bar)
		(at dorian townarch)
		(at mansionexit mansion)
		(at mushroom docks)
		(at mel basement)
		(at forgeentrance townarch)
		(at mansionentrance cliff)
		(at roger mansion)
		(closed fortentrance)
		(closed hutentrance)
		(closed bankentrance)
		(closed basemententrance)
		(closed shopentrance)
		(closed forgeentrance)
		(connected townsquare townarch)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected basement storage)
		(connected valley townsquare)
		(connected townarch docks)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway townsquare valley)
		(has arthur humanskull)
		(has jordan lovecontract)
		(has mel basementbucket)
		(has dorian bouquet)
		(has jordan loveletter)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item dorian rubyring)
		(wants-item james coin)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur humanskull)
	)
	(:goal
		
		(and
			(and (has jordan loveletter) (has jordan lovecontract) )
			(has james coin) 
		)

	)

)
