(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle ash rubyring - item
		 storage basement bar docks townarch townsquare cliff mansion junkyard valley hut forge shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger - character
	)
	(:init
		(at shinykey bar)
		(at dave townsquare)
		(at arthur townarch)
		(at mansionentrance cliff)
		(at forgeentrance townarch)
		(at mansionexit mansion)
		(at barexit bar)
		(at karina townarch)
		(at basemententrance bar)
		(at basementexit basement)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at jordan mansion)
		(at dorian townarch)
		(at mel basement)
		(at mushroom docks)
		(at roger mansion)
		(at candle mansion)
		(at avery mansion)
		(at frank townsquare)
		(at hutentrance townarch)
		(at oscar bar)
		(at barentrance docks)
		(at mel storage)
		(at humanskull cliff)
		(at mel bar)
		(closed shopentrance)
		(closed hutentrance)
		(closed bankentrance)
		(closed forgeentrance)
		(closed basemententrance)
		(connected docks junkyard)
		(connected basement storage)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected storage basement)
		(connected townsquare cliff)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway storage basement)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has arthur bouquet)
		(has jordan loveletter)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto mansionexit cliff)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(wants-item dorian bouquet)
		(wants-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur bouquet)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
