(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle coin silver rubyring ash - item
		 storage basement bar docks townarch townsquare cliff mansion valley bank shop junkyard forge fort hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit fortentrance bankexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger james - character
	)
	(:init
		(at barentrance docks)
		(at bankexit bank)
		(at silver bank)
		(at hutentrance townarch)
		(at bankentrance townsquare)
		(at dave townsquare)
		(at basemententrance bar)
		(at oscar bar)
		(at candle mansion)
		(at frank townsquare)
		(at basementexit basement)
		(at shopentrance townsquare)
		(at mel basement)
		(at forgeentrance townarch)
		(at fortentrance valley)
		(at mel bar)
		(at avery mansion)
		(at arthur bank)
		(at rubyring shop)
		(at jordan mansion)
		(at james valley)
		(at dorian townarch)
		(at mansionexit mansion)
		(at mel storage)
		(at roger mansion)
		(at karina townarch)
		(at mansionentrance cliff)
		(at barexit bar)
		(closed fortentrance)
		(closed shopentrance)
		(closed hutentrance)
		(closed basemententrance)
		(closed forgeentrance)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected valley townsquare)
		(connected basement storage)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected townsquare valley)
		(connected storage basement)
		(connected docks townarch)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townsquare valley)
		(has jordan lovecontract)
		(has arthur mushroom)
		(has arthur humanskull)
		(has mel basementbucket)
		(has jordan loveletter)
		(has arthur coin)
		(has dorian bouquet)
		(leadsto bankexit townsquare)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto mansionexit cliff)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur ash)
		(wants-item james coin)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur humanskull)
	)
	(:goal
		
		(and
			(and (has jordan loveletter) (has jordan lovecontract) )
			(has james coin) 
		)

	)

)
