(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle ash rubyring - item
		 storage basement bar docks townarch townsquare cliff mansion junkyard valley forge shop hut bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger - character
	)
	(:init
		(at dave townsquare)
		(at frank townsquare)
		(at bankentrance townsquare)
		(at mansionexit mansion)
		(at avery mansion)
		(at shopentrance townsquare)
		(at candle mansion)
		(at arthur cliff)
		(at shinykey bar)
		(at roger mansion)
		(at forgeentrance townarch)
		(at mel storage)
		(at oscar bar)
		(at barexit bar)
		(at dorian townarch)
		(at jordan mansion)
		(at basemententrance bar)
		(at mushroom docks)
		(at humanskull cliff)
		(at mel basement)
		(at basementexit basement)
		(at mel bar)
		(at barentrance docks)
		(at karina townarch)
		(at mansionentrance cliff)
		(at hutentrance townarch)
		(closed forgeentrance)
		(closed basemententrance)
		(closed hutentrance)
		(closed bankentrance)
		(closed shopentrance)
		(connected basement storage)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare cliff)
		(connected docks junkyard)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(has jordan loveletter)
		(has dorian bouquet)
		(has mel basementbucket)
		(has arthur lovecontract)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		
			(and (has jordan loveletter) (has jordan lovecontract) )
		

	)

)
