(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle ash rubyring - item
		 storage basement bar docks townarch townsquare cliff mansion valley junkyard bank shop hut forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger - character
	)
	(:init
		(at mel basement)
		(at karina townarch)
		(at mansionentrance cliff)
		(at barexit bar)
		(at basemententrance bar)
		(at arthur townsquare)
		(at avery mansion)
		(at candle mansion)
		(at dorian townarch)
		(at shinykey bar)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at roger mansion)
		(at mansionexit mansion)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at basementexit basement)
		(at forgeentrance townarch)
		(at oscar bar)
		(at frank townsquare)
		(at mel bar)
		(at mel storage)
		(at mushroom docks)
		(at dave townsquare)
		(at jordan mansion)
		(at barentrance docks)
		(closed bankentrance)
		(closed shopentrance)
		(closed basemententrance)
		(closed forgeentrance)
		(closed hutentrance)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected basement storage)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected storage basement)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(has dorian bouquet)
		(has arthur lovecontract)
		(has mel basementbucket)
		(has jordan loveletter)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		
			(and (has jordan loveletter) (has jordan lovecontract) )
		

	)

)
