(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle coin silver bucket knightshield rubyring knightsword rope tastycupcake hairtonic book ash - item
		 storage basement bar docks townarch townsquare cliff mansion valley bank fort shop forge hut junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit fortentrance bankexit fortexit shopexit forgeexit hutexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger james ian camille phillip giovanna peter matthias michael - character
	)
	(:init
		(at mansionexit mansion)
		(at frank townsquare)
		(at basementexit basement)
		(at candle mansion)
		(at bucket fort)
		(at oscar bar)
		(at rope forge)
		(at barentrance docks)
		(at mel storage)
		(at basemententrance bar)
		(at bankentrance townsquare)
		(at shopentrance townsquare)
		(at jordan mansion)
		(at book hut)
		(at phillip fort)
		(at silver bank)
		(at michael hut)
		(at forgeentrance townarch)
		(at bankexit bank)
		(at matthias forge)
		(at camille fort)
		(at peter forge)
		(at arthur shop)
		(at dorian townarch)
		(at dave townsquare)
		(at avery mansion)
		(at fortentrance valley)
		(at tastycupcake hut)
		(at fortexit fort)
		(at hutentrance townarch)
		(at barexit bar)
		(at forgeexit forge)
		(at hutexit hut)
		(at james valley)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at roger mansion)
		(at rubyring shop)
		(at mel bar)
		(at ian fort)
		(at karina townarch)
		(at mel basement)
		(closed basemententrance)
		(connected townsquare valley)
		(connected storage basement)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected townarch docks)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(has arthur mushroom)
		(has ian knightsword)
		(has james coin)
		(has mel basementbucket)
		(has james humanskull)
		(has dorian bouquet)
		(has arthur hairtonic)
		(has ian knightshield)
		(has jordan lovecontract)
		(has jordan loveletter)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(leadsto bankexit townsquare)
		(leadsto forgeexit townarch)
		(leadsto fortentrance fort)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto fortexit valley)
		(leadsto shopexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto mansionexit cliff)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item james candle)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(and (has jordan loveletter) (has jordan lovecontract) )
			(and (has james coin) (has james humanskull) (has james candle) )
		)

	)

)
