(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book bucket humanskull bouquet candle mirror ash rubyring knightshield coin - item
		 storage basement bar docks townarch forge hut townsquare valley fort cliff mansion junkyard shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance fortentrance fortexit mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave james ian camille phillip jordan avery roger alli - character
	)
	(:init
		(at alli junkyard)
		(at james valley)
		(at tastycupcake townarch)
		(at basementexit basement)
		(at book hut)
		(at frank townsquare)
		(at barentrance docks)
		(at bankentrance townsquare)
		(at knightshield shop)
		(at candle mansion)
		(at shopentrance townsquare)
		(at bouquet cliff)
		(at tastycupcake hut)
		(at forgeexit forge)
		(at mushroom townarch)
		(at oscar bar)
		(at barexit bar)
		(at jordan mansion)
		(at rope townarch)
		(at mansionexit mansion)
		(at matthias forge)
		(at phillip fort)
		(at michael hut)
		(at fortexit fort)
		(at hutentrance townarch)
		(at mel storage)
		(at ian fort)
		(at mansionentrance cliff)
		(at karina townarch)
		(at knightsword forge)
		(at dorian townarch)
		(at rubyring shop)
		(at avery mansion)
		(at mirror junkyard)
		(at hairtonic townarch)
		(at fortentrance valley)
		(at hutexit hut)
		(at mel bar)
		(at roger mansion)
		(at bucket fort)
		(at humanskull cliff)
		(at camille fort)
		(at peter forge)
		(at knightsword townarch)
		(at dave townsquare)
		(at arthur valley)
		(at forgeentrance townarch)
		(at mel basement)
		(at basemententrance bar)
		(closed basemententrance)
		(closed bankentrance)
		(closed shopentrance)
		(connected storage basement)
		(connected townarch docks)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected docks junkyard)
		(connected townsquare valley)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway valley townsquare)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway townsquare valley)
		(has mel basementbucket)
		(has arthur shinykey)
		(has alli ash)
		(has arthur loveletter)
		(has dorian lovecontract)
		(leadsto fortentrance fort)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto fortexit valley)
		(leadsto barexit docks)
		(leadsto forgeexit townarch)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto mansionexit cliff)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item ian knightshield)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item alli tastycupcake)
		(wants-item ian knightsword)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(wants-item james coin)
		(wants-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

		)
	)

)
