(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book ash - item
		 storage basement bar docks townarch forge hut townsquare valley cliff mansion junkyard fort bank shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance fortentrance mansionentrance - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave james jordan - character
	)
	(:init
		(at hairtonic townarch)
		(at oscar bar)
		(at rope townarch)
		(at matthias forge)
		(at jordan mansion)
		(at mushroom townarch)
		(at barexit bar)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at tastycupcake townarch)
		(at basementexit basement)
		(at michael hut)
		(at book hut)
		(at peter forge)
		(at knightsword townarch)
		(at frank townsquare)
		(at barentrance docks)
		(at mel storage)
		(at arthur valley)
		(at james valley)
		(at forgeexit forge)
		(at mansionentrance cliff)
		(at fortentrance valley)
		(at karina townarch)
		(at dorian townarch)
		(at mel basement)
		(at mel bar)
		(at hutentrance townarch)
		(at basemententrance bar)
		(at dave townsquare)
		(at hutexit hut)
		(closed bankentrance)
		(closed basemententrance)
		(closed shopentrance)
		(closed fortentrance)
		(connected valley townsquare)
		(connected storage basement)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected basement storage)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected cliff townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(has arthur loveletter)
		(has mel basementbucket)
		(has arthur shinykey)
		(has dorian lovecontract)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto bankentrance bank)
		(leadsto hutexit townarch)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
