(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book bucket knightshield ash coin - item
		 storage basement bar docks townarch forge hut townsquare valley fort cliff mansion junkyard bank shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance fortentrance fortexit mansionentrance - entrance
		 arthur mel oscar dorian karina peter matthias michael frank dave james ian camille phillip jordan - character
	)
	(:init
		(at bucket fort)
		(at dorian townarch)
		(at arthur fort)
		(at fortexit fort)
		(at hutentrance townarch)
		(at james valley)
		(at karina townarch)
		(at forgeexit forge)
		(at michael hut)
		(at bankentrance townsquare)
		(at barexit bar)
		(at jordan mansion)
		(at knightsword townarch)
		(at oscar bar)
		(at shopentrance townsquare)
		(at mushroom townarch)
		(at matthias forge)
		(at rope townarch)
		(at basementexit basement)
		(at knightsword forge)
		(at camille fort)
		(at mansionentrance cliff)
		(at forgeentrance townarch)
		(at basemententrance bar)
		(at ian fort)
		(at frank townsquare)
		(at peter forge)
		(at mel bar)
		(at hutexit hut)
		(at mel basement)
		(at barentrance docks)
		(at mel storage)
		(at hairtonic townarch)
		(at phillip fort)
		(at tastycupcake townarch)
		(at dave townsquare)
		(at book hut)
		(at fortentrance valley)
		(closed bankentrance)
		(closed shopentrance)
		(closed basemententrance)
		(connected townsquare valley)
		(connected townarch docks)
		(connected storage basement)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected basement storage)
		(connected valley townsquare)
		(doorway valley townsquare)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has arthur shinykey)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto fortexit valley)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item james coin)
		(wants-item ian knightshield)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item ian knightsword)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
