(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightshield rubyring humanskull bouquet candle tastycupcake hairtonic - item
		 storage basement bar docks junkyard townarch townsquare shop valley cliff mansion hut fort bank forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance shopexit fortentrance mansionentrance mansionexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave giovanna james jordan avery roger - character
	)
	(:init
		(at roger mansion)
		(at avery mansion)
		(at arthur townarch)
		(at hutentrance townarch)
		(at james valley)
		(at knightshield shop)
		(at jordan mansion)
		(at dorian townarch)
		(at shopentrance townsquare)
		(at barexit bar)
		(at candle mansion)
		(at oscar bar)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at barentrance docks)
		(at tastycupcake hut)
		(at basemententrance bar)
		(at humanskull cliff)
		(at shinykey bar)
		(at karina townarch)
		(at shopexit shop)
		(at mel storage)
		(at frank townsquare)
		(at alli junkyard)
		(at mel bar)
		(at hutexit hut)
		(at rubyring shop)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at mel basement)
		(at dave townsquare)
		(at basementexit basement)
		(at fortentrance valley)
		(at mansionexit mansion)
		(closed fortentrance)
		(closed basemententrance)
		(closed hutentrance)
		(closed shopentrance)
		(closed forgeentrance)
		(closed bankentrance)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected basement storage)
		(connected storage basement)
		(connected docks junkyard)
		(connected valley townsquare)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected docks townarch)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townsquare townarch)
		(doorway storage basement)
		(doorway cliff townsquare)
		(has arthur mirror)
		(has jordan loveletter)
		(has arthur mushroom)
		(has dorian lovecontract)
		(has dorian bouquet)
		(has mel basementbucket)
		(has alli ash)
		(leadsto mansionexit cliff)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item giovanna hairtonic)
		(wants-item alli tastycupcake)
		(wants-item jordan lovecontract)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
