(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightshield rubyring humanskull bouquet candle tastycupcake hairtonic book knightsword rope - item
		 storage basement bar docks junkyard townarch townsquare shop valley cliff mansion hut forge fort bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance shopexit fortentrance mansionentrance mansionexit hutexit forgeexit - entrance
		 arthur mel oscar alli dorian karina frank dave giovanna james jordan avery roger michael peter matthias - character
	)
	(:init
		(at james valley)
		(at peter forge)
		(at bankentrance townsquare)
		(at forgeentrance townarch)
		(at basemententrance bar)
		(at forgeexit forge)
		(at oscar bar)
		(at rope forge)
		(at mel storage)
		(at candle mansion)
		(at book hut)
		(at jordan mansion)
		(at barexit bar)
		(at michael hut)
		(at shinykey bar)
		(at frank townsquare)
		(at matthias forge)
		(at shopentrance townsquare)
		(at basementexit basement)
		(at mel basement)
		(at fortentrance valley)
		(at rubyring shop)
		(at mansionexit mansion)
		(at dorian townarch)
		(at mel bar)
		(at hutexit hut)
		(at alli junkyard)
		(at hutentrance townarch)
		(at knightshield shop)
		(at knightsword forge)
		(at humanskull cliff)
		(at barentrance docks)
		(at roger mansion)
		(at karina townarch)
		(at giovanna shop)
		(at mansionentrance cliff)
		(at shopexit shop)
		(at arthur townarch)
		(at avery mansion)
		(at dave townsquare)
		(closed basemententrance)
		(closed forgeentrance)
		(closed bankentrance)
		(closed fortentrance)
		(closed hutentrance)
		(closed shopentrance)
		(connected storage basement)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected basement storage)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected townarch docks)
		(connected docks townarch)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(doorway junkyard docks)
		(has arthur ash)
		(has arthur mirror)
		(has mel basementbucket)
		(has alli tastycupcake)
		(has arthur mushroom)
		(has jordan lovecontract)
		(has dorian bouquet)
		(has arthur hairtonic)
		(has jordan loveletter)
		(leadsto barentrance bar)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto forgeexit townarch)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(wants-item giovanna hairtonic)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
