(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightshield rubyring humanskull bouquet candle tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch townsquare shop valley cliff mansion hut forge fort bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance shopexit fortentrance mansionentrance mansionexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave giovanna james jordan avery roger michael - character
	)
	(:init
		(at roger mansion)
		(at dorian townarch)
		(at arthur junkyard)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at james valley)
		(at bankentrance townsquare)
		(at barexit bar)
		(at barentrance docks)
		(at knightshield shop)
		(at mansionexit mansion)
		(at candle mansion)
		(at oscar bar)
		(at jordan mansion)
		(at dave townsquare)
		(at michael hut)
		(at mel storage)
		(at shinykey bar)
		(at karina townarch)
		(at rubyring shop)
		(at basemententrance bar)
		(at alli junkyard)
		(at mel basement)
		(at mel bar)
		(at hutexit hut)
		(at frank townsquare)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at avery mansion)
		(at basementexit basement)
		(at fortentrance valley)
		(at book hut)
		(at shopexit shop)
		(closed bankentrance)
		(closed basemententrance)
		(closed shopentrance)
		(closed fortentrance)
		(closed forgeentrance)
		(connected storage basement)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected basement storage)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected docks townarch)
		(doorway junkyard docks)
		(doorway townsquare townarch)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway cliff townsquare)
		(has dorian bouquet)
		(has mel basementbucket)
		(has jordan loveletter)
		(has arthur mirror)
		(has arthur hairtonic)
		(has arthur mushroom)
		(has jordan lovecontract)
		(has alli ash)
		(has alli tastycupcake)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto fortentrance fort)
		(leadsto mansionexit cliff)
		(leadsto basemententrance basement)
		(leadsto shopentrance shop)
		(leadsto shopexit townsquare)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item giovanna hairtonic)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
