(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina frank dave michael peter matthias giovanna james ian camille phillip jordan avery roger - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring bucket humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch townsquare hut forge bank shop valley fort cliff mansion - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance hutexit forgeexit bankexit shopexit fortentrance fortexit mansionentrance mansionexit - entrance
	)
	(:init
		(at alli junkyard)
		(at mushroom docks)
		(at karina townarch)
		(at roger mansion)
		(at rubyring shop)
		(at avery mansion)
		(at book docks)
		(at ian fort)
		(at ash townsquare)
		(at mel basement)
		(at mel bar)
		(at hairtonic docks)
		(at shopexit shop)
		(at arthur bar)
		(at giovanna shop)
		(at mansionentrance cliff)
		(at dorian townarch)
		(at dave townsquare)
		(at basemententrance bar)
		(at peter forge)
		(at camille fort)
		(at rope forge)
		(at bucket fort)
		(at barentrance docks)
		(at mel storage)
		(at hutentrance townarch)
		(at fortexit fort)
		(at james valley)
		(at knightsword forge)
		(at frank townsquare)
		(at basementexit basement)
		(at michael hut)
		(at mirror docks)
		(at barexit bar)
		(at bankexit bank)
		(at forgeexit forge)
		(at mansionexit mansion)
		(at knightshield shop)
		(at jordan mansion)
		(at silver bank)
		(at phillip fort)
		(at bankentrance townsquare)
		(at shopentrance townsquare)
		(at matthias forge)
		(at oscar bar)
		(at forgeentrance townarch)
		(at fortentrance valley)
		(at hutexit hut)
		(closed basemententrance)
		(connected basement storage)
		(connected townarch townsquare)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected junkyard docks)
		(connected storage basement)
		(connected townsquare cliff)
		(doorway valley townsquare)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(has james candle)
		(has mel basementbucket)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has dorian bouquet)
		(has alli tastycupcake)
		(has james coin)
		(has james humanskull)
		(leadsto mansionentrance mansion)
		(leadsto fortexit valley)
		(leadsto hutexit townarch)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto mansionexit cliff)
		(leadsto bankentrance bank)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto hutentrance hut)
		(leadsto forgeexit townarch)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item ian knightshield)
		(wants-item ian knightsword)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur ash)
		(has james coin)
		(has james humanskull)
		(has ian knightsword)
		(has ian knightshield)
		(has james candle)
		(has jordan lovecontract)
	  )
	)
)
