(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina frank dave michael peter matthias - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope - item
		 storage basement bar docks junkyard townarch townsquare hut forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance hutexit forgeexit - entrance
	)
	(:init
		(at book docks)
		(at barentrance docks)
		(at mushroom docks)
		(at hutentrance townarch)
		(at jordan mansion)
		(at barexit bar)
		(at dorian townarch)
		(at alli junkyard)
		(at mansionentrance cliff)
		(at hairtonic docks)
		(at mel basement)
		(at mel bar)
		(at mel storage)
		(at karina townarch)
		(at hutexit hut)
		(at knightsword forge)
		(at peter forge)
		(at dave townsquare)
		(at frank townsquare)
		(at basementexit basement)
		(at forgeexit forge)
		(at oscar bar)
		(at basemententrance bar)
		(at rope forge)
		(at arthur townsquare)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at michael hut)
		(at matthias forge)
		(at mirror docks)
		(at bankentrance townsquare)
		(closed basemententrance)
		(closed bankentrance)
		(closed shopentrance)
		(connected townarch townsquare)
		(connected basement storage)
		(connected townarch docks)
		(connected docks townarch)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected junkyard docks)
		(connected townsquare valley)
		(connected storage basement)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(has mel basementbucket)
		(has arthur ash)
		(has alli tastycupcake)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has arthur shinykey)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto forgeexit townarch)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur ash)
	  )
	)
)
