(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle bucket - item
		 storage basement bar docks junkyard townarch forge hut townsquare bank shop cliff mansion valley fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit fortentrance fortexit - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan avery roger james ian camille phillip - character
	)
	(:init
		(at alli junkyard)
		(at fortexit fort)
		(at james valley)
		(at basementexit basement)
		(at peter forge)
		(at michael hut)
		(at book hut)
		(at fortentrance valley)
		(at barexit bar)
		(at jordan mansion)
		(at phillip fort)
		(at knightshield shop)
		(at oscar bar)
		(at tastycupcake hut)
		(at matthias forge)
		(at silver bank)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at mushroom townarch)
		(at mansionexit mansion)
		(at hutentrance townarch)
		(at camille fort)
		(at dorian townarch)
		(at mel storage)
		(at frank townsquare)
		(at knightsword townsquare)
		(at roger mansion)
		(at avery mansion)
		(at knightsword forge)
		(at ian fort)
		(at mirror townarch)
		(at karina townarch)
		(at rope forge)
		(at mel basement)
		(at hutexit hut)
		(at candle townsquare)
		(at mansionentrance cliff)
		(at forgeexit forge)
		(at mel bar)
		(at basemententrance bar)
		(at dave townsquare)
		(at rubyring townsquare)
		(at bucket fort)
		(at giovanna shop)
		(at forgeentrance townarch)
		(at shopexit shop)
		(at barentrance docks)
		(closed basemententrance)
		(closed barentrance)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected storage basement)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected townsquare valley)
		(connected docks townarch)
		(connected docks junkyard)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected basement storage)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(has james coin)
		(has arthur humanskull)
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has jordan lovecontract)
		(has alli ash)
		(has mel basementbucket)
		(has dorian bouquet)
		(leadsto bankexit townsquare)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto fortexit valley)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item james humanskull)
		(wants-item ian knightsword)
		(wants-item ian knightshield)
		(wants-item arthur ash)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur humanskull)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

		)
	)

)
