(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring - item
		 storage basement bar docks junkyard townarch forge hut townsquare bank shop cliff mansion valley - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit mansionentrance - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan - character
	)
	(:init
		(at basementexit basement)
		(at rubyring shop)
		(at tastycupcake hut)
		(at mushroom townarch)
		(at bankexit bank)
		(at rope forge)
		(at matthias forge)
		(at bankentrance townsquare)
		(at shopentrance townsquare)
		(at arthur townsquare)
		(at jordan mansion)
		(at oscar bar)
		(at barexit bar)
		(at basemententrance bar)
		(at forgeentrance townarch)
		(at forgeexit forge)
		(at frank townsquare)
		(at mel storage)
		(at mirror townarch)
		(at book hut)
		(at peter forge)
		(at mel basement)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at mel bar)
		(at alli junkyard)
		(at dave townsquare)
		(at knightshield shop)
		(at barentrance docks)
		(at karina townarch)
		(at shopexit shop)
		(at michael hut)
		(at silver bank)
		(at dorian townarch)
		(at hutentrance townarch)
		(at coin bank)
		(at hutexit hut)
		(closed barentrance)
		(closed basemententrance)
		(connected townsquare townarch)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected storage basement)
		(connected basement storage)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected docks junkyard)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway junkyard docks)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway basement storage)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur knightsword)
		(has alli ash)
		(has arthur loveletter)
		(has giovanna hairtonic)
		(leadsto shopentrance shop)
		(leadsto bankexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto basementexit bar)
		(leadsto forgeexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has jordan loveletter) 
		)

	)

)
