(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle bucket - item
		 storage basement bar docks junkyard townarch forge hut townsquare bank shop cliff mansion valley fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit fortentrance fortexit - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan avery roger james ian camille phillip - character
	)
	(:init
		(at roger mansion)
		(at james valley)
		(at dorian townarch)
		(at michael hut)
		(at book hut)
		(at hutentrance townarch)
		(at fortexit fort)
		(at bankentrance townsquare)
		(at silver bank)
		(at humanskull townsquare)
		(at mansionexit mansion)
		(at arthur valley)
		(at matthias forge)
		(at barentrance docks)
		(at bankexit bank)
		(at mushroom townarch)
		(at shopentrance townsquare)
		(at phillip fort)
		(at jordan mansion)
		(at oscar bar)
		(at fortentrance valley)
		(at tastycupcake hut)
		(at barexit bar)
		(at knightshield shop)
		(at basementexit basement)
		(at knightsword forge)
		(at bucket fort)
		(at alli junkyard)
		(at karina townarch)
		(at knightsword townsquare)
		(at mirror townarch)
		(at avery mansion)
		(at frank townsquare)
		(at ian fort)
		(at forgeexit forge)
		(at mel storage)
		(at mel basement)
		(at hutexit hut)
		(at candle townsquare)
		(at mansionentrance cliff)
		(at shopexit shop)
		(at forgeentrance townarch)
		(at giovanna shop)
		(at dave townsquare)
		(at basemententrance bar)
		(at peter forge)
		(at camille fort)
		(at rope forge)
		(at mel bar)
		(at rubyring townsquare)
		(closed basemententrance)
		(closed barentrance)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected townarch docks)
		(connected junkyard docks)
		(connected storage basement)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected townsquare cliff)
		(connected basement storage)
		(connected cliff townsquare)
		(connected docks townarch)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(has jordan loveletter)
		(has jordan lovecontract)
		(has alli ash)
		(has dorian bouquet)
		(has james coin)
		(leadsto barentrance bar)
		(leadsto bankentrance bank)
		(leadsto hutexit townarch)
		(leadsto bankexit townsquare)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto fortexit valley)
		(leadsto forgeexit townarch)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto shopexit townsquare)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item ian knightshield)
		(wants-item arthur ash)
		(wants-item ian knightsword)
		(wants-item james humanskull)
		(wants-item arthur shinykey)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

		)
	)

)
