(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch forge hut townsquare bank shop cliff mansion valley - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan avery roger - character
	)
	(:init
		(at forgeexit forge)
		(at basementexit basement)
		(at coin bank)
		(at rope forge)
		(at oscar bar)
		(at mel storage)
		(at barentrance docks)
		(at candle mansion)
		(at bankentrance townsquare)
		(at basemententrance bar)
		(at arthur mansion)
		(at book hut)
		(at jordan mansion)
		(at bouquet cliff)
		(at mushroom townarch)
		(at shopexit shop)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at matthias forge)
		(at dave townsquare)
		(at peter forge)
		(at mel bar)
		(at humanskull cliff)
		(at knightshield shop)
		(at dorian townarch)
		(at alli junkyard)
		(at michael hut)
		(at barexit bar)
		(at roger mansion)
		(at karina townarch)
		(at tastycupcake hut)
		(at mansionexit mansion)
		(at hutentrance townarch)
		(at mansionentrance cliff)
		(at rubyring shop)
		(at frank townsquare)
		(at mel basement)
		(at avery mansion)
		(at silver bank)
		(at hutexit hut)
		(at mirror townarch)
		(at giovanna shop)
		(closed basemententrance)
		(closed barentrance)
		(connected storage basement)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected townarch docks)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected basement storage)
		(connected cliff townsquare)
		(connected junkyard docks)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(has giovanna hairtonic)
		(has alli ash)
		(has arthur knightsword)
		(has jordan loveletter)
		(has dorian lovecontract)
		(has mel basementbucket)
		(leadsto bankexit townsquare)
		(leadsto hutexit townarch)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item dorian bouquet)
		(wants-item jordan lovecontract)
		(wants-item arthur lovecontract)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has jordan loveletter) 
		)

	)

)
