(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch forge hut townsquare bank shop cliff mansion valley - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan avery roger - character
	)
	(:init
		(at karina townarch)
		(at dave townsquare)
		(at book hut)
		(at michael hut)
		(at dorian townarch)
		(at mushroom townarch)
		(at matthias forge)
		(at barexit bar)
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at silver bank)
		(at oscar bar)
		(at tastycupcake hut)
		(at arthur townsquare)
		(at bankentrance townsquare)
		(at jordan mansion)
		(at frank townsquare)
		(at coin bank)
		(at rope forge)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at mirror townarch)
		(at alli junkyard)
		(at roger mansion)
		(at giovanna shop)
		(at mel storage)
		(at knightshield shop)
		(at barentrance docks)
		(at mansionexit mansion)
		(at mel bar)
		(at hutexit hut)
		(at avery mansion)
		(at basemententrance bar)
		(at peter forge)
		(at basementexit basement)
		(at forgeexit forge)
		(at mel basement)
		(closed barentrance)
		(closed basemententrance)
		(connected storage basement)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected junkyard docks)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected basement storage)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(has arthur rubyring)
		(has arthur humanskull)
		(has dorian bouquet)
		(has jordan lovecontract)
		(has arthur candle)
		(has arthur knightsword)
		(has mel basementbucket)
		(has alli ash)
		(has jordan loveletter)
		(has giovanna hairtonic)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto shopexit townsquare)
		(leadsto barentrance bar)
		(leadsto mansionexit cliff)
		(leadsto basementexit bar)
		(leadsto hutexit townarch)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur humanskull)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur candle)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
