(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle mirror ash rubyring tastycupcake coin - item
		 storage basement bar docks townarch townsquare valley cliff mansion junkyard shop hut fort forge bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance mansionexit hutexit - entrance
		 arthur mel oscar dorian karina frank dave james jordan avery roger alli - character
	)
	(:init
		(at rubyring shop)
		(at humanskull cliff)
		(at dorian townarch)
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at james valley)
		(at shopentrance townsquare)
		(at frank townsquare)
		(at basemententrance bar)
		(at mel storage)
		(at oscar bar)
		(at dave townsquare)
		(at fortentrance valley)
		(at basementexit basement)
		(at candle mansion)
		(at bankentrance townsquare)
		(at barentrance docks)
		(at karina townarch)
		(at mansionexit mansion)
		(at hutexit hut)
		(at mel bar)
		(at mel basement)
		(at roger mansion)
		(at barexit bar)
		(at avery mansion)
		(at jordan mansion)
		(at mansionentrance cliff)
		(at arthur townarch)
		(at tastycupcake hut)
		(at alli junkyard)
		(closed hutentrance)
		(closed shopentrance)
		(closed forgeentrance)
		(closed fortentrance)
		(closed bankentrance)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townarch docks)
		(connected docks junkyard)
		(connected townarch townsquare)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway townarch townsquare)
		(has arthur mirror)
		(has dorian bouquet)
		(has mel basementbucket)
		(has jordan loveletter)
		(has arthur mushroom)
		(has alli ash)
		(has arthur shinykey)
		(has arthur lovecontract)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur ash)
		(wants-item alli tastycupcake)
		(wants-item arthur shinykey)
		(wants-item james coin)
		(wants-item jordan lovecontract)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
			(has james coin) 
		)

	)

)
