(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter mirror ash tastycupcake hairtonic book knightsword rope coin - item
		 storage basement bar docks townarch townsquare valley junkyard hut forge mansion cliff fort shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance hutexit forgeexit mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave james alli michael peter matthias jordan - character
	)
	(:init
		(at dave townsquare)
		(at basementexit basement)
		(at bankentrance townsquare)
		(at peter forge)
		(at mansionentrance cliff)
		(at shopentrance townsquare)
		(at matthias forge)
		(at book hut)
		(at mirror hut)
		(at mushroom hut)
		(at oscar bar)
		(at forgeexit forge)
		(at rope forge)
		(at basemententrance bar)
		(at hairtonic hut)
		(at mel storage)
		(at barentrance docks)
		(at hutexit hut)
		(at dorian townarch)
		(at karina townarch)
		(at hutentrance townarch)
		(at jordan mansion)
		(at michael hut)
		(at james valley)
		(at knightsword forge)
		(at barexit bar)
		(at arthur townarch)
		(at alli junkyard)
		(at frank townsquare)
		(at fortentrance valley)
		(at forgeentrance townarch)
		(at mel bar)
		(at mel basement)
		(closed basemententrance)
		(closed bankentrance)
		(closed fortentrance)
		(closed shopentrance)
		(connected valley townsquare)
		(connected storage basement)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected basement storage)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected townarch docks)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(doorway townarch docks)
		(has mel basementbucket)
		(has arthur tastycupcake)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has arthur shinykey)
		(has alli ash)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto fortentrance fort)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto shopentrance shop)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item alli tastycupcake)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item james coin)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur tastycupcake)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
