(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter mirror ash tastycupcake coin - item
		 storage basement bar docks townarch townsquare valley junkyard mansion hut cliff bank fort shop forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance hutexit mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave james alli jordan - character
	)
	(:init
		(at jordan mansion)
		(at bankentrance townsquare)
		(at frank townsquare)
		(at james valley)
		(at dorian townarch)
		(at basemententrance bar)
		(at barentrance docks)
		(at oscar bar)
		(at fortentrance valley)
		(at basementexit basement)
		(at dave townsquare)
		(at forgeentrance townarch)
		(at hutentrance townarch)
		(at tastycupcake hut)
		(at mansionentrance cliff)
		(at karina townarch)
		(at hutexit hut)
		(at mel bar)
		(at alli junkyard)
		(at arthur docks)
		(at shopentrance townsquare)
		(at barexit bar)
		(at mel storage)
		(at mel basement)
		(closed hutentrance)
		(closed shopentrance)
		(closed fortentrance)
		(closed forgeentrance)
		(closed bankentrance)
		(closed basemententrance)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected townarch docks)
		(connected basement storage)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected storage basement)
		(connected cliff townsquare)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(has arthur loveletter)
		(has arthur mirror)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has alli ash)
		(has arthur mushroom)
		(has arthur shinykey)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto fortentrance fort)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item alli tastycupcake)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item james coin)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
