(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter ash - item
		 storage basement bar docks townarch townsquare mansion cliff junkyard valley shop bank hut forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave jordan - character
	)
	(:init
		(at arthur townsquare)
		(at dorian townarch)
		(at barexit bar)
		(at forgeentrance townarch)
		(at mansionentrance cliff)
		(at karina townarch)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at basementexit basement)
		(at mel bar)
		(at hutentrance townarch)
		(at dave townsquare)
		(at frank townsquare)
		(at jordan mansion)
		(at oscar bar)
		(at basemententrance bar)
		(at mel storage)
		(at mel basement)
		(at barentrance docks)
		(closed forgeentrance)
		(closed hutentrance)
		(closed bankentrance)
		(closed basemententrance)
		(closed shopentrance)
		(connected basement storage)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected storage basement)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected townsquare cliff)
		(doorway townsquare townarch)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway basement storage)
		(has arthur shinykey)
		(has arthur loveletter)
		(has arthur mushroom)
		(has dorian lovecontract)
		(has mel basementbucket)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
