(move-through-entrance arthur shop shopexit townsquare)
(close arthur shopentrance townsquare)
(move-through-door arthur townsquare towngate townarch)
(open arthur hutentrance townarch )
(open arthur forgeentrance townarch )
(move-through-entrance arthur townarch forgeentrance forge )
(move-through-entrance arthur forge forgeexit townarch )
(move-through-door arthur townarch towngate townsquare )
(move-through-entrance arthur townsquare bankentrance bank)
(move-through-entrance arthur bank bankexit townsquare )
(open arthur shopentrance townsquare )
(move-through-entrance arthur townsquare shopentrance shop )
(move-through-entrance arthur shop shopexit townsquare)
(move-through-doorway arthur townsquare cliff)
(move-through-entrance arthur cliff mansionentrance mansion)
(give arthur loveletter jordan mansion)
