(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance mansionentrance mansionexit fortentrance fortexit - entrance
		 storage basement bar docks junkyard townarch forge hut townsquare cliff mansion valley fort shop bank - location
		 arthur mel oscar alli dorian karina peter matthias michael frank dave jordan avery roger james ian camille phillip - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book humanskull bouquet candle bucket rubyring knightshield coin - item
	)
	(:init
		(at phillip fort)
		(at ian fort)
		(at knightsword forge)
		(at james valley)
		(at peter forge)
		(at mel storage)
		(at humanskull cliff)
		(at mel basement)
		(at mel bar)
		(at mushroom docks)
		(at alli junkyard)
		(at mansionentrance cliff)
		(at barentrance docks)
		(at dave townsquare)
		(at basemententrance bar)
		(at rope forge)
		(at hutentrance townarch)
		(at karina townarch)
		(at roger mansion)
		(at bucket fort)
		(at rubyring shop)
		(at hairtonic hut)
		(at avery mansion)
		(at camille fort)
		(at michael hut)
		(at frank townsquare)
		(at basementexit basement)
		(at mirror docks)
		(at dorian townarch)
		(at hutexit hut)
		(at fortexit fort)
		(at forgeentrance townarch)
		(at knightshield shop)
		(at arthur townsquare)
		(at bankentrance townsquare)
		(at barexit bar)
		(at mansionexit mansion)
		(at oscar bar)
		(at candle mansion)
		(at fortentrance valley)
		(at book hut)
		(at forgeexit forge)
		(at matthias forge)
		(at jordan mansion)
		(at shopentrance townsquare)
		(closed bankentrance)
		(closed basemententrance)
		(closed shopentrance)
		(connected docks townarch)
		(connected junkyard docks)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected valley townsquare)
		(connected townarch townsquare)
		(connected basement storage)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected storage basement)
		(connected townsquare townarch)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(has jordan loveletter)
		(has mel basementbucket)
		(has ian knightsword)
		(has arthur bouquet)
		(has dorian lovecontract)
		(has arthur ash)
		(has alli tastycupcake)
		(leadsto fortexit valley)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian bouquet)
		(wants-item ian knightshield)
		(wants-item arthur shinykey)
		(wants-item dorian rubyring)
		(wants-item james coin)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

		)
	)

)
