(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter coin silver humanskull bouquet candle rubyring ash - item
		 storage basement bar docks townarch townsquare bank cliff mansion shop valley junkyard forge hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger - character
	)
	(:init
		(at jordan mansion)
		(at oscar bar)
		(at dorian townarch)
		(at bouquet cliff)
		(at arthur townsquare)
		(at humanskull cliff)
		(at candle mansion)
		(at basementexit basement)
		(at dave townsquare)
		(at hutentrance townarch)
		(at basemententrance bar)
		(at frank townsquare)
		(at mansionexit mansion)
		(at bankentrance townsquare)
		(at roger mansion)
		(at karina townarch)
		(at mel basement)
		(at mansionentrance cliff)
		(at mel bar)
		(at barentrance docks)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at avery mansion)
		(at rubyring shop)
		(at barexit bar)
		(at mel storage)
		(closed shopentrance)
		(closed basemententrance)
		(closed forgeentrance)
		(closed hutentrance)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected storage basement)
		(connected townsquare valley)
		(connected cliff townsquare)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has arthur coin)
		(has arthur mushroom)
		(has arthur silver)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto bankexit townsquare)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan lovecontract)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur coin)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
