(move-through-entrance arthur cliff mansionentrance mansion)
(give arthur loveletter jordan mansion)
(move-through-entrance arthur mansion mansionexit cliff)
(close arthur mansionentrance cliff)
(move-through-doorway arthur cliff townsquare)
(move-through-door arthur townsquare towngate townarch)
(move-through-doorway arthur townarch docks)
(move-through-doorway arthur docks townarch )
(move-through-door arthur townarch towngate townsquare )
(move-through-doorway arthur townsquare cliff )
(drop arthur bouquet cliff)
(pickup arthur bouquet cliff )
(open arthur mansionentrance cliff )
(move-through-entrance arthur cliff mansionentrance mansion )
(move-through-entrance arthur mansion mansionexit cliff )
