(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope knightshield rubyring humanskull bouquet candle bucket mirror ash coin - item
		 storage basement bar docks townarch hut forge townsquare shop cliff mansion valley fort junkyard bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance shopexit mansionentrance mansionexit fortentrance fortexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave giovanna jordan avery roger james ian camille phillip alli - character
	)
	(:init
		(at roger mansion)
		(at dave townsquare)
		(at mel storage)
		(at michael hut)
		(at dorian townarch)
		(at hutentrance townarch)
		(at fortexit fort)
		(at matthias forge)
		(at barexit bar)
		(at book townarch)
		(at james valley)
		(at tastycupcake hut)
		(at phillip fort)
		(at candle mansion)
		(at bankentrance townsquare)
		(at jordan mansion)
		(at mushroom forge)
		(at barentrance docks)
		(at bouquet cliff)
		(at oscar bar)
		(at mansionexit mansion)
		(at shopentrance townsquare)
		(at tastycupcake forge)
		(at humanskull cliff)
		(at forgeexit forge)
		(at alli junkyard)
		(at shopexit shop)
		(at karina townarch)
		(at ian fort)
		(at avery mansion)
		(at frank townsquare)
		(at arthur townarch)
		(at mel bar)
		(at basemententrance bar)
		(at fortentrance valley)
		(at hutexit hut)
		(at hairtonic townarch)
		(at mansionentrance cliff)
		(at mel basement)
		(at forgeentrance townarch)
		(at knightsword forge)
		(at camille fort)
		(at rope shop)
		(at basementexit basement)
		(at peter forge)
		(at giovanna shop)
		(at mirror junkyard)
		(closed bankentrance)
		(closed basemententrance)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected storage basement)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected valley townsquare)
		(connected junkyard docks)
		(connected basement storage)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway valley townsquare)
		(doorway townarch docks)
		(has arthur rubyring)
		(has alli ash)
		(has dorian lovecontract)
		(has ian knightshield)
		(has arthur loveletter)
		(has ian knightsword)
		(has mel basementbucket)
		(has arthur shinykey)
		(has arthur bucket)
		(leadsto mansionexit cliff)
		(leadsto fortexit valley)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto forgeexit townarch)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto fortentrance fort)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto hutexit townarch)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item james coin)
		(wants-item alli tastycupcake)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur rubyring)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

		)
	)

)
