(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina michael peter matthias alli - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope mirror ash - item
		 storage basement bar docks townarch hut forge junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit - entrance
	)
	(:init
		(at mel storage)
		(at mel basement)
		(at mansionentrance cliff)
		(at basemententrance bar)
		(at oscar bar)
		(at peter forge)
		(at barentrance docks)
		(at michael hut)
		(at matthias forge)
		(at arthur docks)
		(at forgeentrance townarch)
		(at mushroom junkyard)
		(at mel bar)
		(at karina townarch)
		(at barexit bar)
		(at rope forge)
		(at forgeexit forge)
		(at alli junkyard)
		(at dorian townarch)
		(at tastycupcake hut)
		(at hutentrance townarch)
		(at hutexit hut)
		(at jordan mansion)
		(at basementexit basement)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected storage basement)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected docks townarch)
		(connected townarch docks)
		(connected docks junkyard)
		(connected basement storage)
		(doorway storage basement)
		(doorway junkyard docks)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(has arthur book)
		(has arthur loveletter)
		(has arthur ash)
		(has arthur mirror)
		(has alli tastycupcake)
		(has arthur knightsword)
		(has dorian lovecontract)
		(has arthur hairtonic)
		(has arthur shinykey)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto forgeexit townarch)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur book)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has alli tastycupcake)
		(has arthur ash)
	  )
	)
)
