(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina michael peter matthias alli - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope mirror ash - item
		 storage basement bar docks townarch hut forge junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit - entrance
	)
	(:init
		(at basemententrance bar)
		(at mushroom junkyard)
		(at mel bar)
		(at jordan mansion)
		(at basementexit basement)
		(at mel basement)
		(at hutentrance townarch)
		(at barentrance docks)
		(at mansionentrance cliff)
		(at matthias forge)
		(at mel storage)
		(at michael hut)
		(at oscar bar)
		(at peter forge)
		(at karina townarch)
		(at arthur bar)
		(at alli junkyard)
		(at hutexit hut)
		(at dorian townarch)
		(at barexit bar)
		(at rope forge)
		(at forgeexit forge)
		(at forgeentrance townarch)
		(at tastycupcake hut)
		(connected basement storage)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected storage basement)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townarch docks)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townarch docks)
		(has arthur shinykey)
		(has arthur hairtonic)
		(has arthur mirror)
		(has mel basementbucket)
		(has arthur book)
		(has arthur ash)
		(has alli tastycupcake)
		(has dorian lovecontract)
		(has arthur knightsword)
		(has arthur loveletter)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto forgeexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has alli tastycupcake)
		(has arthur ash)
	  )
	)
)
