(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit fortexit shopexit hutexit - entrance
		 storage basement bar docks townarch forge junkyard townsquare valley cliff mansion fort shop hut bank - location
		 arthur mel oscar dorian karina peter matthias alli frank dave james jordan avery roger ian camille phillip giovanna michael - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope mirror ash humanskull bouquet candle bucket knightshield rubyring tastycupcake hairtonic book coin - item
	)
	(:init
		(at mel bar)
		(at book hut)
		(at frank townsquare)
		(at ash junkyard)
		(at matthias forge)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at camille fort)
		(at dave townsquare)
		(at oscar bar)
		(at candle mansion)
		(at dorian townarch)
		(at basementexit basement)
		(at basemententrance bar)
		(at barexit bar)
		(at fortexit fort)
		(at jordan mansion)
		(at michael hut)
		(at hutentrance townarch)
		(at mirror junkyard)
		(at phillip fort)
		(at arthur cliff)
		(at bankentrance townsquare)
		(at rope townsquare)
		(at hutexit hut)
		(at fortentrance valley)
		(at avery mansion)
		(at mel basement)
		(at mushroom townsquare)
		(at knightshield shop)
		(at barentrance docks)
		(at shopexit shop)
		(at peter forge)
		(at mansionexit mansion)
		(at forgeexit forge)
		(at humanskull cliff)
		(at roger mansion)
		(at bucket fort)
		(at karina townarch)
		(at mel storage)
		(at ian fort)
		(at alli junkyard)
		(at mansionentrance cliff)
		(at james valley)
		(at giovanna shop)
		(closed bankentrance)
		(closed basemententrance)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected storage basement)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected basement storage)
		(connected junkyard docks)
		(connected docks junkyard)
		(connected valley townsquare)
		(connected cliff townsquare)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway townarch docks)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(has alli tastycupcake)
		(has arthur shinykey)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has arthur knightsword)
		(has arthur bouquet)
		(has arthur rubyring)
		(leadsto barentrance bar)
		(leadsto bankentrance bank)
		(leadsto barexit docks)
		(leadsto forgeexit townarch)
		(leadsto hutexit townarch)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto fortexit valley)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto fortentrance fort)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item james coin)
		(wants-item jordan loveletter)
		(wants-item jordan lovecontract)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur rubyring)
	)
	(:goal
		(or
			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

		)
	)

)
