(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina michael peter matthias frank dave giovanna jordan avery roger james ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope knightshield rubyring humanskull bouquet candle bucket - item
		 storage basement bar docks townarch hut forge townsquare shop cliff mansion valley fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance shopexit mansionentrance mansionexit fortentrance fortexit - entrance
	)
	(:init
		(at mansionexit mansion)
		(at arthur valley)
		(at avery mansion)
		(at tastycupcake forge)
		(at fortentrance valley)
		(at knightshield shop)
		(at rope shop)
		(at humanskull cliff)
		(at shopexit shop)
		(at james valley)
		(at forgeexit forge)
		(at phillip fort)
		(at mel basement)
		(at giovanna shop)
		(at roger mansion)
		(at karina townarch)
		(at mel storage)
		(at ian fort)
		(at mel bar)
		(at hutexit hut)
		(at mansionentrance cliff)
		(at rubyring shop)
		(at hairtonic townarch)
		(at hutentrance townarch)
		(at basementexit basement)
		(at peter forge)
		(at camille fort)
		(at frank townsquare)
		(at bankentrance townsquare)
		(at dorian townarch)
		(at bucket fort)
		(at barentrance docks)
		(at oscar bar)
		(at dave townsquare)
		(at candle mansion)
		(at basemententrance bar)
		(at jordan mansion)
		(at michael hut)
		(at mushroom forge)
		(at knightsword forge)
		(at barexit bar)
		(at fortexit fort)
		(at matthias forge)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at bouquet cliff)
		(at book townarch)
		(closed basemententrance)
		(closed bankentrance)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch docks)
		(connected docks townarch)
		(connected storage basement)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected valley townsquare)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(has arthur shinykey)
		(has mel basementbucket)
		(has ian knightsword)
		(has dorian lovecontract)
		(has arthur loveletter)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan lovecontract)
		(wants-item ian knightshield)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item james coin)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
