(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina michael peter matthias frank dave giovanna jordan avery roger james ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope knightshield rubyring humanskull bouquet candle bucket - item
		 storage basement bar docks townarch hut forge townsquare shop cliff mansion valley fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance shopexit mansionentrance mansionexit fortentrance fortexit - entrance
	)
	(:init
		(at giovanna shop)
		(at mel basement)
		(at peter forge)
		(at mansionentrance cliff)
		(at karina townarch)
		(at shopexit shop)
		(at basementexit basement)
		(at fortentrance valley)
		(at basemententrance bar)
		(at mansionexit mansion)
		(at hutexit hut)
		(at camille fort)
		(at hairtonic townarch)
		(at mel bar)
		(at mel storage)
		(at fortexit fort)
		(at dave townsquare)
		(at michael hut)
		(at knightsword forge)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at james valley)
		(at rubyring shop)
		(at ian fort)
		(at roger mansion)
		(at dorian townarch)
		(at avery mansion)
		(at frank townsquare)
		(at tastycupcake forge)
		(at matthias forge)
		(at book townarch)
		(at shopentrance townsquare)
		(at jordan mansion)
		(at phillip fort)
		(at mushroom forge)
		(at forgeentrance townarch)
		(at candle mansion)
		(at forgeexit forge)
		(at oscar bar)
		(at bouquet cliff)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at barexit bar)
		(at knightshield shop)
		(at rope shop)
		(at bucket fort)
		(at barentrance docks)
		(closed bankentrance)
		(closed basemententrance)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected townsquare valley)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(has arthur shinykey)
		(has dorian lovecontract)
		(has ian knightsword)
		(has arthur loveletter)
		(has mel basementbucket)
		(leadsto fortexit valley)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto hutexit townarch)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto shopentrance shop)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item james coin)
		(wants-item ian knightshield)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
