(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet candle knightshield rubyring tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch townsquare valley cliff mansion shop hut fort bank forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave james jordan avery roger giovanna michael - character
	)
	(:init
		(at dave townsquare)
		(at frank townsquare)
		(at candle townarch)
		(at mel storage)
		(at oscar bar)
		(at basemententrance bar)
		(at barentrance docks)
		(at basementexit basement)
		(at shopentrance townsquare)
		(at hutentrance townarch)
		(at jordan mansion)
		(at mushroom townarch)
		(at arthur townsquare)
		(at bankentrance townsquare)
		(at michael hut)
		(at knightshield townarch)
		(at tastycupcake townarch)
		(at fortentrance valley)
		(at hutexit hut)
		(at mirror townarch)
		(at mansionexit mansion)
		(at alli junkyard)
		(at avery mansion)
		(at shopexit shop)
		(at barexit bar)
		(at humanskull townarch)
		(at dorian townarch)
		(at james valley)
		(at mansionentrance cliff)
		(at mel basement)
		(at forgeentrance townarch)
		(at mel bar)
		(at karina townarch)
		(at roger mansion)
		(at giovanna shop)
		(closed bankentrance)
		(closed basemententrance)
		(closed fortentrance)
		(closed forgeentrance)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected basement storage)
		(connected junkyard docks)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected storage basement)
		(connected townsquare townarch)
		(connected docks junkyard)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(has arthur book)
		(has dorian bouquet)
		(has jordan loveletter)
		(has arthur hairtonic)
		(has dorian rubyring)
		(has mel basementbucket)
		(has alli ash)
		(has arthur shinykey)
		(has jordan lovecontract)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto shopexit townsquare)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item giovanna hairtonic)
		(wants-item arthur ash)
		(wants-item alli tastycupcake)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur hairtonic)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
