(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake - item
		 storage basement bar docks junkyard townarch mansion cliff hut townsquare forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance mansionentrance hutexit bankentrance - entrance
		 arthur mel oscar alli dorian karina jordan - character
	)
	(:init
		(at jordan mansion)
		(at tastycupcake hut)
		(at barexit bar)
		(at hutentrance townarch)
		(at hutexit hut)
		(at karina townarch)
		(at basemententrance bar)
		(at oscar bar)
		(at mel storage)
		(at alli junkyard)
		(at arthur townarch)
		(at forgeentrance townarch)
		(at basementexit basement)
		(at mel bar)
		(at mirror junkyard)
		(at mel basement)
		(at barentrance docks)
		(at mansionentrance cliff)
		(at mushroom docks)
		(at dorian townarch)
		(closed basemententrance)
		(closed forgeentrance)
		(connected storage basement)
		(connected basement storage)
		(connected townarch docks)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected junkyard docks)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway junkyard docks)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway docks junkyard)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has alli ash)
		(has arthur loveletter)
		(has arthur shinykey)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto hutexit townarch)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item alli tastycupcake)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
