(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter - item
		 storage basement bar docks junkyard townarch cliff mansion townsquare forge hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance mansionentrance bankentrance - entrance
		 arthur mel oscar alli dorian karina jordan - character
	)
	(:init
		(at mel bar)
		(at dorian townarch)
		(at arthur townarch)
		(at barexit bar)
		(at shinykey townarch)
		(at mushroom townarch)
		(at barentrance docks)
		(at alli junkyard)
		(at jordan mansion)
		(at hutentrance townarch)
		(at oscar bar)
		(at mel storage)
		(at mansionentrance cliff)
		(at mel basement)
		(at karina townarch)
		(at basementexit basement)
		(at forgeentrance townarch)
		(at basemententrance bar)
		(closed forgeentrance)
		(closed hutentrance)
		(closed barentrance)
		(closed basemententrance)
		(connected cliff townsquare)
		(connected basement storage)
		(connected docks townarch)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected storage basement)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway docks junkyard)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has alli ash)
		(has arthur mirror)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
