(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter coin silver bucket humanskull bouquet candle knightshield rubyring knightsword ash hairtonic - item
		 storage basement bar docks townarch townsquare bank valley fort cliff mansion shop forge junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit fortentrance fortexit mansionentrance mansionexit shopexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip jordan avery roger giovanna peter - character
	)
	(:init
		(at arthur townarch)
		(at knightsword forge)
		(at fortentrance valley)
		(at frank townsquare)
		(at fortexit fort)
		(at bucket townsquare)
		(at shopentrance townsquare)
		(at oscar bar)
		(at barexit bar)
		(at jordan mansion)
		(at ian fort)
		(at bankentrance townsquare)
		(at bouquet cliff)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at candle mansion)
		(at hutentrance townarch)
		(at dorian townarch)
		(at james valley)
		(at basemententrance bar)
		(at roger mansion)
		(at karina townarch)
		(at mushroom townsquare)
		(at avery mansion)
		(at phillip fort)
		(at dave townsquare)
		(at mel bar)
		(at mansionexit mansion)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at mel basement)
		(at camille fort)
		(at peter forge)
		(at basementexit basement)
		(at mel storage)
		(at barentrance docks)
		(closed forgeentrance)
		(closed hutentrance)
		(closed basemententrance)
		(connected townarch townsquare)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected storage basement)
		(connected townarch docks)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected basement storage)
		(connected valley townsquare)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway storage basement)
		(has arthur knightshield)
		(has dorian rubyring)
		(has mel basementbucket)
		(has james coin)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has arthur silver)
		(has james humanskull)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item giovanna hairtonic)
		(wants-item ian knightsword)
		(wants-item arthur ash)
		(wants-item dorian bouquet)
		(wants-item ian knightshield)
		(wants-item arthur shinykey)
		(wants-item james candle)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightshield)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

		)
	)

)
