(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter coin silver bucket knightshield humanskull ash - item
		 storage basement bar docks townarch townsquare bank valley fort shop cliff mansion junkyard forge hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit fortentrance fortexit mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip jordan - character
	)
	(:init
		(at mel bar)
		(at barexit bar)
		(at jordan mansion)
		(at bankentrance townsquare)
		(at bucket fort)
		(at oscar bar)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at mel storage)
		(at phillip fort)
		(at basementexit basement)
		(at fortentrance valley)
		(at fortexit fort)
		(at frank townsquare)
		(at james valley)
		(at ian fort)
		(at mel basement)
		(at dorian townarch)
		(at karina townarch)
		(at dave townsquare)
		(at basemententrance bar)
		(at camille fort)
		(at barentrance docks)
		(at mansionentrance cliff)
		(at hutentrance townarch)
		(at arthur fort)
		(at knightshield shop)
		(closed hutentrance)
		(closed shopentrance)
		(closed basemententrance)
		(closed forgeentrance)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected basement storage)
		(connected townsquare valley)
		(connected storage basement)
		(connected cliff townsquare)
		(connected townarch docks)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townarch docks)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has arthur silver)
		(has arthur mushroom)
		(has mel basementbucket)
		(has james coin)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto basemententrance basement)
		(leadsto fortexit valley)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto fortentrance fort)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item james humanskull)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has jordan loveletter) 
			(and (has james coin) (has james humanskull) )
		)

	)

)
