(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightshield rubyring tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch townsquare cliff valley shop hut mansion bank forge fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance shopexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave james giovanna michael - character
	)
	(:init
		(at alli junkyard)
		(at barexit bar)
		(at bouquet cliff)
		(at oscar bar)
		(at arthur townsquare)
		(at forgeentrance townarch)
		(at karina townarch)
		(at knightshield shop)
		(at shopentrance townsquare)
		(at frank townsquare)
		(at fortentrance valley)
		(at basementexit basement)
		(at michael hut)
		(at book hut)
		(at mel storage)
		(at mirror junkyard)
		(at hutentrance townarch)
		(at dave townsquare)
		(at shinykey bar)
		(at shopexit shop)
		(at dorian townarch)
		(at mushroom hut)
		(at bankentrance townsquare)
		(at mel basement)
		(at mel bar)
		(at rubyring shop)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at humanskull cliff)
		(at james valley)
		(at barentrance docks)
		(at basemententrance bar)
		(at hutexit hut)
		(closed forgeentrance)
		(closed mansionentrance)
		(closed basemententrance)
		(closed bankentrance)
		(closed fortentrance)
		(connected townsquare cliff)
		(connected valley townsquare)
		(connected storage basement)
		(connected townsquare valley)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected basement storage)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(has dorian loveletter)
		(has alli ash)
		(has arthur tastycupcake)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has giovanna hairtonic)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item alli tastycupcake)
		(wants-item arthur ash)
		(wants-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur tastycupcake)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
		)

	)

)
