(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightshield rubyring tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch townsquare cliff valley shop hut mansion fort forge bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance shopexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave james giovanna michael jordan - character
	)
	(:init
		(at dorian townarch)
		(at arthur townsquare)
		(at bouquet cliff)
		(at basemententrance bar)
		(at basementexit basement)
		(at mel storage)
		(at barentrance docks)
		(at mirror junkyard)
		(at forgeentrance townarch)
		(at barexit bar)
		(at oscar bar)
		(at jordan mansion)
		(at shopentrance townsquare)
		(at frank townsquare)
		(at mushroom hut)
		(at book hut)
		(at bankentrance townsquare)
		(at fortentrance valley)
		(at mel bar)
		(at karina townarch)
		(at hutexit hut)
		(at dave townsquare)
		(at mel basement)
		(at hutentrance townarch)
		(at michael hut)
		(at knightshield shop)
		(at james valley)
		(at giovanna shop)
		(at shinykey bar)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at alli junkyard)
		(at rubyring shop)
		(at humanskull cliff)
		(closed fortentrance)
		(closed basemententrance)
		(closed mansionentrance)
		(closed bankentrance)
		(closed forgeentrance)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected storage basement)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected basement storage)
		(connected townarch docks)
		(connected junkyard docks)
		(connected docks junkyard)
		(connected cliff townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway storage basement)
		(doorway junkyard docks)
		(has arthur ash)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has alli tastycupcake)
		(has arthur loveletter)
		(has giovanna hairtonic)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto fortentrance fort)
		(leadsto forgeentrance forge)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
