(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter mirror ash - item
		 storage basement bar docks townarch townsquare junkyard mansion cliff valley hut forge shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave alli jordan - character
	)
	(:init
		(at jordan mansion)
		(at basementexit basement)
		(at dave townsquare)
		(at dorian townarch)
		(at barexit bar)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at mansionentrance cliff)
		(at alli junkyard)
		(at mel bar)
		(at forgeentrance townarch)
		(at mirror junkyard)
		(at barentrance docks)
		(at frank townsquare)
		(at hutentrance townarch)
		(at karina townarch)
		(at arthur junkyard)
		(at oscar bar)
		(at mel basement)
		(at basemententrance bar)
		(at mel storage)
		(closed shopentrance)
		(closed forgeentrance)
		(closed bankentrance)
		(closed hutentrance)
		(connected junkyard docks)
		(connected basement storage)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected storage basement)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected docks townarch)
		(doorway townarch docks)
		(doorway townsquare townarch)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway docks junkyard)
		(doorway basement storage)
		(has arthur shinykey)
		(has arthur mushroom)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has alli ash)
		(has mel basementbucket)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
