(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit - entrance
		 storage basement bar docks junkyard townarch hut forge townsquare valley cliff mansion shop fort bank - location
		 arthur mel oscar alli dorian karina michael peter matthias frank dave james jordan avery roger - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle rubyring - item
	)
	(:init
		(at arthur cliff)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at book hut)
		(at michael hut)
		(at mirror junkyard)
		(at mansionexit mansion)
		(at barexit bar)
		(at frank townsquare)
		(at jordan mansion)
		(at candle mansion)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at matthias forge)
		(at shopentrance townsquare)
		(at peter forge)
		(at oscar bar)
		(at bouquet cliff)
		(at mel storage)
		(at knightsword forge)
		(at forgeexit forge)
		(at rubyring shop)
		(at alli junkyard)
		(at dorian townarch)
		(at dave townsquare)
		(at hairtonic hut)
		(at roger mansion)
		(at mel bar)
		(at hutexit hut)
		(at avery mansion)
		(at karina townarch)
		(at mansionentrance cliff)
		(at mel basement)
		(at james valley)
		(at barentrance docks)
		(at basemententrance bar)
		(at basementexit basement)
		(at fortentrance valley)
		(closed bankentrance)
		(closed shopentrance)
		(closed basemententrance)
		(closed fortentrance)
		(connected townarch townsquare)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected junkyard docks)
		(connected valley townsquare)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected basement storage)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(has arthur rope)
		(has arthur ash)
		(has arthur mushroom)
		(has alli tastycupcake)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has arthur shinykey)
		(has mel basementbucket)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto fortentrance fort)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur rope)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
