(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightshield rubyring humanskull bouquet candle tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch townsquare shop valley cliff mansion hut fort bank forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance shopexit fortentrance mansionentrance mansionexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave giovanna james jordan avery roger michael - character
	)
	(:init
		(at mansionexit mansion)
		(at candle mansion)
		(at mel storage)
		(at fortentrance valley)
		(at frank townsquare)
		(at basementexit basement)
		(at book hut)
		(at bankentrance townsquare)
		(at forgeentrance townarch)
		(at jordan mansion)
		(at hutentrance townarch)
		(at barexit bar)
		(at shopentrance townsquare)
		(at arthur docks)
		(at michael hut)
		(at oscar bar)
		(at humanskull cliff)
		(at basemententrance bar)
		(at roger mansion)
		(at dave townsquare)
		(at hutexit hut)
		(at avery mansion)
		(at alli junkyard)
		(at james valley)
		(at shinykey bar)
		(at knightshield shop)
		(at barentrance docks)
		(at dorian townarch)
		(at karina townarch)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at mel basement)
		(at rubyring shop)
		(at mel bar)
		(at shopexit shop)
		(closed basemententrance)
		(closed forgeentrance)
		(closed shopentrance)
		(closed bankentrance)
		(closed fortentrance)
		(connected townsquare cliff)
		(connected storage basement)
		(connected valley townsquare)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected basement storage)
		(connected junkyard docks)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway storage basement)
		(has arthur mirror)
		(has arthur mushroom)
		(has jordan loveletter)
		(has mel basementbucket)
		(has arthur ash)
		(has arthur hairtonic)
		(has alli tastycupcake)
		(has jordan lovecontract)
		(has dorian bouquet)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto fortentrance fort)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto hutentrance hut)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item giovanna hairtonic)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur hairtonic)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
