(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightshield rubyring humanskull bouquet candle tastycupcake hairtonic - item
		 storage basement bar docks junkyard townarch townsquare shop valley cliff mansion hut bank forge fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance shopexit fortentrance mansionentrance mansionexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave giovanna james jordan avery roger - character
	)
	(:init
		(at mansionexit mansion)
		(at fortentrance valley)
		(at frank townsquare)
		(at mel storage)
		(at candle mansion)
		(at arthur mansion)
		(at basementexit basement)
		(at bankentrance townsquare)
		(at jordan mansion)
		(at barexit bar)
		(at basemententrance bar)
		(at forgeentrance townarch)
		(at bouquet cliff)
		(at shinykey bar)
		(at shopentrance townsquare)
		(at oscar bar)
		(at mel basement)
		(at barentrance docks)
		(at mel bar)
		(at dorian townarch)
		(at avery mansion)
		(at dave townsquare)
		(at alli junkyard)
		(at tastycupcake hut)
		(at hutentrance townarch)
		(at knightshield shop)
		(at humanskull cliff)
		(at james valley)
		(at shopexit shop)
		(at karina townarch)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at roger mansion)
		(at rubyring shop)
		(at hutexit hut)
		(closed basemententrance)
		(closed forgeentrance)
		(closed fortentrance)
		(closed hutentrance)
		(closed bankentrance)
		(closed shopentrance)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected storage basement)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected basement storage)
		(connected cliff townsquare)
		(connected townarch docks)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway valley townsquare)
		(doorway basement storage)
		(has arthur mushroom)
		(has arthur mirror)
		(has alli ash)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has jordan loveletter)
		(leadsto basementexit bar)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto mansionexit cliff)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto shopexit townsquare)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item giovanna hairtonic)
		(wants-item alli tastycupcake)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
