(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightshield rubyring tastycupcake hairtonic - item
		 storage basement bar docks junkyard townarch townsquare shop valley hut cliff mansion forge fort bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance shopexit fortentrance hutexit mansionentrance - entrance
		 arthur mel oscar alli dorian karina frank dave giovanna james jordan - character
	)
	(:init
		(at dorian townarch)
		(at barentrance docks)
		(at jordan mansion)
		(at shinykey bar)
		(at arthur townsquare)
		(at oscar bar)
		(at fortentrance valley)
		(at basementexit basement)
		(at basemententrance bar)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at barexit bar)
		(at giovanna shop)
		(at mansionentrance cliff)
		(at bankentrance townsquare)
		(at rubyring shop)
		(at karina townarch)
		(at mel basement)
		(at hutexit hut)
		(at hutentrance townarch)
		(at tastycupcake hut)
		(at james valley)
		(at mel bar)
		(at dave townsquare)
		(at alli junkyard)
		(at frank townsquare)
		(at mel storage)
		(at shopexit shop)
		(at knightshield shop)
		(closed basemententrance)
		(closed forgeentrance)
		(closed fortentrance)
		(closed shopentrance)
		(closed hutentrance)
		(closed bankentrance)
		(connected valley townsquare)
		(connected storage basement)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townarch docks)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected basement storage)
		(connected docks townarch)
		(doorway junkyard docks)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway storage basement)
		(has arthur loveletter)
		(has arthur mirror)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has arthur mushroom)
		(has alli ash)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(leadsto shopexit townsquare)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item alli tastycupcake)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item giovanna hairtonic)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
