(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance mansionentrance - entrance
		 storage basement bar docks junkyard townarch forge hut townsquare cliff mansion valley shop bank - location
		 arthur mel oscar alli dorian karina peter matthias michael frank dave jordan - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book humanskull bouquet - item
	)
	(:init
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at dave townsquare)
		(at matthias forge)
		(at mirror docks)
		(at shopentrance townsquare)
		(at basementexit basement)
		(at bouquet cliff)
		(at rope forge)
		(at oscar bar)
		(at forgeexit forge)
		(at hairtonic hut)
		(at bankentrance townsquare)
		(at mel storage)
		(at barentrance docks)
		(at frank townsquare)
		(at basemententrance bar)
		(at arthur cliff)
		(at dorian townarch)
		(at karina townarch)
		(at humanskull cliff)
		(at mel bar)
		(at book hut)
		(at michael hut)
		(at barexit bar)
		(at jordan mansion)
		(at mel basement)
		(at mansionentrance cliff)
		(at alli junkyard)
		(at hutexit hut)
		(at peter forge)
		(at mushroom docks)
		(closed shopentrance)
		(closed mansionentrance)
		(closed basemententrance)
		(closed bankentrance)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected docks junkyard)
		(connected storage basement)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected townarch docks)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has alli tastycupcake)
		(has arthur knightsword)
		(has arthur ash)
		(has arthur loveletter)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
