(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightsword rope tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch townsquare cliff valley forge hut mansion shop bank fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance forgeexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave james peter matthias michael jordan - character
	)
	(:init
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at bouquet cliff)
		(at dave townsquare)
		(at shopentrance townsquare)
		(at basementexit basement)
		(at peter forge)
		(at matthias forge)
		(at mansionentrance cliff)
		(at arthur hut)
		(at mirror forge)
		(at oscar bar)
		(at barentrance docks)
		(at basemententrance bar)
		(at hairtonic hut)
		(at mel storage)
		(at forgeexit forge)
		(at karina townarch)
		(at tastycupcake hut)
		(at mel basement)
		(at humanskull cliff)
		(at book hut)
		(at jordan mansion)
		(at alli junkyard)
		(at michael hut)
		(at barexit bar)
		(at fortentrance valley)
		(at mel bar)
		(at hutexit hut)
		(at dorian townarch)
		(at james valley)
		(at frank townsquare)
		(at bankentrance townsquare)
		(closed fortentrance)
		(closed mansionentrance)
		(closed bankentrance)
		(closed shopentrance)
		(closed basemententrance)
		(connected storage basement)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected basement storage)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected townarch docks)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway storage basement)
		(has arthur rope)
		(has arthur knightsword)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has mel basementbucket)
		(has alli ash)
		(has arthur mushroom)
		(leadsto bankentrance bank)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item alli tastycupcake)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
