(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring candle - item
		 storage basement bar docks junkyard townarch townsquare cliff valley forge hut bank shop mansion fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance forgeexit hutexit bankexit shopexit mansionexit - entrance
		 arthur mel oscar alli dorian karina frank dave james peter matthias michael giovanna jordan avery roger - character
	)
	(:init
		(at fortentrance valley)
		(at bankentrance townsquare)
		(at dave townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at silver bank)
		(at candle mansion)
		(at forgeexit forge)
		(at oscar bar)
		(at frank townsquare)
		(at basemententrance bar)
		(at mirror forge)
		(at shopentrance townsquare)
		(at basementexit basement)
		(at peter forge)
		(at ash cliff)
		(at barexit bar)
		(at jordan mansion)
		(at matthias forge)
		(at mel storage)
		(at mansionentrance cliff)
		(at arthur townsquare)
		(at giovanna shop)
		(at hutentrance townarch)
		(at hutexit hut)
		(at humanskull cliff)
		(at mel bar)
		(at mansionexit mansion)
		(at michael hut)
		(at rubyring mansion)
		(at barentrance docks)
		(at dorian townarch)
		(at knightshield shop)
		(at book hut)
		(at karina townarch)
		(at james valley)
		(at coin bank)
		(at avery mansion)
		(at mel basement)
		(at mushroom docks)
		(at roger mansion)
		(at shopexit shop)
		(at alli junkyard)
		(closed basemententrance)
		(closed fortentrance)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected storage basement)
		(connected townsquare townarch)
		(connected basement storage)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townarch docks)
		(connected valley townsquare)
		(doorway townsquare townarch)
		(doorway townsquare valley)
		(doorway junkyard docks)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway townsquare cliff)
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur knightsword)
		(has mel basementbucket)
		(has jordan lovecontract)
		(has dorian bouquet)
		(has arthur rope)
		(has giovanna hairtonic)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto shopentrance shop)
		(leadsto shopexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur knightsword)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
