(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina frank dave james ian camille phillip jordan avery roger giovanna michael peter matthias alli - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter coin silver bucket humanskull bouquet candle knightshield rubyring tastycupcake hairtonic book knightsword rope mirror ash - item
		 storage basement bar docks townarch townsquare bank valley fort cliff mansion shop hut forge junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit fortentrance fortexit mansionentrance mansionexit shopexit hutexit forgeexit - entrance
	)
	(:init
		(at basemententrance bar)
		(at mel bar)
		(at hutexit hut)
		(at mel basement)
		(at dave townsquare)
		(at dorian townarch)
		(at james valley)
		(at mansionexit mansion)
		(at hutentrance townarch)
		(at rope forge)
		(at fortentrance valley)
		(at barentrance docks)
		(at mel storage)
		(at frank townsquare)
		(at roger mansion)
		(at basementexit basement)
		(at mushroom townsquare)
		(at avery mansion)
		(at alli junkyard)
		(at peter forge)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at book hut)
		(at karina townarch)
		(at camille fort)
		(at shopexit shop)
		(at fortexit fort)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at mirror junkyard)
		(at bucket townsquare)
		(at matthias forge)
		(at bankentrance townsquare)
		(at candle mansion)
		(at ian fort)
		(at forgeentrance townarch)
		(at bouquet cliff)
		(at arthur docks)
		(at jordan mansion)
		(at forgeexit forge)
		(at oscar bar)
		(at barexit bar)
		(at phillip fort)
		(at michael hut)
		(closed basemententrance)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected basement storage)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected valley townsquare)
		(connected docks junkyard)
		(connected storage basement)
		(connected townsquare cliff)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway valley townsquare)
		(has arthur ash)
		(has james humanskull)
		(has alli tastycupcake)
		(has ian knightsword)
		(has james coin)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has ian knightshield)
		(has mel basementbucket)
		(has arthur hairtonic)
		(has dorian rubyring)
		(has arthur silver)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto shopexit townsquare)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto forgeexit townarch)
		(leadsto hutexit townarch)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto mansionexit cliff)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item james candle)
		(wants-item arthur shinykey)
		(wants-item giovanna hairtonic)
		(wants-item dorian bouquet)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur ash)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has james humanskull)
		(has ian knightsword)
		(has ian knightshield)
		(has james candle)
		(has giovanna hairtonic)
		(has jordan lovecontract)
		(has alli tastycupcake)
		(has arthur ash)
	  )
	)
)
