(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina frank dave - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter coin silver - item
		 storage basement bar docks townarch townsquare bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit - entrance
	)
	(:init
		(at barentrance docks)
		(at jordan mansion)
		(at oscar bar)
		(at mel storage)
		(at hutentrance townarch)
		(at mel bar)
		(at arthur bank)
		(at bankexit bank)
		(at dorian townarch)
		(at karina townarch)
		(at dave townsquare)
		(at silver bank)
		(at basementexit basement)
		(at basemententrance bar)
		(at mansionentrance cliff)
		(at forgeentrance townarch)
		(at mel basement)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at barexit bar)
		(at frank townsquare)
		(closed basemententrance)
		(closed hutentrance)
		(closed forgeentrance)
		(closed shopentrance)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected storage basement)
		(connected cliff townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected townsquare townarch)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(has arthur mushroom)
		(has arthur coin)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has mel basementbucket)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto bankexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
	  )
	)
)
