(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina frank dave jordan avery roger - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle - item
		 storage basement bar docks townarch townsquare cliff mansion - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit - entrance
	)
	(:init
		(at arthur mansion)
		(at dave townsquare)
		(at mel storage)
		(at basementexit basement)
		(at barentrance docks)
		(at humanskull cliff)
		(at mel basement)
		(at hutentrance townarch)
		(at mel bar)
		(at karina townarch)
		(at mansionentrance cliff)
		(at rubyring shop)
		(at basemententrance bar)
		(at forgeentrance townarch)
		(at roger mansion)
		(at oscar bar)
		(at shinykey bar)
		(at jordan mansion)
		(at dorian townarch)
		(at barexit bar)
		(at candle mansion)
		(at mansionexit mansion)
		(at avery mansion)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at frank townsquare)
		(closed shopentrance)
		(closed forgeentrance)
		(closed hutentrance)
		(closed bankentrance)
		(connected docks junkyard)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected basement storage)
		(connected townsquare townarch)
		(connected townarch townsquare)
		(connected townarch docks)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(has dorian bouquet)
		(has jordan loveletter)
		(has arthur mushroom)
		(has arthur lovecontract)
		(has mel basementbucket)
		(leadsto bankentrance bank)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item arthur ash)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has jordan lovecontract)
	  )
	)
)
