(open arthur barexit bar)
(move-through-entrance arthur bar barexit docks)
(pickup arthur mushroom docks)
(move-through-doorway arthur docks townarch)
(open arthur hutentrance townarch)
(move-through-entrance arthur townarch hutentrance hut)
(pickup arthur tastycupcake hut )
(pickup arthur hairtonic hut)
(move-through-entrance arthur hut hutexit townarch )
(open arthur forgeentrance townarch)
(drop arthur hairtonic townarch)
(move-through-entrance arthur townarch forgeentrance forge)
(pickup arthur knightsword forge)
(move-through-entrance arthur forge forgeexit townarch )
(move-through-doorway arthur townarch docks )
(move-through-doorway arthur docks junkyard )
(drop arthur mushroom junkyard)
(give arthur tastycupcake alli junkyard )
(pickup arthur mirror junkyard )
(move-through-doorway arthur junkyard docks)
(move-through-doorway arthur docks townarch)
(move-through-door arthur townarch towngate townsquare)
(open arthur shopentrance townsquare)
(move-through-entrance arthur townsquare shopentrance shop)
(pickup arthur knightshield shop)
(move-through-entrance arthur shop shopexit townsquare)
(move-through-doorway arthur townsquare valley)
(open arthur fortentrance valley)
(move-through-entrance arthur valley fortentrance fort)
(give arthur knightshield ian fort)
(give arthur knightsword ian fort)
(move-through-entrance arthur fort fortexit valley)
(move-through-doorway arthur valley townsquare)
(move-through-door arthur townsquare towngate townarch)
(move-through-doorway arthur townarch docks)
(move-through-doorway arthur docks junkyard )
(pickup arthur mushroom junkyard)
(drop arthur mushroom junkyard )
(move-through-doorway arthur junkyard docks)
(move-through-doorway arthur docks townarch)
(move-through-entrance arthur townarch hutentrance hut)
(move-through-entrance arthur hut hutexit townarch )
(move-through-entrance arthur townarch hutentrance hut)
(move-through-entrance arthur hut hutexit townarch )
(move-through-doorway arthur townarch docks )
(move-through-doorway arthur docks townarch)
(pickup arthur hairtonic townarch)
(move-through-door arthur townarch towngate townsquare)
(move-through-entrance arthur townsquare shopentrance shop)
(give arthur hairtonic giovanna shop)
