(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightshield rubyring humanskull bouquet candle tastycupcake hairtonic - item
		 storage basement bar docks junkyard townarch townsquare shop valley cliff mansion hut fort forge bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance shopexit fortentrance mansionentrance mansionexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave giovanna james jordan avery roger - character
	)
	(:init
		(at knightshield shop)
		(at candle mansion)
		(at fortentrance valley)
		(at arthur townarch)
		(at oscar bar)
		(at barentrance docks)
		(at mel storage)
		(at basemententrance bar)
		(at frank townsquare)
		(at shopentrance townsquare)
		(at dorian townarch)
		(at jordan mansion)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at hutentrance townarch)
		(at james valley)
		(at barexit bar)
		(at shinykey bar)
		(at giovanna shop)
		(at alli junkyard)
		(at karina townarch)
		(at mansionentrance cliff)
		(at avery mansion)
		(at dave townsquare)
		(at rubyring shop)
		(at tastycupcake hut)
		(at roger mansion)
		(at hutexit hut)
		(at humanskull cliff)
		(at mel basement)
		(at mel bar)
		(at mansionexit mansion)
		(at basementexit basement)
		(at shopexit shop)
		(closed forgeentrance)
		(closed hutentrance)
		(closed shopentrance)
		(closed bankentrance)
		(closed basemententrance)
		(closed fortentrance)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected townsquare valley)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected basement storage)
		(doorway townarch townsquare)
		(doorway townsquare townarch)
		(doorway valley townsquare)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway townarch docks)
		(has dorian lovecontract)
		(has alli ash)
		(has arthur mirror)
		(has arthur mushroom)
		(has arthur bouquet)
		(has jordan loveletter)
		(has mel basementbucket)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto barentrance bar)
		(leadsto fortentrance fort)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan lovecontract)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item giovanna hairtonic)
		(wants-item alli tastycupcake)
		(wants-item dorian rubyring)
		(wants-item dorian bouquet)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
