(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope ash - item
		 storage basement bar docks townarch hut forge cliff mansion townsquare junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit mansionentrance bankentrance - entrance
		 arthur mel oscar dorian karina michael peter matthias jordan - character
	)
	(:init
		(at oscar bar)
		(at hutentrance townarch)
		(at hutexit hut)
		(at dorian townarch)
		(at book townarch)
		(at barexit bar)
		(at basementexit basement)
		(at forgeentrance townarch)
		(at mel storage)
		(at jordan mansion)
		(at peter forge)
		(at forgeexit forge)
		(at matthias forge)
		(at hairtonic townarch)
		(at mansionentrance cliff)
		(at mel basement)
		(at barentrance docks)
		(at arthur forge)
		(at karina townarch)
		(at basemententrance bar)
		(at michael hut)
		(at mel bar)
		(closed basemententrance)
		(connected basement storage)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected storage basement)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected townarch docks)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway storage basement)
		(has arthur tastycupcake)
		(has arthur loveletter)
		(has arthur rope)
		(has arthur knightsword)
		(has arthur mushroom)
		(has arthur shinykey)
		(has mel basementbucket)
		(has dorian lovecontract)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur tastycupcake)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
