(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance mansionentrance mansionexit shopexit fortentrance fortexit - entrance
		 storage basement bar docks junkyard townarch forge hut townsquare cliff mansion shop valley fort bank - location
		 arthur mel oscar alli dorian karina peter matthias michael frank dave jordan avery roger giovanna james ian camille phillip - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book humanskull bouquet candle knightshield rubyring bucket coin - item
	)
	(:init
		(at giovanna shop)
		(at ian fort)
		(at forgeentrance townarch)
		(at mushroom townarch)
		(at mansionentrance cliff)
		(at shopentrance townsquare)
		(at phillip fort)
		(at hairtonic hut)
		(at matthias forge)
		(at bouquet cliff)
		(at forgeexit forge)
		(at oscar bar)
		(at candle mansion)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at rope forge)
		(at bucket fort)
		(at basemententrance bar)
		(at jordan mansion)
		(at barexit bar)
		(at mel storage)
		(at barentrance docks)
		(at michael hut)
		(at roger mansion)
		(at alli junkyard)
		(at frank townsquare)
		(at ash townarch)
		(at mel basement)
		(at rubyring valley)
		(at karina townarch)
		(at shopexit shop)
		(at shinykey shop)
		(at fortentrance valley)
		(at dorian townarch)
		(at dave townsquare)
		(at hutexit hut)
		(at basementexit basement)
		(at mansionexit mansion)
		(at mel bar)
		(at avery mansion)
		(at mirror townarch)
		(at fortexit fort)
		(at hutentrance townarch)
		(at james valley)
		(at peter forge)
		(at humanskull cliff)
		(at camille fort)
		(at book hut)
		(closed basemententrance)
		(closed bankentrance)
		(connected storage basement)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected basement storage)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected docks junkyard)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(has arthur knightsword)
		(has alli tastycupcake)
		(has arthur loveletter)
		(has mel basementbucket)
		(has arthur knightshield)
		(has dorian lovecontract)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto fortexit valley)
		(leadsto hutexit townarch)
		(leadsto fortentrance fort)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item ian knightsword)
		(wants-item jordan loveletter)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item ian knightshield)
		(wants-item arthur lovecontract)
		(wants-item james coin)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur knightsword)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) 
			)

		)
	)

)
