(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch hut mansion cliff townsquare forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit mansionentrance bankentrance - entrance
		 arthur mel oscar alli dorian karina michael jordan - character
	)
	(:init
		(at jordan mansion)
		(at dorian townarch)
		(at karina townarch)
		(at barexit bar)
		(at alli junkyard)
		(at arthur townarch)
		(at mel storage)
		(at hutexit hut)
		(at shinykey townarch)
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at basemententrance bar)
		(at mel basement)
		(at mirror junkyard)
		(at oscar bar)
		(at basementexit basement)
		(at mansionentrance cliff)
		(at barentrance docks)
		(at michael hut)
		(at mel bar)
		(closed forgeentrance)
		(closed basemententrance)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected storage basement)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected basement storage)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway docks townarch)
		(has dorian lovecontract)
		(has arthur ash)
		(has arthur mushroom)
		(has alli tastycupcake)
		(has arthur book)
		(has arthur loveletter)
		(has mel basementbucket)
		(has arthur hairtonic)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur book)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
