(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle bucket - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop valley cliff mansion fort forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit fortexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna james jordan avery roger ian camille phillip - character
	)
	(:init
		(at mel bar)
		(at hutexit hut)
		(at forgeentrance townarch)
		(at mel storage)
		(at bankentrance townsquare)
		(at dorian townarch)
		(at bucket fort)
		(at oscar bar)
		(at dave townsquare)
		(at candle mansion)
		(at james valley)
		(at bankexit bank)
		(at basemententrance bar)
		(at avery mansion)
		(at barexit bar)
		(at jordan mansion)
		(at book townarch)
		(at shopentrance townsquare)
		(at barentrance docks)
		(at fortexit fort)
		(at hutentrance townarch)
		(at giovanna shop)
		(at mushroom townsquare)
		(at roger mansion)
		(at silver townsquare)
		(at michael hut)
		(at rubyring shop)
		(at basementexit basement)
		(at mirror junkyard)
		(at knightshield shop)
		(at camille fort)
		(at rubyring valley)
		(at ash valley)
		(at mansionexit mansion)
		(at phillip fort)
		(at arthur mansion)
		(at frank townsquare)
		(at fortentrance valley)
		(at karina townarch)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at alli junkyard)
		(at mel basement)
		(at ian fort)
		(closed basemententrance)
		(closed forgeentrance)
		(connected townsquare valley)
		(connected docks townarch)
		(connected townarch docks)
		(connected storage basement)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected basement storage)
		(connected valley townsquare)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(has james coin)
		(has arthur loveletter)
		(has james humanskull)
		(has dorian lovecontract)
		(has giovanna hairtonic)
		(has alli tastycupcake)
		(has mel basementbucket)
		(has arthur bouquet)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto fortexit valley)
		(leadsto forgeentrance forge)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(leadsto shopexit townsquare)
		(leadsto hutexit townarch)
		(leadsto shopentrance shop)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan lovecontract)
		(wants-item james candle)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		(or
			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

		)
	)

)
