(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle tastycupcake hairtonic book knightshield rubyring ash coin - item
		 storage basement bar docks townarch townsquare cliff mansion hut valley shop junkyard bank fort forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit hutexit fortentrance shopexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger michael james giovanna - character
	)
	(:init
		(at mel basement)
		(at shopexit shop)
		(at shinykey bar)
		(at shopentrance townsquare)
		(at barexit bar)
		(at jordan mansion)
		(at james valley)
		(at karina townarch)
		(at candle mansion)
		(at bankentrance townsquare)
		(at dorian townarch)
		(at mel storage)
		(at tastycupcake hut)
		(at barentrance docks)
		(at dave townsquare)
		(at oscar bar)
		(at hutentrance townarch)
		(at knightshield shop)
		(at basementexit basement)
		(at avery mansion)
		(at forgeentrance townarch)
		(at roger mansion)
		(at humanskull cliff)
		(at mansionentrance cliff)
		(at mansionexit mansion)
		(at basemententrance bar)
		(at mel bar)
		(at arthur shop)
		(at giovanna shop)
		(at frank townsquare)
		(at fortentrance valley)
		(at book hut)
		(at rubyring shop)
		(at michael hut)
		(at hutexit hut)
		(closed forgeentrance)
		(closed fortentrance)
		(closed bankentrance)
		(connected valley townsquare)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected townarch docks)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(has arthur mushroom)
		(has arthur hairtonic)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has dorian bouquet)
		(has mel basementbucket)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto bankentrance bank)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item giovanna hairtonic)
		(wants-item arthur ash)
		(wants-item james coin)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(and (has jordan loveletter) (has jordan lovecontract) )
			(has james coin) 
		)

	)

)
