(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring knightsword coin ash - item
		 storage basement bar docks townarch townsquare valley fort shop cliff forge mansion junkyard hut bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna peter jordan - character
	)
	(:init
		(at shopexit shop)
		(at arthur townsquare)
		(at bankentrance townsquare)
		(at shopentrance townsquare)
		(at jordan mansion)
		(at barexit bar)
		(at oscar bar)
		(at fortentrance valley)
		(at basementexit basement)
		(at frank townsquare)
		(at knightsword forge)
		(at fortexit fort)
		(at peter forge)
		(at barentrance docks)
		(at mel storage)
		(at forgeentrance townarch)
		(at camille fort)
		(at dave townsquare)
		(at hutentrance townarch)
		(at mel bar)
		(at mel basement)
		(at ian fort)
		(at shinykey bar)
		(at karina townarch)
		(at basemententrance bar)
		(at giovanna shop)
		(at dorian townarch)
		(at james valley)
		(at phillip fort)
		(at mansionentrance cliff)
		(closed hutentrance)
		(closed bankentrance)
		(closed forgeentrance)
		(connected docks townarch)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected storage basement)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected basement storage)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(doorway basement storage)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townarch docks)
		(has mel basementbucket)
		(has arthur loveletter)
		(has arthur rubyring)
		(has arthur bucket)
		(has arthur knightshield)
		(has dorian lovecontract)
		(has arthur mushroom)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item ian knightshield)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item ian knightsword)
		(wants-item james coin)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur bucket)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
