(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield knightsword coin ash - item
		 storage basement bar docks townarch townsquare valley fort shop forge cliff mansion junkyard bank hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip peter jordan - character
	)
	(:init
		(at karina townarch)
		(at shopentrance townsquare)
		(at jordan mansion)
		(at dave townsquare)
		(at forgeentrance townarch)
		(at arthur townsquare)
		(at barentrance docks)
		(at mel storage)
		(at oscar bar)
		(at basemententrance bar)
		(at bankentrance townsquare)
		(at knightsword forge)
		(at frank townsquare)
		(at mel basement)
		(at fortexit fort)
		(at dorian townarch)
		(at knightshield shop)
		(at mel bar)
		(at mansionentrance cliff)
		(at basementexit basement)
		(at camille fort)
		(at barexit bar)
		(at ian fort)
		(at peter forge)
		(at fortentrance valley)
		(at james valley)
		(at hutentrance townarch)
		(at phillip fort)
		(at shinykey bar)
		(closed hutentrance)
		(closed bankentrance)
		(closed shopentrance)
		(closed forgeentrance)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected basement storage)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected townarch docks)
		(connected storage basement)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway storage basement)
		(has arthur mushroom)
		(has mel basementbucket)
		(has arthur bucket)
		(has arthur loveletter)
		(has dorian lovecontract)
		(leadsto fortexit valley)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item james coin)
		(wants-item ian knightsword)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item ian knightshield)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
