(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield knightsword coin ash - item
		 storage basement bar docks townarch townsquare valley fort cliff shop forge mansion junkyard bank hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit mansionentrance - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip peter jordan - character
	)
	(:init
		(at phillip fort)
		(at shopentrance townsquare)
		(at oscar bar)
		(at arthur townsquare)
		(at bankentrance townsquare)
		(at jordan mansion)
		(at forgeentrance townarch)
		(at barexit bar)
		(at fortentrance valley)
		(at basementexit basement)
		(at frank townsquare)
		(at fortexit fort)
		(at peter forge)
		(at barentrance docks)
		(at knightsword forge)
		(at basemententrance bar)
		(at mansionentrance cliff)
		(at dorian townarch)
		(at mel storage)
		(at james valley)
		(at mel basement)
		(at knightshield shop)
		(at hutentrance townarch)
		(at karina townarch)
		(at mel bar)
		(at ian fort)
		(at dave townsquare)
		(at camille fort)
		(at shinykey bar)
		(closed bankentrance)
		(closed shopentrance)
		(closed hutentrance)
		(closed forgeentrance)
		(connected storage basement)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected townarch docks)
		(connected basement storage)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(has mel basementbucket)
		(has arthur mushroom)
		(has arthur loveletter)
		(has arthur bucket)
		(has dorian lovecontract)
		(leadsto hutentrance hut)
		(leadsto fortexit valley)
		(leadsto shopentrance shop)
		(leadsto barexit docks)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item ian knightsword)
		(wants-item james coin)
		(wants-item ian knightshield)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
