(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter bucket knightshield rubyring humanskull bouquet candle coin silver knightsword rope ash - item
		 storage basement bar docks townarch townsquare valley fort shop cliff mansion bank forge junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance fortexit shopexit mansionentrance mansionexit bankexit forgeexit - entrance
		 arthur mel oscar dorian karina frank dave james ian camille phillip giovanna jordan avery roger peter matthias - character
	)
	(:init
		(at mushroom cliff)
		(at phillip fort)
		(at rubyring shop)
		(at frank townsquare)
		(at bouquet mansion)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at mel storage)
		(at matthias forge)
		(at forgeentrance townarch)
		(at forgeexit forge)
		(at oscar bar)
		(at rope forge)
		(at bankentrance townsquare)
		(at dave townsquare)
		(at basemententrance bar)
		(at jordan mansion)
		(at barexit bar)
		(at karina townarch)
		(at roger mansion)
		(at shopexit shop)
		(at humanskull cliff)
		(at mel basement)
		(at basementexit basement)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at arthur forge)
		(at mel bar)
		(at mansionexit mansion)
		(at avery mansion)
		(at camille fort)
		(at barentrance docks)
		(at fortentrance valley)
		(at peter forge)
		(at candle forge)
		(at hutentrance townarch)
		(at silver bank)
		(at fortexit fort)
		(at james valley)
		(at dorian townarch)
		(at ian fort)
		(closed hutentrance)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected storage basement)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected basement storage)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected townsquare townarch)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(has dorian lovecontract)
		(has arthur rubyring)
		(has jordan loveletter)
		(has mel basementbucket)
		(has ian knightshield)
		(has arthur bucket)
		(has arthur coin)
		(has arthur knightsword)
		(leadsto basemententrance basement)
		(leadsto shopentrance shop)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(leadsto forgeexit townarch)
		(leadsto fortexit valley)
		(leadsto shopexit townsquare)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian bouquet)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item ian knightsword)
		(wants-item dorian rubyring)
		(wants-item james coin)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur bucket)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
