(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book coin silver knightshield rubyring humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch hut townsquare bank shop valley cliff mansion fort forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit - entrance
		 arthur mel oscar alli dorian karina michael frank dave giovanna james jordan avery roger - character
	)
	(:init
		(at mansionentrance cliff)
		(at frank townsquare)
		(at barentrance docks)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at jordan mansion)
		(at book townarch)
		(at bouquet cliff)
		(at candle mansion)
		(at oscar bar)
		(at coin bank)
		(at mirror junkyard)
		(at bankentrance townsquare)
		(at basemententrance bar)
		(at mel storage)
		(at barexit bar)
		(at dave townsquare)
		(at hutexit hut)
		(at rubyring shop)
		(at avery mansion)
		(at fortentrance valley)
		(at giovanna shop)
		(at mel basement)
		(at roger mansion)
		(at karina townarch)
		(at shopexit shop)
		(at arthur mansion)
		(at mansionexit mansion)
		(at knightshield shop)
		(at basementexit basement)
		(at silver townsquare)
		(at mel bar)
		(at ash townsquare)
		(at hutentrance townarch)
		(at michael hut)
		(at humanskull cliff)
		(at dorian townarch)
		(at james valley)
		(at alli junkyard)
		(at mushroom townsquare)
		(closed forgeentrance)
		(closed fortentrance)
		(closed basemententrance)
		(connected townsquare valley)
		(connected docks townarch)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected valley townsquare)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway valley townsquare)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(has dorian lovecontract)
		(has arthur rubyring)
		(has giovanna hairtonic)
		(has alli tastycupcake)
		(has mel basementbucket)
		(has arthur loveletter)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
