(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina frank dave james peter matthias michael giovanna jordan avery roger - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring candle - item
		 storage basement bar docks junkyard townarch townsquare cliff valley forge hut bank shop mansion - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance forgeexit hutexit bankexit shopexit mansionexit - entrance
	)
	(:init
		(at alli junkyard)
		(at mushroom docks)
		(at mansionexit mansion)
		(at fortentrance valley)
		(at peter forge)
		(at basemententrance bar)
		(at barentrance docks)
		(at michael hut)
		(at knightshield shop)
		(at forgeexit forge)
		(at roger mansion)
		(at frank townsquare)
		(at book hut)
		(at mel basement)
		(at giovanna shop)
		(at mansionentrance cliff)
		(at mel bar)
		(at hutexit hut)
		(at karina townarch)
		(at basementexit basement)
		(at shopexit shop)
		(at barexit bar)
		(at rubyring mansion)
		(at dave townsquare)
		(at coin bank)
		(at bankentrance townsquare)
		(at arthur valley)
		(at james valley)
		(at ash cliff)
		(at oscar bar)
		(at dorian townarch)
		(at mirror forge)
		(at candle mansion)
		(at avery mansion)
		(at humanskull cliff)
		(at mel storage)
		(at hutentrance townarch)
		(at jordan mansion)
		(at forgeentrance townarch)
		(at silver bank)
		(at bankexit bank)
		(at matthias forge)
		(at shopentrance townsquare)
		(closed basemententrance)
		(closed fortentrance)
		(connected basement storage)
		(connected valley townsquare)
		(connected junkyard docks)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected storage basement)
		(connected townsquare valley)
		(connected townsquare cliff)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway townarch docks)
		(has alli tastycupcake)
		(has dorian bouquet)
		(has mel basementbucket)
		(has jordan lovecontract)
		(has giovanna hairtonic)
		(has arthur rope)
		(has jordan loveletter)
		(has arthur knightsword)
		(leadsto basementexit bar)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto mansionexit cliff)
		(leadsto fortentrance fort)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(leadsto forgeexit townarch)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has arthur ash)
		(has jordan lovecontract)
	  )
	)
)
