(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina frank dave - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter - item
		 storage basement bar docks junkyard townarch townsquare - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance - entrance
	)
	(:init
		(at oscar bar)
		(at basementexit basement)
		(at mel basement)
		(at barentrance docks)
		(at tastycupcake hut)
		(at karina townarch)
		(at jordan mansion)
		(at dorian townarch)
		(at basemententrance bar)
		(at alli junkyard)
		(at frank townsquare)
		(at dave townsquare)
		(at mel bar)
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at barexit bar)
		(at arthur townsquare)
		(at shopentrance townsquare)
		(at mel storage)
		(at hutexit hut)
		(at mansionentrance cliff)
		(closed shopentrance)
		(closed basemententrance)
		(closed bankentrance)
		(closed hutentrance)
		(closed forgeentrance)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected basement storage)
		(connected junkyard docks)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway basement storage)
		(has arthur shinykey)
		(has mel basementbucket)
		(has arthur mirror)
		(has dorian lovecontract)
		(has alli ash)
		(has arthur mushroom)
		(has arthur loveletter)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item alli tastycupcake)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur mirror)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
	  )
	)
)
