(move-through-entrance arthur shop shopexit townsquare)
(move-through-doorway arthur townsquare cliff)
(move-through-entrance arthur cliff mansionentrance mansion)
(give arthur loveletter jordan mansion)
(move-through-entrance arthur mansion mansionexit cliff)
(move-through-doorway arthur cliff townsquare)
(move-through-door arthur townsquare towngate townarch )
(move-through-entrance arthur townarch forgeentrance forge )
(move-through-entrance arthur forge forgeexit townarch )
(move-through-entrance arthur townarch hutentrance hut )
(move-through-entrance arthur hut hutexit townarch )
(move-through-door arthur townarch towngate townsquare )
(move-through-entrance arthur townsquare shopentrance shop )
