(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina frank dave james michael peter matthias giovanna jordan avery roger ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet tastycupcake hairtonic book knightsword rope knightshield rubyring candle bucket - item
		 storage basement bar docks junkyard townarch townsquare valley cliff hut forge shop mansion fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance hutexit forgeexit shopexit mansionexit fortexit - entrance
	)
	(:init
		(at mel basement)
		(at frank townsquare)
		(at dave townsquare)
		(at book hut)
		(at michael hut)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at hutexit hut)
		(at fortentrance valley)
		(at camille fort)
		(at mel bar)
		(at arthur fort)
		(at basementexit basement)
		(at peter forge)
		(at phillip fort)
		(at rubyring shop)
		(at ian fort)
		(at james valley)
		(at dorian townarch)
		(at avery mansion)
		(at rubyring cliff)
		(at fortexit fort)
		(at karina townarch)
		(at shopexit shop)
		(at roger mansion)
		(at humanskull cliff)
		(at hutentrance townarch)
		(at alli junkyard)
		(at barexit bar)
		(at forgeentrance townarch)
		(at mel storage)
		(at mushroom hut)
		(at forgeexit forge)
		(at jordan mansion)
		(at candle fort)
		(at shopentrance townsquare)
		(at matthias forge)
		(at barentrance docks)
		(at knightsword forge)
		(at shinykey hut)
		(at mansionexit mansion)
		(at oscar bar)
		(at knightshield shop)
		(at basemententrance bar)
		(at bucket fort)
		(at bankentrance townsquare)
		(closed basemententrance)
		(closed bankentrance)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected basement storage)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected storage basement)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected townsquare valley)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(has arthur ash)
		(has dorian lovecontract)
		(has arthur rope)
		(has arthur mirror)
		(has arthur bouquet)
		(has arthur loveletter)
		(leadsto mansionentrance mansion)
		(leadsto shopexit townsquare)
		(leadsto forgeexit townarch)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto mansionexit cliff)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item ian knightshield)
		(wants-item jordan loveletter)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item ian knightsword)
		(wants-item james coin)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur rope)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has alli tastycupcake)
		(has arthur ash)
		(has giovanna hairtonic)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
