(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina frank dave james michael peter matthias giovanna jordan avery roger - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet tastycupcake hairtonic book knightsword rope knightshield rubyring candle - item
		 storage basement bar docks junkyard townarch townsquare valley cliff hut forge shop mansion - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance hutexit forgeexit shopexit mansionexit - entrance
	)
	(:init
		(at fortentrance valley)
		(at basemententrance bar)
		(at frank townsquare)
		(at mel bar)
		(at hutexit hut)
		(at mansionexit mansion)
		(at barentrance docks)
		(at mel storage)
		(at knightshield shop)
		(at rubyring shop)
		(at book hut)
		(at humanskull cliff)
		(at shopexit shop)
		(at basementexit basement)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at karina townarch)
		(at peter forge)
		(at dave townsquare)
		(at alli junkyard)
		(at roger mansion)
		(at mel basement)
		(at hutentrance townarch)
		(at bankentrance townsquare)
		(at forgeentrance townarch)
		(at michael hut)
		(at knightsword forge)
		(at forgeexit forge)
		(at candle mansion)
		(at dorian townarch)
		(at james valley)
		(at shopentrance townsquare)
		(at jordan mansion)
		(at arthur cliff)
		(at barexit bar)
		(at oscar bar)
		(at shinykey hut)
		(at mushroom hut)
		(at matthias forge)
		(at avery mansion)
		(closed bankentrance)
		(closed fortentrance)
		(closed basemententrance)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected basement storage)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townsquare valley)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(has arthur ash)
		(has mel basementbucket)
		(has arthur rope)
		(has arthur bouquet)
		(has arthur mirror)
		(has dorian lovecontract)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has arthur rubyring)
		(has arthur loveletter)
		(leadsto mansionentrance mansion)
		(leadsto shopexit townsquare)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto shopentrance shop)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item jordan loveletter)
		(wants-item james coin)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mirror)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has alli tastycupcake)
		(has arthur ash)
		(has giovanna hairtonic)
	  )
	)
)
