(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina frank dave james michael peter matthias giovanna jordan avery roger ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet tastycupcake hairtonic book knightsword rope knightshield rubyring candle bucket - item
		 storage basement bar docks junkyard townarch townsquare valley cliff hut forge shop mansion fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance hutexit forgeexit shopexit mansionexit fortexit - entrance
	)
	(:init
		(at book hut)
		(at mel basement)
		(at frank townsquare)
		(at michael hut)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at arthur fort)
		(at hutexit hut)
		(at fortentrance valley)
		(at peter forge)
		(at knightsword forge)
		(at basementexit basement)
		(at mel bar)
		(at shopexit shop)
		(at james valley)
		(at phillip fort)
		(at rubyring shop)
		(at dorian townarch)
		(at avery mansion)
		(at rubyring cliff)
		(at ian fort)
		(at roger mansion)
		(at fortexit fort)
		(at karina townarch)
		(at humanskull cliff)
		(at hutentrance townarch)
		(at alli junkyard)
		(at mansionexit mansion)
		(at shopentrance townsquare)
		(at barentrance docks)
		(at basemententrance bar)
		(at bucket fort)
		(at matthias forge)
		(at mel storage)
		(at jordan mansion)
		(at dave townsquare)
		(at barexit bar)
		(at forgeexit forge)
		(at knightshield shop)
		(at oscar bar)
		(at shinykey hut)
		(at camille fort)
		(at forgeentrance townarch)
		(at mushroom hut)
		(at bankentrance townsquare)
		(closed basemententrance)
		(closed bankentrance)
		(connected townsquare townarch)
		(connected basement storage)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected storage basement)
		(connected townsquare valley)
		(connected townarch docks)
		(connected junkyard docks)
		(connected docks townarch)
		(doorway junkyard docks)
		(doorway townarch townsquare)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway storage basement)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(has arthur rope)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has arthur bouquet)
		(has arthur mirror)
		(has arthur candle)
		(has arthur ash)
		(leadsto shopexit townsquare)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto mansionexit cliff)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item james coin)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur candle)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has alli tastycupcake)
		(has arthur ash)
		(has giovanna hairtonic)
	  )
	)
)
