(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter mirror ash tastycupcake - item
		 storage basement bar docks townarch townsquare junkyard cliff mansion hut valley shop bank forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance hutexit - entrance
		 arthur mel oscar dorian karina frank dave alli jordan - character
	)
	(:init
		(at dave townsquare)
		(at tastycupcake hut)
		(at bankentrance townsquare)
		(at hutexit hut)
		(at barexit bar)
		(at jordan mansion)
		(at basementexit basement)
		(at oscar bar)
		(at basemententrance bar)
		(at karina townarch)
		(at alli junkyard)
		(at shopentrance townsquare)
		(at mansionentrance cliff)
		(at forgeentrance townarch)
		(at barentrance docks)
		(at arthur docks)
		(at mel bar)
		(at dorian townarch)
		(at frank townsquare)
		(at hutentrance townarch)
		(at mel storage)
		(at mel basement)
		(closed forgeentrance)
		(closed hutentrance)
		(closed shopentrance)
		(closed bankentrance)
		(connected townarch docks)
		(connected basement storage)
		(connected docks junkyard)
		(connected docks townarch)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected storage basement)
		(connected cliff townsquare)
		(connected townsquare townarch)
		(connected townsquare valley)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway storage basement)
		(has alli ash)
		(has arthur mushroom)
		(has dorian lovecontract)
		(has arthur mirror)
		(has mel basementbucket)
		(has arthur loveletter)
		(has arthur shinykey)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto basemententrance basement)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item alli tastycupcake)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
