(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter mirror ash humanskull bouquet candle rubyring tastycupcake coin - item
		 storage basement bar docks townarch townsquare junkyard valley cliff mansion shop hut fort bank forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance mansionexit hutexit - entrance
		 arthur mel oscar dorian karina frank dave alli james jordan avery roger - character
	)
	(:init
		(at avery mansion)
		(at basemententrance bar)
		(at frank townsquare)
		(at oscar bar)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at basementexit basement)
		(at arthur mansion)
		(at forgeentrance townarch)
		(at dave townsquare)
		(at fortentrance valley)
		(at barexit bar)
		(at alli junkyard)
		(at humanskull cliff)
		(at jordan mansion)
		(at mel basement)
		(at karina townarch)
		(at mansionentrance cliff)
		(at roger mansion)
		(at mel storage)
		(at hutexit hut)
		(at james valley)
		(at dorian townarch)
		(at hutentrance townarch)
		(at tastycupcake hut)
		(at mel bar)
		(at mansionexit mansion)
		(at rubyring shop)
		(at barentrance docks)
		(closed hutentrance)
		(closed shopentrance)
		(closed forgeentrance)
		(closed bankentrance)
		(closed fortentrance)
		(connected basement storage)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected docks townarch)
		(connected storage basement)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected junkyard docks)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway townsquare townarch)
		(has alli ash)
		(has arthur mushroom)
		(has arthur mirror)
		(has arthur loveletter)
		(has arthur bouquet)
		(has arthur candle)
		(has arthur shinykey)
		(has dorian lovecontract)
		(has mel basementbucket)
		(leadsto forgeentrance forge)
		(leadsto mansionexit cliff)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto fortentrance fort)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item alli tastycupcake)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item james coin)
		(willing-to-give-item arthur candle)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
