(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina frank dave james alli michael peter matthias giovanna ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter mirror ash tastycupcake hairtonic book knightsword rope knightshield rubyring bucket - item
		 storage basement bar docks townarch townsquare valley junkyard hut forge shop fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance hutexit forgeexit shopexit fortexit - entrance
	)
	(:init
		(at fortentrance valley)
		(at peter forge)
		(at basementexit basement)
		(at hutexit hut)
		(at hutentrance townarch)
		(at barentrance docks)
		(at camille fort)
		(at rubyring shop)
		(at karina townarch)
		(at ian fort)
		(at mel bar)
		(at michael hut)
		(at book hut)
		(at giovanna shop)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at frank townsquare)
		(at tastycupcake townsquare)
		(at alli junkyard)
		(at fortexit fort)
		(at mel basement)
		(at basemententrance bar)
		(at bankentrance townsquare)
		(at mirror hut)
		(at forgeexit forge)
		(at forgeentrance townarch)
		(at mushroom hut)
		(at dorian townarch)
		(at arthur valley)
		(at james valley)
		(at dave townsquare)
		(at phillip fort)
		(at barexit bar)
		(at oscar bar)
		(at bucket fort)
		(at mel storage)
		(at jordan mansion)
		(at matthias forge)
		(at shopentrance townsquare)
		(at hairtonic hut)
		(at rope forge)
		(closed bankentrance)
		(closed basemententrance)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected docks junkyard)
		(connected basement storage)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected storage basement)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected junkyard docks)
		(connected townsquare valley)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway junkyard docks)
		(doorway valley townsquare)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway docks junkyard)
		(has mel basementbucket)
		(has alli ash)
		(has arthur shinykey)
		(has dorian lovecontract)
		(has ian knightshield)
		(has ian knightsword)
		(has arthur loveletter)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item giovanna hairtonic)
		(wants-item james coin)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item alli tastycupcake)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
