(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar dorian karina peter matthias michael frank dave giovanna alli james jordan avery roger - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring mirror ash humanskull bouquet candle - item
		 storage basement bar docks townarch forge hut townsquare bank shop junkyard valley cliff mansion - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit - entrance
	)
	(:init
		(at mansionentrance cliff)
		(at giovanna shop)
		(at mel basement)
		(at shopexit shop)
		(at dorian townarch)
		(at michael hut)
		(at frank townsquare)
		(at mansionexit mansion)
		(at knightshield shop)
		(at barentrance docks)
		(at fortentrance valley)
		(at mel bar)
		(at hutexit hut)
		(at dave townsquare)
		(at avery mansion)
		(at coin bank)
		(at book townsquare)
		(at silver bank)
		(at mushroom townsquare)
		(at rubyring shop)
		(at humanskull cliff)
		(at karina townarch)
		(at hutentrance townarch)
		(at james valley)
		(at alli junkyard)
		(at roger mansion)
		(at matthias forge)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at jordan mansion)
		(at basemententrance bar)
		(at mel storage)
		(at candle mansion)
		(at forgeexit forge)
		(at oscar bar)
		(at forgeentrance townarch)
		(at arthur mansion)
		(at bankentrance townsquare)
		(at barexit bar)
		(at tastycupcake hut)
		(at peter forge)
		(at basementexit basement)
		(closed forgeentrance)
		(closed bankentrance)
		(closed basemententrance)
		(closed shopentrance)
		(closed hutentrance)
		(closed fortentrance)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townsquare valley)
		(connected basement storage)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected townarch docks)
		(connected storage basement)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(has dorian bouquet)
		(has arthur mirror)
		(has alli ash)
		(has arthur rope)
		(has arthur knightsword)
		(has arthur lovecontract)
		(has jordan loveletter)
		(leadsto mansionentrance mansion)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto forgeexit townarch)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian rubyring)
		(wants-item james coin)
		(wants-item alli tastycupcake)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(wants-item arthur ash)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has giovanna hairtonic)
		(has jordan loveletter)
		(has james coin)
		(has alli tastycupcake)
		(has jordan lovecontract)
	  )
	)
)
