(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch forge hut townsquare - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit bankentrance - entrance
		 arthur mel oscar alli dorian karina peter matthias michael jordan - character
	)
	(:init
		(at hairtonic townarch)
		(at hutexit hut)
		(at shinykey townarch)
		(at hutentrance townarch)
		(at book townarch)
		(at rope townarch)
		(at mushroom townarch)
		(at barexit bar)
		(at arthur townarch)
		(at knightsword townarch)
		(at alli junkyard)
		(at peter forge)
		(at barentrance docks)
		(at karina townarch)
		(at forgeentrance townarch)
		(at dorian townarch)
		(at matthias forge)
		(at michael hut)
		(at mel bar)
		(at mel basement)
		(at mirror townarch)
		(at forgeexit forge)
		(connected junkyard docks)
		(connected townarch docks)
		(connected docks townarch)
		(connected docks junkyard)
		(connected townarch townsquare)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(doorway townarch townsquare)
		(has alli tastycupcake)
		(has dorian lovecontract)
		(has arthur ash)
		(has arthur loveletter)
		(leadsto hutentrance hut)
		(leadsto forgeexit townarch)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
