(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book knightshield rubyring - item
		 storage basement bar docks junkyard townarch forge hut townsquare shop cliff valley bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance shopexit - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan - character
	)
	(:init
		(at mel bar)
		(at forgeentrance townarch)
		(at karina townarch)
		(at hutexit hut)
		(at shopexit shop)
		(at knightshield townsquare)
		(at mushroom townarch)
		(at hutentrance townarch)
		(at book townarch)
		(at knightsword townarch)
		(at forgeexit forge)
		(at barexit bar)
		(at shopentrance townsquare)
		(at rubyring townsquare)
		(at shinykey townsquare)
		(at bankentrance townsquare)
		(at arthur shop)
		(at barentrance docks)
		(at frank townsquare)
		(at michael hut)
		(at mel basement)
		(at mirror townarch)
		(at peter forge)
		(at rope townarch)
		(at ash townarch)
		(at giovanna shop)
		(at dorian townarch)
		(at dave townsquare)
		(at matthias forge)
		(at alli junkyard)
		(closed bankentrance)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected townarch docks)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(has giovanna hairtonic)
		(has alli tastycupcake)
		(has dorian lovecontract)
		(has arthur loveletter)
		(leadsto hutentrance hut)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
