(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightshield rubyring tastycupcake hairtonic book candle - item
		 storage basement bar docks junkyard townarch townsquare cliff valley shop hut mansion fort forge bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance shopexit hutexit mansionexit - entrance
		 arthur mel oscar alli dorian karina frank dave james giovanna michael jordan avery roger - character
	)
	(:init
		(at alli junkyard)
		(at hutentrance townarch)
		(at james valley)
		(at book hut)
		(at michael hut)
		(at mirror junkyard)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at mansionexit mansion)
		(at bankentrance townsquare)
		(at knightshield shop)
		(at candle mansion)
		(at barexit bar)
		(at barentrance docks)
		(at jordan mansion)
		(at oscar bar)
		(at frank townsquare)
		(at basemententrance bar)
		(at humanskull cliff)
		(at mushroom hut)
		(at roger mansion)
		(at shinykey bar)
		(at avery mansion)
		(at rubyring shop)
		(at mel storage)
		(at karina townarch)
		(at mel basement)
		(at mel bar)
		(at arthur townarch)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at dorian townarch)
		(at dave townsquare)
		(at basementexit basement)
		(at fortentrance valley)
		(at hutexit hut)
		(closed fortentrance)
		(closed bankentrance)
		(closed forgeentrance)
		(closed basemententrance)
		(connected storage basement)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townsquare valley)
		(connected townarch docks)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected townarch townsquare)
		(connected basement storage)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway junkyard docks)
		(doorway townsquare valley)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(has jordan loveletter)
		(has mel basementbucket)
		(has arthur ash)
		(has giovanna hairtonic)
		(has dorian bouquet)
		(has arthur lovecontract)
		(has alli tastycupcake)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto fortentrance fort)
		(leadsto shopexit townsquare)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto mansionexit cliff)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
