(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightshield rubyring tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch townsquare cliff valley shop hut fort bank mansion forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance shopexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave james giovanna michael - character
	)
	(:init
		(at barentrance docks)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at oscar bar)
		(at bouquet cliff)
		(at shinykey bar)
		(at knightshield shop)
		(at barexit bar)
		(at mushroom hut)
		(at karina townarch)
		(at basementexit basement)
		(at dave townsquare)
		(at bankentrance townsquare)
		(at arthur townarch)
		(at rubyring shop)
		(at michael hut)
		(at dorian townarch)
		(at fortentrance valley)
		(at mel storage)
		(at shopexit shop)
		(at frank townsquare)
		(at book hut)
		(at basemententrance bar)
		(at mirror junkyard)
		(at mel bar)
		(at alli junkyard)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at mel basement)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at james valley)
		(at hutexit hut)
		(closed mansionentrance)
		(closed basemententrance)
		(closed bankentrance)
		(closed fortentrance)
		(closed forgeentrance)
		(connected townarch townsquare)
		(connected townsquare valley)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected junkyard docks)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected docks townarch)
		(connected storage basement)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected basement storage)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(has dorian loveletter)
		(has arthur hairtonic)
		(has mel basementbucket)
		(has arthur tastycupcake)
		(has dorian lovecontract)
		(has alli ash)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto shopexit townsquare)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item alli tastycupcake)
		(wants-item arthur shinykey)
		(wants-item giovanna hairtonic)
		(wants-item arthur loveletter)
		(willing-to-give-item arthur tastycupcake)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
		)

	)

)
