(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter coin silver knightshield rubyring tastycupcake hairtonic - item
		 storage basement bar docks junkyard townarch townsquare bank shop cliff hut mansion valley forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit shopexit mansionentrance hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave giovanna jordan - character
	)
	(:init
		(at mansionentrance cliff)
		(at forgeentrance townarch)
		(at bankexit bank)
		(at oscar bar)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at barexit bar)
		(at giovanna shop)
		(at basementexit basement)
		(at dorian townarch)
		(at hutentrance townarch)
		(at dave townsquare)
		(at mel storage)
		(at jordan mansion)
		(at basemententrance bar)
		(at mirror junkyard)
		(at arthur shop)
		(at frank townsquare)
		(at mel basement)
		(at karina townarch)
		(at shopexit shop)
		(at mel bar)
		(at hutexit hut)
		(at alli junkyard)
		(at barentrance docks)
		(at tastycupcake hut)
		(closed forgeentrance)
		(closed hutentrance)
		(connected townsquare townarch)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected junkyard docks)
		(connected basement storage)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected storage basement)
		(doorway townsquare valley)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway cliff townsquare)
		(has arthur loveletter)
		(has arthur silver)
		(has arthur coin)
		(has alli ash)
		(has mel basementbucket)
		(has arthur knightshield)
		(has dorian lovecontract)
		(has arthur mushroom)
		(has arthur rubyring)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto shopexit townsquare)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto bankexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item giovanna hairtonic)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item alli tastycupcake)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur coin)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
