(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet tastycupcake hairtonic book knightsword rope coin - item
		 storage basement bar docks junkyard townarch townsquare valley cliff hut forge mansion shop fort bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance hutexit forgeexit - entrance
		 arthur mel oscar alli dorian karina frank dave james michael peter matthias jordan - character
	)
	(:init
		(at barentrance docks)
		(at karina townarch)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at shinykey hut)
		(at matthias forge)
		(at oscar bar)
		(at barexit bar)
		(at jordan mansion)
		(at mel storage)
		(at james valley)
		(at humanskull cliff)
		(at peter forge)
		(at forgeexit forge)
		(at michael hut)
		(at book hut)
		(at dave townsquare)
		(at hutentrance townarch)
		(at mansionentrance cliff)
		(at arthur forge)
		(at frank townsquare)
		(at basementexit basement)
		(at basemententrance bar)
		(at mel bar)
		(at hutexit hut)
		(at alli junkyard)
		(at rope forge)
		(at mel basement)
		(at mushroom hut)
		(at bankentrance townsquare)
		(at dorian townarch)
		(at knightsword forge)
		(at fortentrance valley)
		(closed mansionentrance)
		(closed basemententrance)
		(closed bankentrance)
		(closed fortentrance)
		(closed shopentrance)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected docks townarch)
		(connected basement storage)
		(connected storage basement)
		(connected townarch townsquare)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(has arthur tastycupcake)
		(has mel basementbucket)
		(has arthur loveletter)
		(has alli ash)
		(has dorian lovecontract)
		(has arthur bouquet)
		(has arthur mirror)
		(has arthur hairtonic)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto forgeexit townarch)
		(leadsto hutexit townarch)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item james coin)
		(wants-item alli tastycupcake)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur tastycupcake)
		(willing-to-give-item arthur hairtonic)
		(willing-to-give-item arthur bouquet)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
