(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash loveletter lovecontract - item
		 storage basement bar docks junkyard townarch - location
		 basementexit basemententrance barexit barentrance bankentrance - entrance
		 arthur mel oscar alli - character
	)
	(:init
		(at arthur docks)
		(at basementexit basement)
		(at oscar bar)
		(at mel storage)
		(at alli junkyard)
		(at barexit bar)
		(at barentrance docks)
		(at mel bar)
		(at mel basement)
		(at mushroom docks)
		(at basemententrance bar)
		(closed basemententrance)
		(connected junkyard docks)
		(connected storage basement)
		(connected basement storage)
		(connected docks townarch)
		(connected docks junkyard)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway basement storage)
		(has arthur shinykey)
		(has arthur mirror)
		(has alli ash)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item arthur loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		(game-has-been-won)
	)
)
