(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle coin silver bucket knightshield rubyring knightsword rope ash - item
		 storage basement bar docks townarch townsquare cliff mansion valley bank fort shop forge junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit fortentrance bankexit fortexit shopexit forgeexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger james ian camille phillip giovanna peter matthias - character
	)
	(:init
		(at bucket fort)
		(at karina townarch)
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at silver bank)
		(at bankexit bank)
		(at matthias forge)
		(at shopentrance townsquare)
		(at roger mansion)
		(at forgeexit forge)
		(at candle mansion)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at fortexit fort)
		(at jordan mansion)
		(at barexit bar)
		(at rope forge)
		(at oscar bar)
		(at giovanna shop)
		(at camille fort)
		(at shopexit shop)
		(at dorian townarch)
		(at mel bar)
		(at frank townsquare)
		(at basemententrance bar)
		(at mel basement)
		(at mel storage)
		(at mansionentrance cliff)
		(at barentrance docks)
		(at ian fort)
		(at mansionexit mansion)
		(at fortentrance valley)
		(at rubyring shop)
		(at dave townsquare)
		(at peter forge)
		(at avery mansion)
		(at basementexit basement)
		(at phillip fort)
		(at james valley)
		(closed hutentrance)
		(closed basemententrance)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected storage basement)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected townarch townsquare)
		(connected basement storage)
		(connected townarch docks)
		(connected docks junkyard)
		(connected cliff townsquare)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway basement storage)
		(has dorian bouquet)
		(has arthur mushroom)
		(has ian knightshield)
		(has jordan loveletter)
		(has jordan lovecontract)
		(has ian knightsword)
		(has mel basementbucket)
		(has james humanskull)
		(has james coin)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(leadsto fortexit valley)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item james candle)
		(wants-item arthur ash)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(and (has ian knightsword) (has ian knightshield) )
			(and (has jordan loveletter) (has jordan lovecontract) )
			(and (has james coin) (has james humanskull) (has james candle) )
		)

	)

)
