(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle coin silver rubyring ash - item
		 storage basement bar docks townarch townsquare cliff mansion valley bank shop junkyard fort forge hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit fortentrance bankexit - entrance
		 arthur mel oscar dorian karina frank dave jordan avery roger james - character
	)
	(:init
		(at frank townsquare)
		(at dave townsquare)
		(at silver bank)
		(at bankexit bank)
		(at mel storage)
		(at shopentrance townsquare)
		(at bankentrance townsquare)
		(at candle mansion)
		(at james valley)
		(at rubyring shop)
		(at dorian townarch)
		(at mansionentrance cliff)
		(at arthur valley)
		(at avery mansion)
		(at oscar bar)
		(at forgeentrance townarch)
		(at basemententrance bar)
		(at mel bar)
		(at karina townarch)
		(at roger mansion)
		(at jordan mansion)
		(at barentrance docks)
		(at fortentrance valley)
		(at mansionexit mansion)
		(at hutentrance townarch)
		(at basementexit basement)
		(at mel basement)
		(at barexit bar)
		(closed fortentrance)
		(closed basemententrance)
		(closed shopentrance)
		(closed hutentrance)
		(closed forgeentrance)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected townarch docks)
		(connected basement storage)
		(connected storage basement)
		(connected townarch townsquare)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(has mel basementbucket)
		(has james coin)
		(has jordan lovecontract)
		(has dorian bouquet)
		(has arthur mushroom)
		(has james humanskull)
		(has jordan loveletter)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item james candle)
		(wants-item arthur shinykey)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		(and
			(and (has jordan loveletter) (has jordan lovecontract) )
			(and (has james coin) (has james humanskull) (has james candle) )
		)

	)

)
