(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch forge hut townsquare - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit bankentrance - entrance
		 arthur mel oscar alli dorian karina peter matthias michael jordan - character
	)
	(:init
		(at forgeentrance townarch)
		(at mushroom townarch)
		(at hutexit hut)
		(at forgeexit forge)
		(at barexit bar)
		(at shinykey townarch)
		(at hutentrance townarch)
		(at rope townarch)
		(at arthur townarch)
		(at hairtonic townarch)
		(at knightsword townarch)
		(at matthias forge)
		(at mel bar)
		(at mirror townarch)
		(at michael hut)
		(at karina townarch)
		(at dorian townarch)
		(at mel basement)
		(at peter forge)
		(at tastycupcake townarch)
		(connected townarch docks)
		(connected junkyard docks)
		(connected townarch townsquare)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway docks townarch)
		(has dorian lovecontract)
		(has arthur book)
		(has alli ash)
		(has arthur loveletter)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur book)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
