(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book knightshield rubyring coin silver - item
		 storage basement bar docks junkyard townarch forge hut townsquare shop bank cliff valley - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance shopexit bankexit - entrance
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan - character
	)
	(:init
		(at dave townsquare)
		(at coin townsquare)
		(at karina townarch)
		(at knightsword townarch)
		(at barexit bar)
		(at bankentrance townsquare)
		(at shopentrance townsquare)
		(at mushroom townarch)
		(at hutexit hut)
		(at frank townsquare)
		(at hutentrance townarch)
		(at book townarch)
		(at rope townarch)
		(at knightshield townsquare)
		(at alli junkyard)
		(at dorian townarch)
		(at peter forge)
		(at mel basement)
		(at rubyring townsquare)
		(at matthias forge)
		(at silver townsquare)
		(at shopexit shop)
		(at arthur townsquare)
		(at michael hut)
		(at bankexit bank)
		(at mel bar)
		(at forgeentrance townarch)
		(at forgeexit forge)
		(at giovanna shop)
		(at barentrance docks)
		(at ash townarch)
		(at mirror townarch)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected docks junkyard)
		(doorway townsquare valley)
		(doorway docks townarch)
		(doorway townarch townsquare)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway townsquare townarch)
		(doorway townsquare cliff)
		(has arthur loveletter)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has dorian lovecontract)
		(leadsto bankentrance bank)
		(leadsto hutexit townarch)
		(leadsto shopentrance shop)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto bankexit townsquare)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
