(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring humanskull bouquet candle bucket ash - item
		 storage basement bar docks townarch hut forge townsquare bank shop cliff mansion valley fort junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit fortentrance fortexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave giovanna jordan avery roger james ian camille phillip - character
	)
	(:init
		(at peter forge)
		(at knightshield townsquare)
		(at avery mansion)
		(at knightsword townarch)
		(at mansionexit mansion)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at jordan mansion)
		(at matthias forge)
		(at phillip fort)
		(at book townarch)
		(at candle mansion)
		(at bucket fort)
		(at oscar bar)
		(at ian fort)
		(at bankentrance townsquare)
		(at rope townarch)
		(at forgeexit forge)
		(at barentrance docks)
		(at barexit bar)
		(at bouquet cliff)
		(at mushroom docks)
		(at roger mansion)
		(at arthur fort)
		(at camille fort)
		(at mansionentrance cliff)
		(at shopexit shop)
		(at silver townsquare)
		(at basementexit basement)
		(at karina townarch)
		(at giovanna shop)
		(at fortentrance valley)
		(at basemententrance bar)
		(at rubyring shop)
		(at hutexit hut)
		(at mel storage)
		(at dave townsquare)
		(at mel bar)
		(at dorian townarch)
		(at frank townsquare)
		(at tastycupcake townarch)
		(at james valley)
		(at michael hut)
		(at fortexit fort)
		(at hutentrance townarch)
		(at mel basement)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected valley townsquare)
		(connected basement storage)
		(connected townsquare townarch)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway townsquare townarch)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway storage basement)
		(has jordan loveletter)
		(has mel basementbucket)
		(has jordan lovecontract)
		(has james coin)
		(has james humanskull)
		(has dorian rubyring)
		(has giovanna hairtonic)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto fortentrance fort)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto fortexit valley)
		(leadsto shopexit townsquare)
		(leadsto forgeexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item dorian bouquet)
		(wants-item james candle)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(and (has jordan loveletter) (has jordan lovecontract) )
			(and (has james coin) (has james humanskull) (has james candle) )
		)

	)

)
