(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit mansionentrance - entrance
		 storage basement bar docks junkyard townarch hut forge townsquare bank cliff mansion valley shop - location
		 arthur mel oscar alli dorian karina michael peter matthias frank dave jordan - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver - item
	)
	(:init
		(at alli junkyard)
		(at oscar bar)
		(at forgeentrance townarch)
		(at bankexit bank)
		(at arthur townsquare)
		(at bankentrance townsquare)
		(at jordan mansion)
		(at barexit bar)
		(at shopentrance townsquare)
		(at matthias forge)
		(at book hut)
		(at dorian townarch)
		(at mel storage)
		(at knightsword forge)
		(at basementexit basement)
		(at michael hut)
		(at forgeexit forge)
		(at mansionentrance cliff)
		(at rope forge)
		(at dave townsquare)
		(at hutentrance townarch)
		(at mel basement)
		(at peter forge)
		(at tastycupcake hut)
		(at frank townsquare)
		(at mel bar)
		(at hutexit hut)
		(at barentrance docks)
		(at basemententrance bar)
		(at hairtonic hut)
		(at karina townarch)
		(closed basemententrance)
		(closed shopentrance)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townarch docks)
		(connected townsquare valley)
		(connected storage basement)
		(connected basement storage)
		(connected townsquare townarch)
		(connected cliff townsquare)
		(connected docks townarch)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway junkyard docks)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(has arthur mirror)
		(has dorian lovecontract)
		(has arthur mushroom)
		(has alli ash)
		(has dorian loveletter)
		(has arthur coin)
		(has mel basementbucket)
		(has arthur silver)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur loveletter)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur coin)
	)
	(:goal
	)
)
