(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle coin silver bucket knightshield rubyring knightsword rope ash hairtonic - item
		 storage basement bar docks townarch townsquare valley cliff mansion bank fort shop forge junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance mansionexit bankexit fortexit shopexit forgeexit - entrance
		 arthur mel oscar dorian karina frank dave james jordan avery roger ian camille phillip giovanna peter matthias - character
	)
	(:init
		(at shopexit shop)
		(at james valley)
		(at ian fort)
		(at bankentrance townsquare)
		(at forgeexit forge)
		(at avery mansion)
		(at candle mansion)
		(at roger mansion)
		(at dave townsquare)
		(at matthias forge)
		(at bucket fort)
		(at basemententrance bar)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at oscar bar)
		(at mel storage)
		(at phillip fort)
		(at dorian townarch)
		(at mel bar)
		(at barentrance docks)
		(at hutentrance townarch)
		(at humanskull cliff)
		(at camille fort)
		(at karina townarch)
		(at jordan mansion)
		(at peter forge)
		(at basementexit basement)
		(at barexit bar)
		(at arthur forge)
		(at mel basement)
		(at fortexit fort)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at fortentrance valley)
		(at mansionexit mansion)
		(at frank townsquare)
		(closed basemententrance)
		(closed hutentrance)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected townsquare townarch)
		(connected basement storage)
		(connected cliff townsquare)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected townarch townsquare)
		(connected storage basement)
		(connected townarch docks)
		(connected docks townarch)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(has arthur silver)
		(has arthur rope)
		(has james coin)
		(has arthur rubyring)
		(has arthur knightsword)
		(has jordan loveletter)
		(has dorian bouquet)
		(has arthur knightshield)
		(has jordan lovecontract)
		(has arthur mushroom)
		(has mel basementbucket)
		(leadsto bankexit townsquare)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto fortexit valley)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(leadsto bankentrance bank)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item ian knightsword)
		(wants-item dorian rubyring)
		(wants-item james humanskull)
		(wants-item ian knightshield)
		(wants-item giovanna hairtonic)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur knightshield)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur rubyring)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) 
			)

		)
	)

)
