(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle rubyring ash - item
		 storage basement bar docks townarch townsquare valley cliff mansion shop junkyard forge bank fort hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina frank dave james jordan avery roger - character
	)
	(:init
		(at mansionentrance cliff)
		(at frank townsquare)
		(at fortentrance valley)
		(at shopentrance townsquare)
		(at bouquet cliff)
		(at bankentrance townsquare)
		(at forgeentrance townarch)
		(at basemententrance bar)
		(at barentrance docks)
		(at candle mansion)
		(at arthur mansion)
		(at basementexit basement)
		(at dave townsquare)
		(at mel bar)
		(at oscar bar)
		(at mansionexit mansion)
		(at james valley)
		(at rubyring shop)
		(at barexit bar)
		(at hutentrance townarch)
		(at jordan mansion)
		(at humanskull cliff)
		(at dorian townarch)
		(at mel storage)
		(at karina townarch)
		(at mel basement)
		(at roger mansion)
		(at avery mansion)
		(closed hutentrance)
		(closed fortentrance)
		(closed bankentrance)
		(closed shopentrance)
		(closed forgeentrance)
		(closed basemententrance)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected storage basement)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected basement storage)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected townarch docks)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(doorway storage basement)
		(has dorian lovecontract)
		(has arthur shinykey)
		(has jordan loveletter)
		(has arthur mushroom)
		(has mel basementbucket)
		(leadsto bankentrance bank)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto mansionexit cliff)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
