(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope knightshield rubyring coin silver humanskull bouquet candle - item
		 storage basement bar docks junkyard townarch hut forge townsquare shop bank cliff mansion valley - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance shopexit bankexit mansionentrance mansionexit - entrance
		 arthur mel oscar alli dorian karina michael peter matthias frank dave giovanna jordan avery roger - character
	)
	(:init
		(at alli junkyard)
		(at michael hut)
		(at knightsword forge)
		(at hutentrance townarch)
		(at bankexit bank)
		(at forgeexit forge)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at barexit bar)
		(at jordan mansion)
		(at matthias forge)
		(at bankentrance townsquare)
		(at knightshield shop)
		(at bouquet cliff)
		(at candle mansion)
		(at barentrance docks)
		(at oscar bar)
		(at coin bank)
		(at dave townsquare)
		(at humanskull cliff)
		(at dorian townarch)
		(at basemententrance bar)
		(at roger mansion)
		(at karina townarch)
		(at avery mansion)
		(at rubyring shop)
		(at book docks)
		(at shopexit shop)
		(at mel bar)
		(at frank townsquare)
		(at mansionexit mansion)
		(at hutexit hut)
		(at giovanna shop)
		(at mel basement)
		(at silver bank)
		(at peter forge)
		(at basementexit basement)
		(at arthur mansion)
		(at rope forge)
		(at mel storage)
		(at mansionentrance cliff)
		(connected storage basement)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected townarch townsquare)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected basement storage)
		(connected docks townarch)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(has arthur mirror)
		(has arthur ash)
		(has dorian lovecontract)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(has jordan loveletter)
		(has arthur mushroom)
		(leadsto barentrance bar)
		(leadsto bankexit townsquare)
		(leadsto forgeexit townarch)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto shopexit townsquare)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
