(open arthur barexit bar)
(move-through-entrance arthur bar barexit docks)
(pickup arthur mushroom docks)
(close arthur barentrance docks )
(move-through-doorway arthur docks townarch)
(give dorian loveletter arthur townarch)
(give dorian lovecontract arthur townarch)
(move-through-door arthur townarch towngate townsquare)
(move-through-doorway arthur townsquare cliff)
(pickup arthur bouquet cliff)
(move-through-doorway arthur cliff townsquare)
(move-through-door arthur townsquare towngate townarch)
(give arthur bouquet dorian townarch)
(open arthur hutentrance townarch)
(move-through-entrance arthur townarch hutentrance hut)
(pickup arthur hairtonic hut)
(pickup arthur tastycupcake hut)
(move-through-entrance arthur hut hutexit townarch)
(move-through-doorway arthur townarch docks)
(drop arthur mushroom docks)
(pickup arthur mushroom docks )
(move-through-doorway arthur docks junkyard )
(give arthur tastycupcake alli junkyard)
(drop arthur loveletter junkyard)
(drop arthur lovecontract junkyard)
(drop arthur hairtonic junkyard)
(move-through-doorway arthur junkyard docks)
(open arthur barentrance docks)
(move-through-entrance arthur docks barentrance bar)
(close arthur barexit bar)
(open arthur basemententrance bar)
(move-through-entrance arthur bar basemententrance basement)
(move-through-entrance arthur basement basementexit bar)
(open arthur barexit bar)
(move-through-entrance arthur bar barexit docks)
(move-through-doorway arthur docks townarch)
(move-through-doorway arthur townarch docks )
(move-through-doorway arthur docks junkyard )
(move-through-doorway arthur junkyard docks)
(move-through-doorway arthur docks townarch)
(move-through-doorway arthur townarch docks )
(close arthur barentrance docks)
(open arthur barentrance docks )
(move-through-entrance arthur docks barentrance bar )
(close arthur barexit bar )
(open arthur barexit bar)
(move-through-entrance arthur bar barexit docks)
(close arthur barentrance docks )
(move-through-doorway arthur docks junkyard )
(pickup arthur hairtonic junkyard)
(pickup arthur lovecontract junkyard)
(pickup arthur loveletter junkyard)
(move-through-doorway arthur junkyard docks)
(move-through-doorway arthur docks townarch)
(move-through-door arthur townarch towngate townsquare)
(move-through-doorway arthur townsquare cliff)
(open arthur mansionentrance cliff)
(move-through-entrance arthur cliff mansionentrance mansion)
(give arthur loveletter jordan mansion)
(give arthur lovecontract jordan mansion)
(move-through-entrance arthur mansion mansionexit cliff)
(move-through-doorway arthur cliff townsquare)
(open arthur shopentrance townsquare)
(move-through-entrance arthur townsquare shopentrance shop)
(give arthur hairtonic giovanna shop)
