(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance mansionentrance hutexit bankentrance - entrance
		 storage basement bar docks junkyard townarch hut cliff mansion townsquare forge - location
		 arthur mel oscar alli dorian karina jordan - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake - item
	)
	(:init
		(at mel bar)
		(at forgeentrance townarch)
		(at arthur townarch)
		(at barexit bar)
		(at dorian townarch)
		(at hutexit hut)
		(at oscar bar)
		(at basemententrance bar)
		(at jordan mansion)
		(at karina townarch)
		(at mel storage)
		(at barentrance docks)
		(at mel basement)
		(at tastycupcake hut)
		(at basementexit basement)
		(at alli junkyard)
		(at hutentrance townarch)
		(at mansionentrance cliff)
		(closed forgeentrance)
		(connected junkyard docks)
		(connected docks junkyard)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected storage basement)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected basement storage)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway docks junkyard)
		(has dorian lovecontract)
		(has arthur mirror)
		(has arthur shinykey)
		(has arthur loveletter)
		(has alli ash)
		(has arthur mushroom)
		(has mel basementbucket)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item alli tastycupcake)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
