(close arthur mansionentrance cliff)
(move-through-doorway arthur cliff townsquare)
(move-through-door arthur townsquare towngate townarch)
(move-through-entrance arthur townarch forgeentrance forge)
(pickup arthur rubyring forge)
(pickup arthur rope forge)
(pickup arthur mirror forge)
(drop arthur rubyring forge )
(drop arthur mirror forge )
(drop arthur rope forge )
(move-through-entrance arthur forge forgeexit townarch )
(move-through-door arthur townarch towngate townsquare )
(move-through-doorway arthur townsquare cliff )
(open arthur mansionentrance cliff )
(pickup arthur humanskull cliff)
(move-through-doorway arthur cliff townsquare)
(move-through-doorway arthur townsquare valley)
(give arthur humanskull james valley)
(move-through-entrance arthur valley fortentrance fort)
(give arthur knightshield ian fort)
(give arthur knightsword ian fort)
(move-through-entrance arthur fort fortexit valley)
(move-through-doorway arthur valley townsquare)
(move-through-doorway arthur townsquare cliff )
(move-through-entrance arthur cliff mansionentrance mansion)
(give arthur loveletter jordan mansion)
