(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake coin - item
		 storage basement bar docks junkyard townarch townsquare valley hut cliff mansion bank forge shop fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance fortentrance mansionentrance hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave james jordan - character
	)
	(:init
		(at dave townsquare)
		(at bankentrance townsquare)
		(at mirror docks)
		(at shopentrance townsquare)
		(at frank townsquare)
		(at oscar bar)
		(at mel storage)
		(at mel basement)
		(at basemententrance bar)
		(at basementexit basement)
		(at alli junkyard)
		(at james valley)
		(at fortentrance valley)
		(at barentrance docks)
		(at karina townarch)
		(at mel bar)
		(at hutexit hut)
		(at dorian townarch)
		(at barexit bar)
		(at arthur valley)
		(at jordan mansion)
		(at mansionentrance cliff)
		(at hutentrance townarch)
		(at tastycupcake hut)
		(at forgeentrance townarch)
		(closed hutentrance)
		(closed basemententrance)
		(closed fortentrance)
		(closed shopentrance)
		(closed forgeentrance)
		(closed bankentrance)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected townsquare valley)
		(connected docks junkyard)
		(connected townarch docks)
		(connected basement storage)
		(connected storage basement)
		(connected townarch townsquare)
		(doorway junkyard docks)
		(doorway townarch townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway townsquare townarch)
		(has alli ash)
		(has arthur mushroom)
		(has mel basementbucket)
		(has arthur loveletter)
		(has arthur shinykey)
		(has dorian lovecontract)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto fortentrance fort)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item alli tastycupcake)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item james coin)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
