(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan avery roger james ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book knightshield rubyring coin silver humanskull bouquet candle bucket - item
		 storage basement bar docks junkyard townarch forge hut townsquare shop bank cliff mansion valley fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance shopexit bankexit mansionentrance mansionexit fortentrance fortexit - entrance
	)
	(:init
		(at james valley)
		(at karina townarch)
		(at mansionexit mansion)
		(at fortentrance valley)
		(at dorian townarch)
		(at knightshield shop)
		(at fortexit fort)
		(at michael hut)
		(at knightsword forge)
		(at barentrance docks)
		(at hutentrance townarch)
		(at mel basement)
		(at mansionentrance cliff)
		(at phillip fort)
		(at giovanna shop)
		(at arthur forge)
		(at mirror townarch)
		(at hutexit hut)
		(at shopexit shop)
		(at mel bar)
		(at avery mansion)
		(at dave townsquare)
		(at ash townarch)
		(at peter forge)
		(at bankentrance townsquare)
		(at mushroom townarch)
		(at ian fort)
		(at camille fort)
		(at bucket fort)
		(at forgeexit forge)
		(at alli junkyard)
		(at rope townarch)
		(at candle mansion)
		(at silver townsquare)
		(at roger mansion)
		(at frank townsquare)
		(at barexit bar)
		(at rubyring shop)
		(at jordan mansion)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at book townarch)
		(at matthias forge)
		(connected docks junkyard)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected valley townsquare)
		(connected junkyard docks)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townarch townsquare)
		(connected townsquare townarch)
		(connected townsquare valley)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(has arthur knightsword)
		(has arthur rubyring)
		(has alli tastycupcake)
		(has arthur knightshield)
		(has dorian bouquet)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has james coin)
		(has james humanskull)
		(leadsto mansionexit cliff)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto bankexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item ian knightsword)
		(wants-item dorian rubyring)
		(wants-item arthur shinykey)
		(wants-item james candle)
		(wants-item ian knightshield)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightshield)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur ash)
		(has giovanna hairtonic)
		(has jordan lovecontract)
		(has james coin)
		(has james humanskull)
		(has ian knightsword)
		(has ian knightshield)
		(has james candle)
	  )
	)
)
