(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book knightshield rubyring coin silver - item
		 storage basement bar docks junkyard townarch forge hut townsquare shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance shopexit bankexit - entrance
	)
	(:init
		(at mel bar)
		(at alli junkyard)
		(at frank townsquare)
		(at michael hut)
		(at mel basement)
		(at shopexit shop)
		(at rope townarch)
		(at knightshield townsquare)
		(at peter forge)
		(at giovanna shop)
		(at rubyring townsquare)
		(at ash townarch)
		(at dave townsquare)
		(at arthur townsquare)
		(at bankexit bank)
		(at barentrance docks)
		(at mirror townarch)
		(at silver townsquare)
		(at barexit bar)
		(at shopentrance townsquare)
		(at dorian townarch)
		(at mushroom townarch)
		(at bankentrance townsquare)
		(at book townarch)
		(at knightsword townarch)
		(at forgeexit forge)
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at hutexit hut)
		(at matthias forge)
		(at karina townarch)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected townsquare valley)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected docks junkyard)
		(connected townarch townsquare)
		(doorway townsquare townarch)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(has alli tastycupcake)
		(has dorian lovecontract)
		(has giovanna hairtonic)
		(has arthur loveletter)
		(has arthur coin)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto bankexit townsquare)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto hutentrance hut)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur coin)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur ash)
		(has giovanna hairtonic)
	  )
	)
)
