(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter - item
		 storage basement bar docks junkyard townarch - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance - entrance
	)
	(:init
		(at mel basement)
		(at mel bar)
		(at hutexit hut)
		(at tastycupcake hut)
		(at karina townarch)
		(at dorian townarch)
		(at mirror townarch)
		(at forgeentrance townarch)
		(at barexit bar)
		(at mushroom townarch)
		(at arthur townarch)
		(at hutentrance townarch)
		(at shinykey townarch)
		(closed hutentrance)
		(connected junkyard docks)
		(connected townarch docks)
		(connected townarch townsquare)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(has alli ash)
		(has arthur loveletter)
		(has dorian lovecontract)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
	  )
	)
)
