(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina peter matthias michael frank dave giovanna jordan avery roger james ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book knightshield rubyring coin silver humanskull bouquet candle bucket - item
		 storage basement bar docks junkyard townarch forge hut townsquare shop bank cliff mansion valley fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance shopexit bankexit mansionentrance mansionexit fortentrance fortexit - entrance
	)
	(:init
		(at mel bar)
		(at hutexit hut)
		(at fortentrance valley)
		(at dave townsquare)
		(at dorian townarch)
		(at james valley)
		(at knightsword forge)
		(at knightshield shop)
		(at barentrance docks)
		(at humanskull cliff)
		(at mansionexit mansion)
		(at hutentrance townarch)
		(at roger mansion)
		(at alli junkyard)
		(at mansionentrance cliff)
		(at karina townarch)
		(at shopexit shop)
		(at silver townsquare)
		(at phillip fort)
		(at mirror townarch)
		(at avery mansion)
		(at giovanna shop)
		(at rubyring shop)
		(at mel basement)
		(at arthur townsquare)
		(at peter forge)
		(at camille fort)
		(at mushroom townarch)
		(at ian fort)
		(at bankentrance townsquare)
		(at knightsword townarch)
		(at rubyring townsquare)
		(at forgeexit forge)
		(at bucket fort)
		(at rope townarch)
		(at candle mansion)
		(at forgeentrance townarch)
		(at ash townarch)
		(at michael hut)
		(at jordan mansion)
		(at barexit bar)
		(at frank townsquare)
		(at book townarch)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at matthias forge)
		(at fortexit fort)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townarch docks)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway junkyard docks)
		(doorway docks townarch)
		(has giovanna hairtonic)
		(has jordan lovecontract)
		(has arthur knightshield)
		(has dorian bouquet)
		(has alli tastycupcake)
		(has jordan loveletter)
		(has james coin)
		(leadsto forgeexit townarch)
		(leadsto bankexit townsquare)
		(leadsto hutentrance hut)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto fortexit valley)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto mansionexit cliff)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item james humanskull)
		(wants-item dorian rubyring)
		(wants-item ian knightsword)
		(wants-item arthur shinykey)
		(wants-item ian knightshield)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightshield)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur ash)
		(has giovanna hairtonic)
		(has jordan lovecontract)
		(has james coin)
		(has james humanskull)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
