(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina peter matthias michael frank dave - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch forge hut townsquare - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance - entrance
	)
	(:init
		(at matthias forge)
		(at ash townarch)
		(at dave townsquare)
		(at barentrance docks)
		(at knightsword townarch)
		(at arthur townsquare)
		(at mel basement)
		(at dorian townarch)
		(at mirror townarch)
		(at forgeexit forge)
		(at hairtonic townarch)
		(at mel bar)
		(at michael hut)
		(at frank townsquare)
		(at bankentrance townsquare)
		(at rope townarch)
		(at shopentrance townsquare)
		(at shinykey townarch)
		(at karina townarch)
		(at book townarch)
		(at hutentrance townarch)
		(at alli junkyard)
		(at hutexit hut)
		(at peter forge)
		(at barexit bar)
		(at forgeentrance townarch)
		(at mushroom townarch)
		(closed bankentrance)
		(closed shopentrance)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townarch docks)
		(connected townsquare valley)
		(connected townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway junkyard docks)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has alli tastycupcake)
		(leadsto hutentrance hut)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(locked bankentrance)
		(player arthur)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur ash)
	  )
	)
)
