(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina peter matthias michael - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book - item
		 storage basement bar docks junkyard townarch forge hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit - entrance
	)
	(:init
		(at barentrance docks)
		(at mansionentrance cliff)
		(at hairtonic hut)
		(at peter forge)
		(at mel storage)
		(at michael hut)
		(at mel bar)
		(at mirror townarch)
		(at matthias forge)
		(at forgeentrance townarch)
		(at rope forge)
		(at alli junkyard)
		(at karina townarch)
		(at forgeexit forge)
		(at dorian townarch)
		(at basemententrance bar)
		(at oscar bar)
		(at mel basement)
		(at basementexit basement)
		(at hutentrance townarch)
		(at book hut)
		(at hutexit hut)
		(at tastycupcake hut)
		(at mushroom townarch)
		(at shinykey townarch)
		(at arthur townarch)
		(at barexit bar)
		(at jordan mansion)
		(closed basemententrance)
		(closed barentrance)
		(connected basement storage)
		(connected docks townarch)
		(connected storage basement)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townsquare cliff)
		(doorway junkyard docks)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway townarch townsquare)
		(has mel basementbucket)
		(has arthur knightsword)
		(has dorian lovecontract)
		(has alli ash)
		(has arthur loveletter)
		(leadsto mansionentrance mansion)
		(leadsto forgeexit townarch)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto barentrance bar)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto barexit docks)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has jordan loveletter)
	  )
	)
)
