(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 towngate - door
		 arthur mel oscar dorian karina frank dave jordan avery roger james ian camille phillip giovanna peter matthias - character
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter humanskull bouquet candle bucket knightshield rubyring coin silver knightsword rope - item
		 storage basement bar docks townarch townsquare cliff mansion valley fort shop bank forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance mansionexit fortentrance fortexit shopexit bankexit forgeexit - entrance
	)
	(:init
		(at mansionentrance cliff)
		(at giovanna shop)
		(at fortexit fort)
		(at shopexit shop)
		(at rubyring shop)
		(at mushroom docks)
		(at karina townarch)
		(at fortentrance valley)
		(at mansionexit mansion)
		(at barentrance docks)
		(at roger mansion)
		(at mel basement)
		(at mel bar)
		(at ian fort)
		(at camille fort)
		(at basementexit basement)
		(at frank townsquare)
		(at basemententrance bar)
		(at forgeexit forge)
		(at mel storage)
		(at bucket fort)
		(at dave townsquare)
		(at arthur fort)
		(at avery mansion)
		(at peter forge)
		(at dorian townarch)
		(at hutentrance townarch)
		(at james valley)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at phillip fort)
		(at matthias forge)
		(at forgeentrance townarch)
		(at candle mansion)
		(at oscar bar)
		(at silver bank)
		(at bankentrance townsquare)
		(at jordan mansion)
		(at barexit bar)
		(closed hutentrance)
		(connected storage basement)
		(connected docks junkyard)
		(connected basement storage)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected townsquare valley)
		(connected townarch townsquare)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway cliff townsquare)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway valley townsquare)
		(has mel basementbucket)
		(has james humanskull)
		(has james coin)
		(has jordan loveletter)
		(has dorian bouquet)
		(has arthur knightsword)
		(has arthur rope)
		(has jordan lovecontract)
		(has ian knightshield)
		(leadsto forgeexit townarch)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto fortexit valley)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(leadsto shopexit townsquare)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item ian knightsword)
		(wants-item dorian rubyring)
		(wants-item arthur ash)
		(wants-item giovanna hairtonic)
		(wants-item james candle)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rope)
	)
	(:goal
	  (AND
		
		(not (locked basementexit))
		(has jordan loveletter)
		(has james coin)
		(has ian knightsword)
		(has ian knightshield)
		(has jordan lovecontract)
		(has giovanna hairtonic)
		(has james humanskull)
		(has james candle)
	  )
	)
)
