(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit bankexit - entrance
		 storage basement bar docks junkyard townarch hut forge townsquare valley cliff mansion shop bank fort - location
		 arthur mel oscar alli dorian karina michael peter matthias frank dave james jordan avery roger giovanna - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle knightshield rubyring coin silver - item
	)
	(:init
		(at hutexit hut)
		(at forgeentrance townarch)
		(at silver bank)
		(at bankexit bank)
		(at arthur bank)
		(at dave townsquare)
		(at avery mansion)
		(at peter forge)
		(at bankentrance townsquare)
		(at barexit bar)
		(at coin bank)
		(at hutentrance townarch)
		(at oscar bar)
		(at bouquet cliff)
		(at basemententrance bar)
		(at shopentrance townsquare)
		(at candle mansion)
		(at barentrance docks)
		(at matthias forge)
		(at jordan mansion)
		(at mel bar)
		(at mel storage)
		(at mel basement)
		(at fortentrance valley)
		(at forgeexit forge)
		(at frank townsquare)
		(at alli junkyard)
		(at knightsword forge)
		(at basementexit basement)
		(at mirror junkyard)
		(at knightshield shop)
		(at mansionexit mansion)
		(at james valley)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at michael hut)
		(at shopexit shop)
		(at karina townarch)
		(at dorian townarch)
		(at roger mansion)
		(at book hut)
		(at humanskull cliff)
		(closed basemententrance)
		(closed fortentrance)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected townsquare valley)
		(connected docks townarch)
		(connected storage basement)
		(connected valley townsquare)
		(connected basement storage)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected townarch townsquare)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway basement storage)
		(has arthur rope)
		(has arthur rubyring)
		(has giovanna hairtonic)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has alli tastycupcake)
		(has arthur mushroom)
		(has arthur ash)
		(has mel basementbucket)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(leadsto mansionexit cliff)
		(leadsto shopentrance shop)
		(leadsto bankexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto shopexit townsquare)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto forgeexit townarch)
		(leadsto mansionentrance mansion)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
