(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina peter matthias michael frank dave james ian camille phillip jordan avery roger giovanna - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book bucket humanskull bouquet candle knightshield rubyring coin silver - item
		 storage basement bar docks junkyard townarch forge hut townsquare valley fort cliff mansion shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance fortentrance fortexit mansionentrance mansionexit shopexit bankexit - entrance
	)
	(:init
		(at ian fort)
		(at fortentrance valley)
		(at camille fort)
		(at frank townsquare)
		(at forgeexit forge)
		(at hutexit hut)
		(at rope forge)
		(at avery mansion)
		(at basemententrance bar)
		(at mansionexit mansion)
		(at knightshield shop)
		(at phillip fort)
		(at karina townarch)
		(at humanskull cliff)
		(at dorian townarch)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at alli junkyard)
		(at book docks)
		(at basementexit basement)
		(at mel bar)
		(at roger mansion)
		(at mel basement)
		(at bankentrance townsquare)
		(at silver bank)
		(at coin bank)
		(at forgeentrance townarch)
		(at mushroom townarch)
		(at bucket fort)
		(at dave townsquare)
		(at candle mansion)
		(at james valley)
		(at oscar bar)
		(at knightsword forge)
		(at hutentrance townarch)
		(at peter forge)
		(at barexit bar)
		(at mel storage)
		(at fortexit fort)
		(at michael hut)
		(at jordan mansion)
		(at barentrance docks)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at arthur bank)
		(at matthias forge)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected basement storage)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected docks townarch)
		(doorway townsquare townarch)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(has arthur ash)
		(has mel basementbucket)
		(has giovanna hairtonic)
		(has arthur bouquet)
		(has alli tastycupcake)
		(has dorian lovecontract)
		(has arthur mirror)
		(has jordan loveletter)
		(has arthur rubyring)
		(leadsto fortentrance fort)
		(leadsto shopexit townsquare)
		(leadsto fortexit valley)
		(leadsto forgeentrance forge)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto bankentrance bank)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto shopentrance shop)
		(leadsto mansionexit cliff)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item james coin)
		(wants-item dorian rubyring)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item dorian bouquet)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur ash)
		(has james coin)
		(has giovanna hairtonic)
	  )
	)
)
