(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina peter matthias michael frank dave james ian camille phillip jordan avery roger giovanna - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter knightsword rope tastycupcake hairtonic book bucket humanskull bouquet candle knightshield rubyring coin silver - item
		 storage basement bar docks junkyard townarch forge hut townsquare valley fort cliff mansion shop bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit hutexit shopentrance bankentrance fortentrance fortexit mansionentrance mansionexit shopexit bankexit - entrance
	)
	(:init
		(at avery mansion)
		(at silver bank)
		(at mansionexit mansion)
		(at fortentrance valley)
		(at phillip fort)
		(at knightshield shop)
		(at peter forge)
		(at james valley)
		(at forgeexit forge)
		(at barentrance docks)
		(at dave townsquare)
		(at mel basement)
		(at karina townarch)
		(at shopexit shop)
		(at giovanna shop)
		(at mansionentrance cliff)
		(at roger mansion)
		(at mel bar)
		(at hutexit hut)
		(at ian fort)
		(at alli junkyard)
		(at book docks)
		(at hutentrance townarch)
		(at dorian townarch)
		(at basementexit basement)
		(at frank townsquare)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at camille fort)
		(at bucket fort)
		(at oscar bar)
		(at rope forge)
		(at basemententrance bar)
		(at mel storage)
		(at matthias forge)
		(at knightsword forge)
		(at shopentrance townsquare)
		(at jordan mansion)
		(at fortexit fort)
		(at michael hut)
		(at mushroom townarch)
		(at barexit bar)
		(at forgeentrance townarch)
		(at bankexit bank)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected junkyard docks)
		(connected basement storage)
		(connected docks junkyard)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare valley)
		(doorway townarch townsquare)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway junkyard docks)
		(doorway townsquare townarch)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townsquare valley)
		(doorway basement storage)
		(has mel basementbucket)
		(has dorian bouquet)
		(has arthur rubyring)
		(has jordan lovecontract)
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has arthur humanskull)
		(has arthur candle)
		(has arthur mirror)
		(has arthur ash)
		(has james coin)
		(has alli tastycupcake)
		(leadsto fortexit valley)
		(leadsto basementexit bar)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto bankexit townsquare)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item dorian rubyring)
		(wants-item james humanskull)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur candle)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur humanskull)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur rubyring)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has arthur ash)
		(has james coin)
		(has giovanna hairtonic)
		(has james humanskull)
		(has jordan lovecontract)
	  )
	)
)
