(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring humanskull bouquet candle ash - item
		 storage basement bar docks townarch hut forge townsquare bank shop cliff mansion junkyard valley - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave giovanna jordan avery roger - character
	)
	(:init
		(at mushroom docks)
		(at dave townsquare)
		(at knightshield townsquare)
		(at humanskull cliff)
		(at coin townsquare)
		(at michael hut)
		(at hutentrance townarch)
		(at mansionexit mansion)
		(at book townarch)
		(at frank townsquare)
		(at shopentrance townsquare)
		(at jordan mansion)
		(at matthias forge)
		(at bankexit bank)
		(at rope townarch)
		(at candle mansion)
		(at bankentrance townsquare)
		(at oscar bar)
		(at bouquet cliff)
		(at barexit bar)
		(at barentrance docks)
		(at dorian townarch)
		(at forgeexit forge)
		(at roger mansion)
		(at silver townsquare)
		(at arthur townarch)
		(at avery mansion)
		(at knightsword townarch)
		(at rubyring shop)
		(at karina townarch)
		(at mel storage)
		(at mel bar)
		(at mel basement)
		(at forgeentrance townarch)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at peter forge)
		(at basementexit basement)
		(at tastycupcake townarch)
		(at basemententrance bar)
		(at hutexit hut)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected storage basement)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected docks townarch)
		(connected basement storage)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townarch docks)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway basement storage)
		(doorway townarch townsquare)
		(doorway cliff townsquare)
		(has dorian rubyring)
		(has jordan lovecontract)
		(has giovanna hairtonic)
		(has jordan loveletter)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto bankexit townsquare)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto mansionexit cliff)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item dorian bouquet)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
