(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring humanskull bouquet candle ash - item
		 storage basement bar docks townarch hut forge townsquare bank shop cliff mansion junkyard valley - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave giovanna jordan avery roger - character
	)
	(:init
		(at knightshield townsquare)
		(at bankentrance townsquare)
		(at basementexit basement)
		(at rope townarch)
		(at forgeexit forge)
		(at oscar bar)
		(at bouquet cliff)
		(at rubyring townsquare)
		(at candle mansion)
		(at barentrance docks)
		(at frank townsquare)
		(at book townarch)
		(at michael hut)
		(at jordan mansion)
		(at coin townsquare)
		(at shopentrance townsquare)
		(at tastycupcake townarch)
		(at arthur mansion)
		(at bankexit bank)
		(at matthias forge)
		(at basemententrance bar)
		(at peter forge)
		(at forgeentrance townarch)
		(at dave townsquare)
		(at mansionexit mansion)
		(at hutexit hut)
		(at avery mansion)
		(at dorian townarch)
		(at barexit bar)
		(at hutentrance townarch)
		(at roger mansion)
		(at humanskull cliff)
		(at mel storage)
		(at karina townarch)
		(at silver townsquare)
		(at giovanna shop)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at mushroom docks)
		(at knightsword townarch)
		(at mel basement)
		(at mel bar)
		(connected townsquare cliff)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected storage basement)
		(connected docks townarch)
		(connected townarch docks)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townarch townsquare)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway storage basement)
		(has dorian lovecontract)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(has arthur loveletter)
		(leadsto bankexit townsquare)
		(leadsto mansionexit cliff)
		(leadsto hutexit townarch)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto barexit docks)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto basemententrance basement)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item jordan lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has jordan loveletter) 
		)

	)

)
