(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring humanskull bouquet candle ash - item
		 storage basement bar docks townarch hut forge townsquare bank shop cliff mansion junkyard valley - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave giovanna jordan avery roger - character
	)
	(:init
		(at giovanna shop)
		(at coin townsquare)
		(at rubyring shop)
		(at frank townsquare)
		(at book townarch)
		(at shopentrance townsquare)
		(at matthias forge)
		(at jordan mansion)
		(at candle mansion)
		(at roger mansion)
		(at arthur townsquare)
		(at bankentrance townsquare)
		(at bankexit bank)
		(at bouquet cliff)
		(at forgeexit forge)
		(at mel storage)
		(at oscar bar)
		(at barexit bar)
		(at barentrance docks)
		(at rope townarch)
		(at mushroom docks)
		(at silver townsquare)
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at mel basement)
		(at karina townarch)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at basementexit basement)
		(at dave townsquare)
		(at knightsword townarch)
		(at mansionexit mansion)
		(at basemententrance bar)
		(at mel bar)
		(at hutexit hut)
		(at tastycupcake townarch)
		(at knightshield townsquare)
		(at michael hut)
		(at avery mansion)
		(at dorian townarch)
		(at humanskull cliff)
		(at peter forge)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townarch docks)
		(connected basement storage)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway basement storage)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway townarch docks)
		(has jordan lovecontract)
		(has giovanna hairtonic)
		(has jordan loveletter)
		(has dorian rubyring)
		(has mel basementbucket)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item dorian bouquet)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
