(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book ash - item
		 storage basement bar docks townarch hut cliff mansion townsquare junkyard forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit mansionentrance bankentrance - entrance
		 arthur mel oscar dorian karina michael jordan - character
	)
	(:init
		(at mel basement)
		(at hutexit hut)
		(at forgeentrance townarch)
		(at mushroom docks)
		(at dorian townarch)
		(at barexit bar)
		(at arthur townarch)
		(at hutentrance townarch)
		(at michael hut)
		(at karina townarch)
		(at jordan mansion)
		(at oscar bar)
		(at mel bar)
		(at basementexit basement)
		(at mansionentrance cliff)
		(at barentrance docks)
		(at mel storage)
		(at basemententrance bar)
		(closed forgeentrance)
		(connected storage basement)
		(connected townsquare cliff)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected basement storage)
		(connected docks townarch)
		(connected townarch townsquare)
		(connected townarch docks)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(has dorian lovecontract)
		(has arthur tastycupcake)
		(has arthur book)
		(has arthur loveletter)
		(has arthur shinykey)
		(has arthur hairtonic)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto basementexit bar)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur book)
		(willing-to-give-item arthur tastycupcake)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur hairtonic)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
