(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring humanskull bouquet candle bucket mirror ash - item
		 storage basement bar docks townarch hut forge townsquare bank shop cliff mansion valley fort junkyard - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit shopexit mansionentrance mansionexit fortentrance fortexit - entrance
		 arthur mel oscar dorian karina michael peter matthias frank dave giovanna jordan avery roger james ian camille phillip alli - character
	)
	(:init
		(at shopexit shop)
		(at basementexit basement)
		(at avery mansion)
		(at tastycupcake valley)
		(at book townarch)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at matthias forge)
		(at barexit bar)
		(at jordan mansion)
		(at phillip fort)
		(at forgeentrance townarch)
		(at candle mansion)
		(at bucket fort)
		(at oscar bar)
		(at rope valley)
		(at bouquet cliff)
		(at ian fort)
		(at bankentrance townsquare)
		(at knightshield shop)
		(at forgeexit forge)
		(at mirror junkyard)
		(at mushroom docks)
		(at camille fort)
		(at peter forge)
		(at arthur junkyard)
		(at basemententrance bar)
		(at barentrance docks)
		(at dave townsquare)
		(at roger mansion)
		(at silver townsquare)
		(at karina townarch)
		(at mansionentrance cliff)
		(at hutexit hut)
		(at fortentrance valley)
		(at rubyring shop)
		(at mel bar)
		(at mansionexit mansion)
		(at mel basement)
		(at fortexit fort)
		(at giovanna shop)
		(at frank townsquare)
		(at knightsword forge)
		(at michael hut)
		(at james valley)
		(at hutentrance townarch)
		(at alli junkyard)
		(at mel storage)
		(at dorian townarch)
		(connected townarch townsquare)
		(connected storage basement)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected docks townarch)
		(connected basement storage)
		(connected docks junkyard)
		(connected valley townsquare)
		(connected junkyard docks)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected townsquare townarch)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway townsquare townarch)
		(doorway basement storage)
		(doorway valley townsquare)
		(has ian knightshield)
		(has jordan loveletter)
		(has james coin)
		(has alli ash)
		(has james humanskull)
		(has giovanna hairtonic)
		(has jordan lovecontract)
		(has dorian rubyring)
		(has mel basementbucket)
		(has ian knightsword)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto fortentrance fort)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto fortexit valley)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item dorian bouquet)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item james candle)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
	)
	(:goal
		(or
			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has ian knightsword) (has ian knightshield) 
				(has giovanna hairtonic) 
				(has jordan loveletter) (has jordan lovecontract) 
				(has james coin) (has james humanskull) (has james candle) 
			)

		)
	)

)
