(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book knightsword rope ash - item
		 storage basement bar docks townarch hut forge mansion cliff junkyard townsquare - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit mansionentrance bankentrance - entrance
		 arthur mel oscar dorian karina michael peter matthias jordan - character
	)
	(:init
		(at rope forge)
		(at arthur forge)
		(at hairtonic townarch)
		(at mel basement)
		(at dorian townarch)
		(at shinykey townarch)
		(at barexit bar)
		(at knightsword forge)
		(at book townarch)
		(at hutentrance townarch)
		(at forgeexit forge)
		(at hutexit hut)
		(at mushroom docks)
		(at mansionentrance cliff)
		(at matthias forge)
		(at peter forge)
		(at oscar bar)
		(at barentrance docks)
		(at mel storage)
		(at karina townarch)
		(at basemententrance bar)
		(at mel bar)
		(at michael hut)
		(at forgeentrance townarch)
		(at tastycupcake townarch)
		(at jordan mansion)
		(at basementexit basement)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected storage basement)
		(connected basement storage)
		(connected docks junkyard)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway storage basement)
		(doorway basement storage)
		(doorway townarch townsquare)
		(has arthur loveletter)
		(has mel basementbucket)
		(has dorian lovecontract)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto forgeexit townarch)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
