(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 arthur mel oscar alli dorian karina frank dave giovanna james ian camille phillip peter matthias - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter coin silver knightshield rubyring bucket knightsword rope - item
		 storage basement bar docks junkyard townarch townsquare bank shop valley fort forge - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance bankexit shopexit fortentrance fortexit forgeexit - entrance
	)
	(:init
		(at tastycupcake hut)
		(at dorian townarch)
		(at ian fort)
		(at barentrance docks)
		(at barexit bar)
		(at hutentrance townarch)
		(at phillip fort)
		(at james valley)
		(at jordan mansion)
		(at mansionentrance cliff)
		(at mel bar)
		(at mel basement)
		(at giovanna shop)
		(at hutexit hut)
		(at shopexit shop)
		(at karina townarch)
		(at arthur forge)
		(at fortentrance valley)
		(at mirror junkyard)
		(at peter forge)
		(at camille fort)
		(at basementexit basement)
		(at bankentrance townsquare)
		(at alli junkyard)
		(at forgeexit forge)
		(at oscar bar)
		(at mel storage)
		(at dave townsquare)
		(at basemententrance bar)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at shopentrance townsquare)
		(at fortexit fort)
		(at matthias forge)
		(at frank townsquare)
		(closed hutentrance)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected storage basement)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected valley townsquare)
		(connected townarch docks)
		(connected basement storage)
		(connected townsquare townarch)
		(connected docks townarch)
		(connected townsquare cliff)
		(doorway basement storage)
		(doorway storage basement)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway docks townarch)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway townarch docks)
		(doorway junkyard docks)
		(doorway valley townsquare)
		(has ian knightshield)
		(has dorian lovecontract)
		(has alli ash)
		(has mel basementbucket)
		(has arthur rubyring)
		(has arthur knightsword)
		(has arthur rope)
		(has arthur mushroom)
		(has arthur bucket)
		(has james coin)
		(has arthur silver)
		(has arthur loveletter)
		(leadsto fortexit valley)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto fortentrance fort)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto hutexit townarch)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item ian knightsword)
		(wants-item arthur shinykey)
		(wants-item james humanskull)
		(wants-item giovanna hairtonic)
		(wants-item jordan loveletter)
		(wants-item alli tastycupcake)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur bucket)
	)
	(:goal
	  (AND
		(game-has-been-won)
		(not (locked basementexit))
		(has alli tastycupcake)
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has james coin)
		(has james humanskull)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
