(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit mansionentrance bankentrance - entrance
		 storage basement bar docks townarch hut junkyard forge cliff mansion townsquare - location
		 arthur mel oscar dorian karina michael alli peter matthias jordan - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter tastycupcake hairtonic book mirror ash knightsword rope - item
	)
	(:init
		(at mansionentrance cliff)
		(at barexit bar)
		(at mel basement)
		(at jordan mansion)
		(at hutexit hut)
		(at tastycupcake hut)
		(at hairtonic hut)
		(at basementexit basement)
		(at arthur forge)
		(at basemententrance bar)
		(at book hut)
		(at dorian townarch)
		(at forgeexit forge)
		(at oscar bar)
		(at alli junkyard)
		(at mushroom docks)
		(at karina townarch)
		(at peter forge)
		(at mel storage)
		(at matthias forge)
		(at michael hut)
		(at barentrance docks)
		(at hutentrance townarch)
		(at forgeentrance townarch)
		(at rope docks)
		(at shinykey docks)
		(at mel bar)
		(closed basemententrance)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected townsquare cliff)
		(connected basement storage)
		(connected storage basement)
		(connected docks townarch)
		(connected junkyard docks)
		(connected townarch docks)
		(connected docks junkyard)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(doorway townsquare cliff)
		(has dorian lovecontract)
		(has arthur mirror)
		(has arthur loveletter)
		(has arthur knightsword)
		(has alli ash)
		(has mel basementbucket)
		(leadsto basemententrance basement)
		(leadsto forgeentrance forge)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto barexit docks)
		(leadsto mansionentrance mansion)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item alli tastycupcake)
		(wants-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur knightsword)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
