(move-through-entrance arthur docks barentrance bar)
(open arthur hutentrance townarch)
(move-through-entrance arthur hut hutexit townarch)
(move-through-door arthur townsquare towngate townarch)
(move-through-door arthur townsquare towngate townarch)
(move-through-entrance arthur townarch hutentrance hut)
(move-through-entrance arthur hut hutexit townarch)
(move-through-door arthur townsquare towngate townarch)
(move-through-doorway arthur townarch docks)
(move-through-entrance arthur docks barentrance bar)
(move-through-door arthur townsquare towngate townarch)
(move-through-doorway arthur townarch docks)
(move-through-doorway arthur docks junkyard)
(move-through-doorway arthur junkyard docks)
(move-through-entrance arthur townarch hutentrance hut)
(pickup arthur tastycupcake hut)
(move-through-entrance arthur hut hutexit townarch)
(drop arthur mushroom townarch)
(move-through-doorway arthur townarch docks)
(move-through-doorway arthur docks junkyard)
(give arthur tastycupcake alli junkyard)
(move-through-doorway arthur junkyard docks)
(move-through-door arthur townsquare towngate townarch)
(move-through-doorway arthur townarch docks)
