(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit fortexit shopexit hutexit - entrance
		 storage basement bar docks townarch forge junkyard townsquare valley cliff mansion fort shop hut bank - location
		 arthur mel oscar dorian karina peter matthias alli frank dave james jordan avery roger ian camille phillip giovanna michael - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope mirror ash humanskull bouquet candle bucket knightshield rubyring tastycupcake hairtonic book coin - item
	)
	(:init
		(at phillip fort)
		(at hutentrance townarch)
		(at fortexit fort)
		(at basementexit basement)
		(at camille fort)
		(at frank townsquare)
		(at dorian townarch)
		(at mel bar)
		(at barentrance docks)
		(at bankentrance townsquare)
		(at michael hut)
		(at tastycupcake hut)
		(at jordan mansion)
		(at knightshield shop)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at oscar bar)
		(at mansionexit mansion)
		(at candle mansion)
		(at barexit bar)
		(at hutexit hut)
		(at fortentrance valley)
		(at mirror junkyard)
		(at book hut)
		(at forgeexit forge)
		(at rope townsquare)
		(at ian fort)
		(at rubyring shop)
		(at matthias forge)
		(at peter forge)
		(at avery mansion)
		(at mushroom townsquare)
		(at giovanna shop)
		(at hairtonic hut)
		(at mel basement)
		(at humanskull cliff)
		(at mansionentrance cliff)
		(at alli junkyard)
		(at shopexit shop)
		(at karina townarch)
		(at james valley)
		(at bucket fort)
		(at mel storage)
		(at dave townsquare)
		(at basemententrance bar)
		(at roger mansion)
		(at arthur hut)
		(closed bankentrance)
		(closed basemententrance)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected junkyard docks)
		(connected storage basement)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townsquare valley)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townarch townsquare)
		(connected docks junkyard)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway basement storage)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway junkyard docks)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway cliff townsquare)
		(has mel basementbucket)
		(has alli ash)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has arthur bouquet)
		(has arthur knightsword)
		(has arthur shinykey)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(leadsto fortentrance fort)
		(leadsto basementexit bar)
		(leadsto fortexit valley)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(locked bankentrance)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item jordan loveletter)
		(wants-item alli tastycupcake)
		(wants-item james coin)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur bouquet)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
