(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightsword rope tastycupcake - item
		 storage basement bar docks junkyard townarch townsquare cliff valley forge hut mansion fort bank shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance forgeexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave james peter matthias jordan - character
	)
	(:init
		(at mansionentrance cliff)
		(at tastycupcake hut)
		(at shopentrance townsquare)
		(at bouquet cliff)
		(at oscar bar)
		(at barexit bar)
		(at jordan mansion)
		(at matthias forge)
		(at hutentrance townarch)
		(at basementexit basement)
		(at james valley)
		(at knightsword forge)
		(at peter forge)
		(at mel storage)
		(at forgeexit forge)
		(at humanskull cliff)
		(at dave townsquare)
		(at forgeentrance townarch)
		(at barentrance docks)
		(at bankentrance townsquare)
		(at frank townsquare)
		(at mel basement)
		(at fortentrance valley)
		(at alli junkyard)
		(at arthur forge)
		(at mel bar)
		(at hutexit hut)
		(at dorian townarch)
		(at basemententrance bar)
		(at karina townarch)
		(closed fortentrance)
		(closed mansionentrance)
		(closed basemententrance)
		(closed hutentrance)
		(closed shopentrance)
		(closed bankentrance)
		(connected docks townarch)
		(connected basement storage)
		(connected storage basement)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected townsquare cliff)
		(connected valley townsquare)
		(connected cliff townsquare)
		(connected junkyard docks)
		(connected townarch townsquare)
		(connected townsquare valley)
		(connected townarch docks)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway townsquare cliff)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway docks junkyard)
		(doorway townsquare valley)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway townarch townsquare)
		(has alli ash)
		(has arthur loveletter)
		(has arthur rope)
		(has arthur mirror)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur mushroom)
		(leadsto forgeentrance forge)
		(leadsto shopentrance shop)
		(leadsto barexit docks)
		(leadsto hutentrance hut)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto fortentrance fort)
		(leadsto forgeexit townarch)
		(leadsto basementexit bar)
		(leadsto basemententrance basement)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item alli tastycupcake)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
