(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring candle - item
		 storage basement bar docks junkyard townarch townsquare cliff valley forge hut bank shop mansion fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance forgeexit hutexit bankexit shopexit mansionexit - entrance
		 arthur mel oscar alli dorian karina frank dave james peter matthias michael giovanna jordan avery roger - character
	)
	(:init
		(at mansionexit mansion)
		(at frank townsquare)
		(at book hut)
		(at bankentrance townsquare)
		(at peter forge)
		(at mel storage)
		(at oscar bar)
		(at coin bank)
		(at mirror forge)
		(at arthur mansion)
		(at candle mansion)
		(at michael hut)
		(at matthias forge)
		(at jordan mansion)
		(at barexit bar)
		(at hutentrance townarch)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at bouquet cliff)
		(at humanskull cliff)
		(at basementexit basement)
		(at mel basement)
		(at silver bank)
		(at basemententrance bar)
		(at fortentrance valley)
		(at avery mansion)
		(at dave townsquare)
		(at forgeexit forge)
		(at james valley)
		(at mushroom docks)
		(at knightshield shop)
		(at barentrance docks)
		(at dorian townarch)
		(at roger mansion)
		(at giovanna shop)
		(at shopexit shop)
		(at mansionentrance cliff)
		(at alli junkyard)
		(at mel bar)
		(at hutexit hut)
		(at rubyring shop)
		(at karina townarch)
		(closed basemententrance)
		(closed fortentrance)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected storage basement)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected basement storage)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway townsquare townarch)
		(doorway docks junkyard)
		(doorway storage basement)
		(has giovanna hairtonic)
		(has arthur ash)
		(has dorian lovecontract)
		(has arthur rope)
		(has arthur knightsword)
		(has jordan loveletter)
		(has mel basementbucket)
		(has alli tastycupcake)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto basemententrance basement)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto fortentrance fort)
		(leadsto shopexit townsquare)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan lovecontract)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
