(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightsword rope tastycupcake hairtonic book coin silver knightshield rubyring candle - item
		 storage basement bar docks junkyard townarch townsquare cliff valley forge hut bank shop mansion fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance forgeexit hutexit bankexit shopexit mansionexit - entrance
		 arthur mel oscar alli dorian karina frank dave james peter matthias michael giovanna jordan avery roger - character
	)
	(:init
		(at giovanna shop)
		(at mushroom docks)
		(at forgeexit forge)
		(at forgeentrance townarch)
		(at silver bank)
		(at ash cliff)
		(at jordan mansion)
		(at bankentrance townsquare)
		(at oscar bar)
		(at michael hut)
		(at mel storage)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at candle mansion)
		(at mirror forge)
		(at barexit bar)
		(at matthias forge)
		(at coin bank)
		(at barentrance docks)
		(at arthur townsquare)
		(at karina townarch)
		(at alli junkyard)
		(at roger mansion)
		(at mel basement)
		(at basementexit basement)
		(at shopexit shop)
		(at frank townsquare)
		(at mansionentrance cliff)
		(at mel bar)
		(at book hut)
		(at mansionexit mansion)
		(at knightshield shop)
		(at hutexit hut)
		(at basemententrance bar)
		(at peter forge)
		(at fortentrance valley)
		(at humanskull cliff)
		(at dorian townarch)
		(at avery mansion)
		(at hutentrance townarch)
		(at rubyring mansion)
		(at dave townsquare)
		(at james valley)
		(closed fortentrance)
		(closed basemententrance)
		(connected townsquare townarch)
		(connected storage basement)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected townarch docks)
		(connected junkyard docks)
		(connected basement storage)
		(connected docks junkyard)
		(connected townarch townsquare)
		(doorway cliff townsquare)
		(doorway townsquare townarch)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway junkyard docks)
		(doorway townsquare valley)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway townarch townsquare)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway valley townsquare)
		(has giovanna hairtonic)
		(has jordan loveletter)
		(has arthur knightsword)
		(has arthur rope)
		(has dorian bouquet)
		(has alli tastycupcake)
		(has jordan lovecontract)
		(has mel basementbucket)
		(leadsto bankexit townsquare)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto forgeexit townarch)
		(leadsto mansionexit cliff)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item dorian rubyring)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur knightsword)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has alli tastycupcake) 
			(and (has jordan loveletter) (has jordan lovecontract) )
		)

	)

)
