(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightsword rope tastycupcake - item
		 storage basement bar docks junkyard townarch townsquare cliff valley forge hut mansion fort bank shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance forgeexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave james peter matthias jordan - character
	)
	(:init
		(at dorian townarch)
		(at basementexit basement)
		(at oscar bar)
		(at jordan mansion)
		(at forgeexit forge)
		(at peter forge)
		(at mel storage)
		(at basemententrance bar)
		(at bouquet cliff)
		(at matthias forge)
		(at forgeentrance townarch)
		(at mel bar)
		(at mel basement)
		(at arthur forge)
		(at hutexit hut)
		(at shopentrance townsquare)
		(at frank townsquare)
		(at james valley)
		(at mirror forge)
		(at karina townarch)
		(at barentrance docks)
		(at hutentrance townarch)
		(at barexit bar)
		(at dave townsquare)
		(at tastycupcake hut)
		(at fortentrance valley)
		(at bankentrance townsquare)
		(at mansionentrance cliff)
		(at alli junkyard)
		(at humanskull cliff)
		(closed basemententrance)
		(closed mansionentrance)
		(closed bankentrance)
		(closed hutentrance)
		(closed fortentrance)
		(closed shopentrance)
		(connected townarch townsquare)
		(connected storage basement)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townarch docks)
		(connected townsquare cliff)
		(connected basement storage)
		(connected docks townarch)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected junkyard docks)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway junkyard docks)
		(doorway townarch townsquare)
		(doorway basement storage)
		(doorway valley townsquare)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(has arthur mushroom)
		(has arthur rope)
		(has dorian lovecontract)
		(has arthur knightsword)
		(has arthur loveletter)
		(has mel basementbucket)
		(has alli ash)
		(leadsto basemententrance basement)
		(leadsto barexit docks)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto fortentrance fort)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(wants-item jordan loveletter)
		(wants-item alli tastycupcake)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur rope)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
