(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter humanskull bouquet knightsword rope tastycupcake - item
		 storage basement bar docks junkyard townarch townsquare cliff valley forge hut mansion shop fort bank - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance shopentrance bankentrance mansionentrance fortentrance forgeexit hutexit - entrance
		 arthur mel oscar alli dorian karina frank dave james peter matthias jordan - character
	)
	(:init
		(at alli junkyard)
		(at shopentrance townsquare)
		(at bouquet cliff)
		(at oscar bar)
		(at matthias forge)
		(at tastycupcake hut)
		(at barexit bar)
		(at jordan mansion)
		(at knightsword forge)
		(at basementexit basement)
		(at peter forge)
		(at humanskull cliff)
		(at hutentrance townarch)
		(at mel storage)
		(at rope forge)
		(at james valley)
		(at dave townsquare)
		(at mansionentrance cliff)
		(at arthur forge)
		(at forgeexit forge)
		(at bankentrance townsquare)
		(at frank townsquare)
		(at hutexit hut)
		(at fortentrance valley)
		(at dorian townarch)
		(at forgeentrance townarch)
		(at mel basement)
		(at mel bar)
		(at barentrance docks)
		(at basemententrance bar)
		(at karina townarch)
		(closed fortentrance)
		(closed basemententrance)
		(closed shopentrance)
		(closed bankentrance)
		(closed mansionentrance)
		(closed hutentrance)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected storage basement)
		(connected townsquare cliff)
		(connected basement storage)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected docks townarch)
		(connected townarch docks)
		(doorway valley townsquare)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway townsquare valley)
		(doorway storage basement)
		(doorway townsquare cliff)
		(doorway junkyard docks)
		(doorway docks junkyard)
		(doorway townsquare townarch)
		(doorway cliff townsquare)
		(doorway townarch townsquare)
		(doorway townarch docks)
		(doorway basement storage)
		(has arthur loveletter)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has alli ash)
		(has arthur mushroom)
		(has arthur mirror)
		(leadsto bankentrance bank)
		(leadsto forgeentrance forge)
		(leadsto mansionentrance mansion)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto fortentrance fort)
		(leadsto basemententrance basement)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(leadsto hutexit townarch)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item alli tastycupcake)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur ash)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur mirror)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		(and
			(has alli tastycupcake) 
			(has jordan loveletter) 
		)

	)

)
