(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit fortexit - entrance
		 storage basement bar docks junkyard townarch hut forge townsquare bank shop valley cliff mansion fort - location
		 arthur mel oscar alli dorian karina michael peter matthias frank dave giovanna james jordan avery roger ian camille phillip - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring humanskull bouquet candle bucket - item
	)
	(:init
		(at hutexit hut)
		(at rubyring shop)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at mel storage)
		(at mirror junkyard)
		(at matthias forge)
		(at rope forge)
		(at arthur hut)
		(at james valley)
		(at fortentrance valley)
		(at oscar bar)
		(at mushroom hut)
		(at avery mansion)
		(at barexit bar)
		(at jordan mansion)
		(at basemententrance bar)
		(at peter forge)
		(at tastycupcake hut)
		(at bucket fort)
		(at phillip fort)
		(at hutentrance townarch)
		(at michael hut)
		(at forgeentrance townarch)
		(at bouquet townsquare)
		(at fortexit fort)
		(at basementexit basement)
		(at alli junkyard)
		(at dave townsquare)
		(at mel bar)
		(at roger mansion)
		(at camille fort)
		(at forgeexit forge)
		(at mansionexit mansion)
		(at ian fort)
		(at barentrance docks)
		(at dorian townarch)
		(at mansionentrance cliff)
		(at frank townsquare)
		(at giovanna shop)
		(at karina townarch)
		(at shopexit shop)
		(at book hut)
		(at bankentrance townsquare)
		(at mel basement)
		(at knightshield shop)
		(closed mansionentrance)
		(closed forgeentrance)
		(closed barentrance)
		(closed basemententrance)
		(closed shopentrance)
		(closed bankentrance)
		(closed fortentrance)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townarch docks)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected storage basement)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townarch townsquare)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townsquare cliff)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway valley townsquare)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway docks junkyard)
		(has james coin)
		(has james humanskull)
		(has alli ash)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has arthur silver)
		(has mel basementbucket)
		(has giovanna hairtonic)
		(has james candle)
		(has arthur knightsword)
		(leadsto bankexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto hutexit townarch)
		(leadsto mansionentrance mansion)
		(leadsto fortexit valley)
		(leadsto fortentrance fort)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item alli tastycupcake)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item jordan lovecontract)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		(or
			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

		)
	)

)
