(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance - entrance
		 storage basement bar docks junkyard townarch hut forge townsquare bank shop valley cliff mansion fort - location
		 arthur mel oscar alli dorian karina michael peter matthias frank dave giovanna james jordan - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring - item
	)
	(:init
		(at barentrance docks)
		(at forgeexit forge)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at james valley)
		(at mushroom hut)
		(at peter forge)
		(at hutentrance townarch)
		(at dave townsquare)
		(at jordan mansion)
		(at rope forge)
		(at michael hut)
		(at alli junkyard)
		(at shopentrance townsquare)
		(at matthias forge)
		(at oscar bar)
		(at dorian townarch)
		(at book hut)
		(at bankentrance townsquare)
		(at basementexit basement)
		(at basemententrance bar)
		(at knightshield shop)
		(at karina townarch)
		(at frank townsquare)
		(at mirror junkyard)
		(at barexit bar)
		(at arthur valley)
		(at tastycupcake hut)
		(at rubyring shop)
		(at mel basement)
		(at shopexit shop)
		(at fortentrance valley)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at mel bar)
		(at hutexit hut)
		(at mel storage)
		(closed fortentrance)
		(closed forgeentrance)
		(closed shopentrance)
		(closed basemententrance)
		(closed hutentrance)
		(closed bankentrance)
		(closed barentrance)
		(connected townsquare valley)
		(connected storage basement)
		(connected townsquare cliff)
		(connected valley townsquare)
		(connected docks townarch)
		(connected townsquare townarch)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townarch docks)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townarch townsquare)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway valley townsquare)
		(doorway junkyard docks)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway townarch docks)
		(doorway townsquare valley)
		(has arthur knightsword)
		(has arthur silver)
		(has dorian lovecontract)
		(has arthur coin)
		(has alli ash)
		(has arthur loveletter)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(leadsto forgeentrance forge)
		(leadsto barexit docks)
		(leadsto basementexit bar)
		(leadsto bankexit townsquare)
		(leadsto shopentrance shop)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto fortentrance fort)
		(leadsto forgeexit townarch)
		(leadsto basemententrance basement)
		(leadsto shopexit townsquare)
		(leadsto bankentrance bank)
		(leadsto barentrance bar)
		(leadsto hutexit townarch)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item james coin)
		(wants-item jordan loveletter)
		(wants-item arthur ash)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur coin)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has jordan loveletter) 
			(has james coin) 
		)

	)

)
