(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit fortexit - entrance
		 storage basement bar docks junkyard townarch hut forge townsquare bank shop valley cliff mansion fort - location
		 arthur mel oscar alli dorian karina michael peter matthias frank dave giovanna james jordan avery roger ian camille phillip - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring humanskull bouquet candle bucket - item
	)
	(:init
		(at hutexit hut)
		(at fortexit fort)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at mel storage)
		(at matthias forge)
		(at mirror junkyard)
		(at avery mansion)
		(at oscar bar)
		(at hutentrance townarch)
		(at rope forge)
		(at phillip fort)
		(at rubyring shop)
		(at ian fort)
		(at barexit bar)
		(at jordan mansion)
		(at peter forge)
		(at bucket fort)
		(at camille fort)
		(at basemententrance bar)
		(at dorian townarch)
		(at book hut)
		(at shopentrance townsquare)
		(at alli junkyard)
		(at bouquet townsquare)
		(at basementexit basement)
		(at arthur junkyard)
		(at bankentrance townsquare)
		(at roger mansion)
		(at barentrance docks)
		(at dave townsquare)
		(at forgeexit forge)
		(at mansionexit mansion)
		(at michael hut)
		(at mel bar)
		(at mansionentrance cliff)
		(at fortentrance valley)
		(at giovanna shop)
		(at shopexit shop)
		(at frank townsquare)
		(at karina townarch)
		(at mel basement)
		(at james valley)
		(at knightshield shop)
		(closed basemententrance)
		(closed fortentrance)
		(closed barentrance)
		(closed bankentrance)
		(closed shopentrance)
		(closed mansionentrance)
		(closed forgeentrance)
		(connected townsquare townarch)
		(connected townsquare valley)
		(connected townarch docks)
		(connected docks townarch)
		(connected valley townsquare)
		(connected storage basement)
		(connected docks junkyard)
		(connected junkyard docks)
		(connected townsquare cliff)
		(connected basement storage)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(has arthur knightsword)
		(has james coin)
		(has arthur loveletter)
		(has arthur silver)
		(has dorian lovecontract)
		(has james humanskull)
		(has alli tastycupcake)
		(has mel basementbucket)
		(has giovanna hairtonic)
		(has james candle)
		(has arthur mushroom)
		(has alli ash)
		(leadsto shopexit townsquare)
		(leadsto mansionexit cliff)
		(leadsto bankexit townsquare)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto fortexit valley)
		(leadsto hutentrance hut)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto barentrance bar)
		(leadsto mansionentrance mansion)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item jordan lovecontract)
		(wants-item arthur ash)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
	)
	(:goal
		(or
			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

			(and
				(has giovanna hairtonic) 
				(has alli tastycupcake) 
				(has jordan loveletter) 
				(has james coin) (has james humanskull) (has james candle) 
			)

		)
	)

)
