(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance bankexit shopexit fortentrance mansionentrance mansionexit - entrance
		 storage basement bar docks junkyard townarch hut forge townsquare bank shop valley cliff mansion fort - location
		 arthur mel oscar alli dorian karina michael peter matthias frank dave giovanna james jordan avery roger - character
		 towngate - door
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope coin silver knightshield rubyring humanskull bouquet candle - item
	)
	(:init
		(at avery mansion)
		(at mel storage)
		(at basementexit basement)
		(at arthur townsquare)
		(at fortentrance valley)
		(at mushroom hut)
		(at oscar bar)
		(at rope forge)
		(at candle mansion)
		(at basemententrance bar)
		(at bouquet cliff)
		(at shopentrance townsquare)
		(at michael hut)
		(at hutentrance townarch)
		(at dorian townarch)
		(at book hut)
		(at frank townsquare)
		(at forgeentrance townarch)
		(at bankexit bank)
		(at matthias forge)
		(at jordan mansion)
		(at mirror junkyard)
		(at shopexit shop)
		(at alli junkyard)
		(at rubyring shop)
		(at barentrance docks)
		(at karina townarch)
		(at barexit bar)
		(at james valley)
		(at peter forge)
		(at tastycupcake hut)
		(at dave townsquare)
		(at forgeexit forge)
		(at mel bar)
		(at hutexit hut)
		(at mansionentrance cliff)
		(at mel basement)
		(at giovanna shop)
		(at roger mansion)
		(at bankentrance townsquare)
		(at mansionexit mansion)
		(at knightshield shop)
		(closed hutentrance)
		(closed mansionentrance)
		(closed barentrance)
		(closed fortentrance)
		(closed bankentrance)
		(closed shopentrance)
		(closed basemententrance)
		(closed forgeentrance)
		(connected storage basement)
		(connected townsquare townarch)
		(connected docks junkyard)
		(connected docks townarch)
		(connected townsquare valley)
		(connected townarch townsquare)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected basement storage)
		(connected junkyard docks)
		(connected valley townsquare)
		(connected cliff townsquare)
		(doorbetween towngate townarch townsquare)
		(doorbetween towngate townsquare townarch)
		(doorway docks junkyard)
		(doorway townarch docks)
		(doorway valley townsquare)
		(doorway townsquare valley)
		(doorway cliff townsquare)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway basement storage)
		(doorway townsquare cliff)
		(has giovanna hairtonic)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has alli ash)
		(has arthur silver)
		(has arthur loveletter)
		(has arthur humanskull)
		(has arthur knightsword)
		(has james coin)
		(leadsto hutentrance hut)
		(leadsto hutexit townarch)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto shopentrance shop)
		(leadsto forgeexit townarch)
		(leadsto basemententrance basement)
		(leadsto barentrance bar)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto mansionexit cliff)
		(leadsto forgeentrance forge)
		(leadsto basementexit bar)
		(leadsto fortentrance fort)
		(leadsto bankentrance bank)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur lovecontract)
		(wants-item james humanskull)
		(wants-item jordan loveletter)
		(wants-item arthur shinykey)
		(wants-item arthur ash)
		(wants-item jordan lovecontract)
		(willing-to-give-item arthur knightsword)
		(willing-to-give-item arthur silver)
		(willing-to-give-item arthur humanskull)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
		
		(and
			(has giovanna hairtonic) 
			(has jordan loveletter) 
			(and (has james coin) (has james humanskull) )
		)

	)

)
