(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 towngate - door
		 arthur mel oscar alli dorian karina michael peter matthias frank dave james jordan avery roger giovanna ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle knightshield rubyring coin silver bucket - item
		 storage basement bar docks junkyard townarch hut forge townsquare valley cliff mansion shop bank fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit bankexit fortexit - entrance
	)
	(:init
		(at mushroom townsquare)
		(at silver bank)
		(at fortentrance valley)
		(at avery mansion)
		(at mel bar)
		(at hutexit hut)
		(at camille fort)
		(at book hut)
		(at bucket fort)
		(at basementexit basement)
		(at mansionexit mansion)
		(at barentrance docks)
		(at roger mansion)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at dorian townarch)
		(at shopexit shop)
		(at karina townarch)
		(at ian fort)
		(at frank townsquare)
		(at mel storage)
		(at alli junkyard)
		(at arthur mansion)
		(at mel basement)
		(at hutentrance townarch)
		(at knightsword forge)
		(at fortexit fort)
		(at forgeexit forge)
		(at bankentrance townsquare)
		(at humanskull cliff)
		(at bouquet cliff)
		(at basemententrance bar)
		(at oscar bar)
		(at michael hut)
		(at dave townsquare)
		(at candle mansion)
		(at forgeentrance townarch)
		(at phillip fort)
		(at matthias forge)
		(at peter forge)
		(at james valley)
		(at jordan mansion)
		(at bankexit bank)
		(at shopentrance townsquare)
		(at mirror junkyard)
		(at barexit bar)
		(closed basemententrance)
		(connected junkyard docks)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected cliff townsquare)
		(connected basement storage)
		(connected townsquare townarch)
		(connected townsquare cliff)
		(connected storage basement)
		(connected townarch docks)
		(connected docks townarch)
		(connected valley townsquare)
		(connected townsquare valley)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway docks townarch)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(has mel basementbucket)
		(has arthur rope)
		(has jordan loveletter)
		(has ian knightshield)
		(has alli tastycupcake)
		(has james coin)
		(has dorian lovecontract)
		(has arthur rubyring)
		(has arthur ash)
		(has ian knightsword)
		(has giovanna hairtonic)
		(leadsto forgeentrance forge)
		(leadsto bankentrance bank)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto mansionentrance mansion)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(leadsto hutexit townarch)
		(leadsto basemententrance basement)
		(leadsto fortexit valley)
		(leadsto barexit docks)
		(leadsto bankexit townsquare)
		(leadsto hutentrance hut)
		(leadsto fortentrance fort)
		(leadsto barentrance bar)
		(leadsto mansionexit cliff)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item james humanskull)
		(wants-item jordan lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur rope)
	)
	(:goal
	  (AND
		
		(not (locked basementexit))
		(has alli tastycupcake)
		(has arthur ash)
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has james coin)
		(has james humanskull)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
