(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 towngate - door
		 arthur mel oscar alli dorian karina michael peter matthias frank dave james jordan avery roger giovanna - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle knightshield rubyring - item
		 storage basement bar docks junkyard townarch hut forge townsquare valley cliff mansion shop - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit - entrance
	)
	(:init
		(at hutexit hut)
		(at fortentrance valley)
		(at mel bar)
		(at knightsword forge)
		(at humanskull cliff)
		(at hutentrance townarch)
		(at barentrance docks)
		(at michael hut)
		(at knightshield shop)
		(at mansionexit mansion)
		(at peter forge)
		(at shopexit shop)
		(at mirror junkyard)
		(at karina townarch)
		(at alli junkyard)
		(at roger mansion)
		(at avery mansion)
		(at mel basement)
		(at james valley)
		(at dorian townarch)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at shopentrance townsquare)
		(at forgeentrance townarch)
		(at basemententrance bar)
		(at matthias forge)
		(at forgeexit forge)
		(at basementexit basement)
		(at dave townsquare)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at frank townsquare)
		(at barexit bar)
		(at bouquet cliff)
		(at oscar bar)
		(at mel storage)
		(at jordan mansion)
		(at book hut)
		(at candle mansion)
		(closed bankentrance)
		(closed basemententrance)
		(closed fortentrance)
		(connected cliff townsquare)
		(connected docks junkyard)
		(connected townarch townsquare)
		(connected basement storage)
		(connected valley townsquare)
		(connected townsquare townarch)
		(connected junkyard docks)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected townarch docks)
		(connected townsquare valley)
		(connected storage basement)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway valley townsquare)
		(doorway townarch docks)
		(doorway docks townarch)
		(doorway cliff townsquare)
		(doorway docks junkyard)
		(doorway junkyard docks)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway townsquare valley)
		(doorway basement storage)
		(doorway storage basement)
		(has mel basementbucket)
		(has alli tastycupcake)
		(has arthur rubyring)
		(has dorian lovecontract)
		(has arthur loveletter)
		(has arthur mushroom)
		(has arthur rope)
		(has giovanna hairtonic)
		(has arthur ash)
		(leadsto hutexit townarch)
		(leadsto forgeentrance forge)
		(leadsto shopexit townsquare)
		(leadsto fortentrance fort)
		(leadsto barexit docks)
		(leadsto barentrance bar)
		(leadsto hutentrance hut)
		(leadsto mansionexit cliff)
		(leadsto basemententrance basement)
		(leadsto bankentrance bank)
		(leadsto mansionentrance mansion)
		(leadsto forgeexit townarch)
		(leadsto shopentrance shop)
		(leadsto basementexit bar)
		(player arthur)
		(unlocks basementexitkey basementexit)
		(unlocks shinykey bankentrance)
		(wants-item arthur shinykey)
		(wants-item arthur lovecontract)
		(wants-item jordan lovecontract)
		(wants-item jordan loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
	  (AND
		
		(not (locked basementexit))
		(has alli tastycupcake)
		(has arthur ash)
		(has jordan loveletter)
		(has giovanna hairtonic)
	  )
	)
)
