(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 towngate - door
		 arthur mel oscar alli dorian karina michael peter matthias frank dave james jordan avery roger giovanna ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle knightshield rubyring coin silver bucket - item
		 storage basement bar docks junkyard townarch hut forge townsquare valley cliff mansion shop bank fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit bankexit fortexit - entrance
	)
	(:init
		(at giovanna shop)
		(at frank townsquare)
		(at mel basement)
		(at mansionentrance cliff)
		(at karina townarch)
		(at shopexit shop)
		(at book hut)
		(at camille fort)
		(at fortentrance valley)
		(at mansionexit mansion)
		(at hutexit hut)
		(at dorian townarch)
		(at basementexit basement)
		(at mel bar)
		(at james valley)
		(at avery mansion)
		(at arthur cliff)
		(at mushroom townsquare)
		(at peter forge)
		(at knightsword forge)
		(at silver bank)
		(at roger mansion)
		(at fortexit fort)
		(at michael hut)
		(at alli junkyard)
		(at humanskull cliff)
		(at ian fort)
		(at hutentrance townarch)
		(at mirror junkyard)
		(at barexit bar)
		(at mel storage)
		(at phillip fort)
		(at shopentrance townsquare)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at bankentrance townsquare)
		(at jordan mansion)
		(at forgeexit forge)
		(at dave townsquare)
		(at oscar bar)
		(at barentrance docks)
		(at matthias forge)
		(at bucket fort)
		(at candle mansion)
		(at basemententrance bar)
		(at bouquet cliff)
		(closed basemententrance)
		(connected cliff townsquare)
		(connected townarch docks)
		(connected townarch townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected townsquare valley)
		(connected townsquare townarch)
		(connected valley townsquare)
		(connected townsquare cliff)
		(connected docks townarch)
		(connected storage basement)
		(connected junkyard docks)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway townsquare valley)
		(doorway docks junkyard)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townarch docks)
		(doorway townsquare cliff)
		(doorway docks townarch)
		(doorway junkyard docks)
		(doorway valley townsquare)
		(doorway storage basement)
		(doorway cliff townsquare)
		(has arthur rubyring)
		(has mel basementbucket)
		(has alli tastycupcake)
		(has giovanna hairtonic)
		(has arthur rope)
		(has arthur loveletter)
		(has dorian lovecontract)
		(has ian knightshield)
		(has ian knightsword)
		(has james coin)
		(has arthur ash)
		(leadsto barexit docks)
		(leadsto bankentrance bank)
		(leadsto bankexit townsquare)
		(leadsto forgeentrance forge)
		(leadsto forgeexit townarch)
		(leadsto barentrance bar)
		(leadsto basementexit bar)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto hutexit townarch)
		(leadsto fortexit valley)
		(leadsto shopexit townsquare)
		(leadsto basemententrance basement)
		(leadsto fortentrance fort)
		(leadsto mansionexit cliff)
		(leadsto hutentrance hut)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item jordan loveletter)
		(wants-item jordan lovecontract)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(wants-item james humanskull)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
	)
	(:goal
	  (AND
		
		(not (locked basementexit))
		(has alli tastycupcake)
		(has arthur ash)
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has james coin)
		(has james humanskull)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
