(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 towngate - door
		 arthur mel oscar alli dorian karina michael peter matthias frank dave james jordan avery roger giovanna ian camille phillip - character
		 basementexitkey basementbucket shinykey mushroom mirror ash lovecontract loveletter tastycupcake hairtonic book knightsword rope humanskull bouquet candle knightshield rubyring coin silver bucket - item
		 storage basement bar docks junkyard townarch hut forge townsquare valley cliff mansion shop bank fort - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance hutexit forgeexit shopentrance bankentrance fortentrance mansionentrance mansionexit shopexit bankexit fortexit - entrance
	)
	(:init
		(at mel basement)
		(at silver bank)
		(at basementexit basement)
		(at dorian townarch)
		(at frank townsquare)
		(at mansionentrance cliff)
		(at giovanna shop)
		(at mansionexit mansion)
		(at knightshield shop)
		(at forgeexit forge)
		(at camille fort)
		(at mel bar)
		(at hutexit hut)
		(at fortentrance valley)
		(at ian fort)
		(at humanskull cliff)
		(at hutentrance townarch)
		(at james valley)
		(at avery mansion)
		(at dave townsquare)
		(at peter forge)
		(at karina townarch)
		(at shopexit shop)
		(at book hut)
		(at michael hut)
		(at alli junkyard)
		(at roger mansion)
		(at fortexit fort)
		(at bankexit bank)
		(at forgeentrance townarch)
		(at barentrance docks)
		(at shopentrance townsquare)
		(at phillip fort)
		(at matthias forge)
		(at mirror junkyard)
		(at candle mansion)
		(at bouquet cliff)
		(at oscar bar)
		(at knightsword forge)
		(at bankentrance townsquare)
		(at arthur townsquare)
		(at mel storage)
		(at jordan mansion)
		(at barexit bar)
		(at basemententrance bar)
		(at bucket fort)
		(closed basemententrance)
		(connected townsquare cliff)
		(connected townsquare valley)
		(connected valley townsquare)
		(connected basement storage)
		(connected docks junkyard)
		(connected cliff townsquare)
		(connected townarch townsquare)
		(connected storage basement)
		(connected junkyard docks)
		(connected townsquare townarch)
		(connected townarch docks)
		(connected docks townarch)
		(doorbetween towngate townsquare townarch)
		(doorbetween towngate townarch townsquare)
		(doorway townarch docks)
		(doorway cliff townsquare)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway junkyard docks)
		(doorway townsquare cliff)
		(doorway storage basement)
		(doorway valley townsquare)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway townsquare valley)
		(has arthur ash)
		(has alli tastycupcake)
		(has arthur mushroom)
		(has mel basementbucket)
		(has dorian lovecontract)
		(has arthur rubyring)
		(has arthur loveletter)
		(has arthur rope)
		(has james coin)
		(has giovanna hairtonic)
		(leadsto forgeentrance forge)
		(leadsto barentrance bar)
		(leadsto forgeexit townarch)
		(leadsto shopexit townsquare)
		(leadsto shopentrance shop)
		(leadsto mansionentrance mansion)
		(leadsto fortexit valley)
		(leadsto hutexit townarch)
		(leadsto basementexit bar)
		(leadsto bankentrance bank)
		(leadsto basemententrance basement)
		(leadsto bankexit townsquare)
		(leadsto mansionexit cliff)
		(leadsto fortentrance fort)
		(leadsto hutentrance hut)
		(leadsto barexit docks)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item james humanskull)
		(wants-item jordan loveletter)
		(wants-item jordan lovecontract)
		(wants-item ian knightsword)
		(wants-item arthur shinykey)
		(wants-item ian knightshield)
		(wants-item arthur lovecontract)
		(willing-to-give-item arthur rubyring)
		(willing-to-give-item arthur rope)
		(willing-to-give-item arthur mushroom)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur lovecontract)
	)
	(:goal
	  (AND
		
		(not (locked basementexit))
		(has alli tastycupcake)
		(has arthur ash)
		(has jordan loveletter)
		(has giovanna hairtonic)
		(has james coin)
		(has james humanskull)
		(has ian knightsword)
		(has ian knightshield)
	  )
	)
)
