(define (problem rob)
(:domain arthur_HYRULE)
	(:objects 
		 basementexitkey basementbucket shinykey mushroom lovecontract loveletter knightsword rope ash - item
		 storage basement bar docks townarch forge mansion cliff townsquare junkyard hut - location
		 basementexit basemententrance barexit barentrance hutentrance forgeentrance forgeexit mansionentrance bankentrance - entrance
		 arthur mel oscar dorian karina peter matthias jordan - character
	)
	(:init
		(at forgeentrance townarch)
		(at dorian townarch)
		(at forgeexit forge)
		(at barexit bar)
		(at karina townarch)
		(at peter forge)
		(at mel storage)
		(at barentrance docks)
		(at oscar bar)
		(at arthur forge)
		(at mel basement)
		(at knightsword forge)
		(at mansionentrance cliff)
		(at rope forge)
		(at hutentrance townarch)
		(at mel bar)
		(at jordan mansion)
		(at basementexit basement)
		(at matthias forge)
		(at basemententrance bar)
		(closed basemententrance)
		(closed hutentrance)
		(connected townarch townsquare)
		(connected townarch docks)
		(connected cliff townsquare)
		(connected docks townarch)
		(connected townsquare cliff)
		(connected docks junkyard)
		(connected storage basement)
		(connected basement storage)
		(doorway townarch docks)
		(doorway docks junkyard)
		(doorway docks townarch)
		(doorway storage basement)
		(doorway basement storage)
		(doorway cliff townsquare)
		(doorway townsquare cliff)
		(doorway townarch townsquare)
		(has arthur shinykey)
		(has arthur mushroom)
		(has dorian lovecontract)
		(has mel basementbucket)
		(has arthur loveletter)
		(leadsto hutentrance hut)
		(leadsto mansionentrance mansion)
		(leadsto barentrance bar)
		(leadsto barexit docks)
		(leadsto basemententrance basement)
		(leadsto forgeexit townarch)
		(leadsto basementexit bar)
		(leadsto forgeentrance forge)
		(player arthur)
		(unlocks shinykey bankentrance)
		(unlocks basementexitkey basementexit)
		(wants-item arthur ash)
		(wants-item jordan loveletter)
		(wants-item arthur lovecontract)
		(wants-item arthur shinykey)
		(willing-to-give-item arthur lovecontract)
		(willing-to-give-item arthur ash)
		(willing-to-give-item arthur shinykey)
		(willing-to-give-item arthur loveletter)
		(willing-to-give-item arthur mushroom)
	)
	(:goal
		
		
			(has jordan loveletter) 
		

	)

)
